# -*- coding: utf-8 -*-
"""quests batch 2: uk, ru, pt, it"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_quests

insert_quests.LANGS["uk"] = {
    "quests_title": "Завдання",
    "quests_subtitle": "Виконуйте завдання, щоб отримувати нагороди. Прогрес зберігається у вашому браузері.",
    "quests_daily_title": "Щоденне завдання",
    "quests_daily_note": "Одне завдання на день, оновлюється кожні 24 години.",
    "quests_seasonal_title": "Сезонні завдання",
    "quests_seasonal_note": "Всі три активні протягом усього місяця. Прогрес переноситься з дня на день.",
    "quests_rewards_title": "Нагороди",
    "quests_rewards_note": "Отримайте будь-яку нагороду, щоб вимкнути рекламу на цьому пристрої.",
    "quests_reward_active": "Нагорода активна:",
    "quests_reward_active_desc": "Реклама вимкнена — продовжуйте!",
    "quests_streak_reward_title": "Серія із 20 щоденних завдань",
    "quests_streak_reward_desc": "Виконуйте щоденне завдання 20 днів поспіль.",
    "quests_season_reward_title": "10 щоденних завдань цього сезону",
    "quests_season_reward_desc": "Виконайте щоденне завдання у будь-які 10 днів цього місяця.",
    "quests_og_title": "Завдання Сапера",
    "quests_og_desc": "Виконуйте щоденні та місячні завдання Сапера. Зберіть серію з 20 днів або завершіть 10 завдань за сезон, щоб вимкнути рекламу.",
    "quest_complete": "Виконано!",
    "quest_unlocked": "Розблоковано!",
    "quest_not_complete": "Ще не виконано",
    "quest_play": "Грати",
    "quest_days": "днів",
    "quest_daily_easy_win": "Виграти Легкий Сапер",
    "quest_daily_rush_5": "Знищити 5 мін у режимі Rush",
    "quest_daily_tentaizu": "Вирішити щоденну головоломку Tentaizu",
    "quest_season_intermediate_win": "Виграти Середній Сапер",
    "quest_season_rush_100": "Знищити 100 мін у режимі Rush",
    "quest_season_tentaizu_10": "Вирішити 10 щоденних головоломок Tentaizu",
    "quest_reward_reason_streak": "Серія із 20 щоденних завдань",
    "quest_reward_reason_season": "10 щоденних завдань цього сезону",
    "quest_toast_daily_easy": "Щоденне завдання виконано! Легкий Сапер виграно.",
    "quest_toast_daily_rush": "Щоденне завдання виконано! 5 мін Rush знищено.",
    "quest_toast_daily_tentaizu": "Щоденне завдання виконано! Головоломка Tentaizu вирішена.",
    "quest_toast_reward_unlocked": "Нагорода розблокована! Реклама вимкнена — {reason}.",
    "quest_toast_season_intermediate": "Сезонне завдання виконано! Середній Сапер виграно!",
    "quest_toast_season_rush": "Сезонне завдання виконано! 100 мін Rush знищено!",
    "quest_toast_season_tentaizu": "Сезонне завдання виконано! 10 головоломок Tentaizu вирішено!",
}

insert_quests.LANGS["ru"] = {
    "quests_title": "Задания",
    "quests_subtitle": "Выполняйте задания, чтобы получать награды. Прогресс сохраняется в вашем браузере.",
    "quests_daily_title": "Ежедневное задание",
    "quests_daily_note": "Одно задание в день, меняется каждые 24 часа.",
    "quests_seasonal_title": "Сезонные задания",
    "quests_seasonal_note": "Все три активны весь месяц. Прогресс переносится день за днём.",
    "quests_rewards_title": "Награды",
    "quests_rewards_note": "Получите любую из наград, чтобы отключить рекламу на этом устройстве.",
    "quests_reward_active": "Награда активна:",
    "quests_reward_active_desc": "Реклама отключена — продолжайте!",
    "quests_streak_reward_title": "Серия из 20 ежедневных заданий",
    "quests_streak_reward_desc": "Выполняйте ежедневное задание 20 дней подряд.",
    "quests_season_reward_title": "10 ежедневных заданий в этом сезоне",
    "quests_season_reward_desc": "Выполните ежедневное задание в любые 10 дней этого месяца.",
    "quests_og_title": "Задания Сапёра",
    "quests_og_desc": "Выполняйте ежедневные и ежемесячные задания Сапёра. Наберите серию из 20 дней или завершите 10 заданий за сезон, чтобы отключить рекламу.",
    "quest_complete": "Выполнено!",
    "quest_unlocked": "Разблокировано!",
    "quest_not_complete": "Ещё не выполнено",
    "quest_play": "Играть",
    "quest_days": "дней",
    "quest_daily_easy_win": "Выиграть Лёгкий Сапёр",
    "quest_daily_rush_5": "Уничтожить 5 мин в режиме Rush",
    "quest_daily_tentaizu": "Решить ежедневную головоломку Tentaizu",
    "quest_season_intermediate_win": "Выиграть Средний Сапёр",
    "quest_season_rush_100": "Уничтожить 100 мин в режиме Rush",
    "quest_season_tentaizu_10": "Решить 10 ежедневных головоломок Tentaizu",
    "quest_reward_reason_streak": "Серия из 20 ежедневных заданий",
    "quest_reward_reason_season": "10 ежедневных заданий в этом сезоне",
    "quest_toast_daily_easy": "Ежедневное задание выполнено! Лёгкий Сапёр выигран.",
    "quest_toast_daily_rush": "Ежедневное задание выполнено! 5 мин Rush уничтожено.",
    "quest_toast_daily_tentaizu": "Ежедневное задание выполнено! Головоломка Tentaizu решена.",
    "quest_toast_reward_unlocked": "Награда разблокирована! Реклама отключена — {reason}.",
    "quest_toast_season_intermediate": "Сезонное задание выполнено! Средний Сапёр выигран!",
    "quest_toast_season_rush": "Сезонное задание выполнено! 100 мин Rush уничтожено!",
    "quest_toast_season_tentaizu": "Сезонное задание выполнено! 10 головоломок Tentaizu решено!",
}

insert_quests.LANGS["pt"] = {
    "quests_title": "Missoes",
    "quests_subtitle": "Complete missoes para ganhar recompensas. O progresso e guardado no seu navegador.",
    "quests_daily_title": "Missao diaria",
    "quests_daily_note": "Uma missao por dia, muda a cada 24 horas.",
    "quests_seasonal_title": "Missoes sazonais",
    "quests_seasonal_note": "As tres estao ativas durante o mes todo. O progresso acumula dia a dia.",
    "quests_rewards_title": "Recompensas",
    "quests_rewards_note": "Ganhe qualquer uma das recompensas para desativar os anuncios neste dispositivo.",
    "quests_reward_active": "Recompensa ativa:",
    "quests_reward_active_desc": "Os anuncios estao desativados — continue assim!",
    "quests_streak_reward_title": "Serie de 20 dias de missao diaria",
    "quests_streak_reward_desc": "Complete a sua missao diaria durante 20 dias consecutivos.",
    "quests_season_reward_title": "10 missoes diarias esta temporada",
    "quests_season_reward_desc": "Complete a sua missao diaria em quaisquer 10 dias deste mes.",
    "quests_og_title": "Missoes Campo Minado",
    "quests_og_desc": "Complete missoes diarias e mensais de Campo Minado. Consiga uma serie de 20 dias ou termine 10 missoes numa temporada para desativar os anuncios.",
    "quest_complete": "Concluido!",
    "quest_unlocked": "Desbloqueado!",
    "quest_not_complete": "Ainda nao concluido",
    "quest_play": "Jogar",
    "quest_days": "dias",
    "quest_daily_easy_win": "Ganhar Campo Minado Facil",
    "quest_daily_rush_5": "Eliminar 5 minas no modo Rush",
    "quest_daily_tentaizu": "Completar o puzzle diario de Tentaizu",
    "quest_season_intermediate_win": "Ganhar Campo Minado Intermedio",
    "quest_season_rush_100": "Eliminar 100 minas no modo Rush",
    "quest_season_tentaizu_10": "Completar 10 puzzles diarios de Tentaizu",
    "quest_reward_reason_streak": "Serie de 20 dias de missao diaria",
    "quest_reward_reason_season": "10 missoes diarias esta temporada",
    "quest_toast_daily_easy": "Missao diaria concluida! Campo Minado Facil ganho.",
    "quest_toast_daily_rush": "Missao diaria concluida! 5 minas Rush eliminadas.",
    "quest_toast_daily_tentaizu": "Missao diaria concluida! Puzzle de Tentaizu completado.",
    "quest_toast_reward_unlocked": "Recompensa desbloqueada! Anuncios desativados — {reason}.",
    "quest_toast_season_intermediate": "Missao sazonal concluida! Campo Minado Intermedio ganho!",
    "quest_toast_season_rush": "Missao sazonal concluida! 100 minas Rush eliminadas!",
    "quest_toast_season_tentaizu": "Missao sazonal concluida! 10 puzzles de Tentaizu completados!",
}

insert_quests.LANGS["it"] = {
    "quests_title": "Missioni",
    "quests_subtitle": "Completa le missioni per guadagnare ricompense. Il progresso viene salvato nel tuo browser.",
    "quests_daily_title": "Missione quotidiana",
    "quests_daily_note": "Una missione al giorno, cambia ogni 24 ore.",
    "quests_seasonal_title": "Missioni stagionali",
    "quests_seasonal_note": "Tutte e tre sono attive per tutto il mese. Il progresso si accumula giorno per giorno.",
    "quests_rewards_title": "Ricompense",
    "quests_rewards_note": "Guadagna una delle ricompense per disabilitare gli annunci su questo dispositivo.",
    "quests_reward_active": "Ricompensa attiva:",
    "quests_reward_active_desc": "Gli annunci sono disabilitati — continua cosi!",
    "quests_streak_reward_title": "Serie di 20 giorni di missione quotidiana",
    "quests_streak_reward_desc": "Completa la tua missione quotidiana per 20 giorni consecutivi.",
    "quests_season_reward_title": "10 missioni quotidiane questa stagione",
    "quests_season_reward_desc": "Completa la tua missione quotidiana in qualsiasi 10 giorni di questo mese.",
    "quests_og_title": "Missioni Puntaspilli",
    "quests_og_desc": "Completa missioni quotidiane e mensili di Puntaspilli. Guadagna una serie di 20 giorni o finisci 10 missioni in una stagione per disabilitare gli annunci.",
    "quest_complete": "Completato!",
    "quest_unlocked": "Sbloccato!",
    "quest_not_complete": "Non ancora completato",
    "quest_play": "Gioca",
    "quest_days": "giorni",
    "quest_daily_easy_win": "Vincere Puntaspilli Facile",
    "quest_daily_rush_5": "Eliminare 5 mine in modalita Rush",
    "quest_daily_tentaizu": "Completare il puzzle quotidiano di Tentaizu",
    "quest_season_intermediate_win": "Vincere Puntaspilli Intermedio",
    "quest_season_rush_100": "Eliminare 100 mine in modalita Rush",
    "quest_season_tentaizu_10": "Completare 10 puzzle quotidiani di Tentaizu",
    "quest_reward_reason_streak": "Serie di 20 giorni di missione quotidiana",
    "quest_reward_reason_season": "10 missioni quotidiane questa stagione",
    "quest_toast_daily_easy": "Missione quotidiana completata! Puntaspilli Facile vinto.",
    "quest_toast_daily_rush": "Missione quotidiana completata! 5 mine Rush eliminate.",
    "quest_toast_daily_tentaizu": "Missione quotidiana completata! Puzzle Tentaizu completato.",
    "quest_toast_reward_unlocked": "Ricompensa sbloccata! Annunci disabilitati — {reason}.",
    "quest_toast_season_intermediate": "Missione stagionale completata! Puntaspilli Intermedio vinto!",
    "quest_toast_season_rush": "Missione stagionale completata! 100 mine Rush eliminate!",
    "quest_toast_season_tentaizu": "Missione stagionale completata! 10 puzzle Tentaizu completati!",
}

if __name__ == "__main__":
    for lang in ["uk", "ru", "pt", "it"]:
        insert_quests.insert_lang(lang)
