# -*- coding: utf-8 -*-
"""15-Puzzle fp_* batch 2: uk, ru, pt, it"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_fp

insert_fp.LANGS["uk"] = {
    "fp_col_moves": "Ходи",
    "fp_gen_copy": "Копіювати",
    "fp_gen_delete": "Видалити",
    "fp_gen_file_label": "JPG або PNG, макс. 2МБ",
    "fp_gen_limit_post": "-головоломок. Видаліть збережену головоломку, щоб звільнити місце.",
    "fp_gen_limit_pre": "Ви досягли ліміту\xa0",
    "fp_gen_limit_reached": "Ліміт головоломок досягнуто",
    "fp_gen_mode_h2": "2. Виберіть режим фото",
    "fp_gen_mode_hint": "<strong>Плитки:</strong> фото нарізається по плитках і перемішується разом з ними.<br><strong>Відкриття при перемозі:</strong> плитки показують цифри; розв'язання відкриває фото знизу.",
    "fp_gen_mode_reveal": "Відкриття при перемозі",
    "fp_gen_mode_tiles": "Плитки",
    "fp_gen_no_puzzles": "Збережених головоломок ще немає. Створіть одну вище!",
    "fp_gen_refresh": "Оновити",
    "fp_gen_refresh_hint": "щоб побачити її у збереженому списку нижче.",
    "fp_gen_save_btn": "Зберегти &amp; Отримати посилання",
    "fp_gen_saved_title": "Головоломку збережено! Поділіться цим посиланням:",
    "fp_gen_scramble": "↺ Перемішати",
    "fp_gen_signin_btn": "Увійти",
    "fp_gen_signin_msg": 'Ви повинні <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">Увійти</a>, щоб завантажувати фото та зберігати головоломки.',
    "fp_gen_title_label": "Назва головоломки (необов'язково)",
    "fp_gen_title_ph": "Моя чудова головоломка",
    "fp_gen_untitled": "Головоломка без назви",
    "fp_gen_upload_h2": "1. Завантажте фото",
    "fp_gen_your_puzzles": "Ваші збережені головоломки",
    "fp_htp_back": "← Грати у сьогоднішню головоломку",
    "fp_htp_controls_desktop_li1": "<strong>Клацніть плитку</strong> поруч із порожнім місцем, щоб посунути її туди.",
    "fp_htp_controls_desktop_li2": "<strong>Клацніть плитку далі</strong> в тому самому рядку або стовпці — і весь ряд плиток між нею та порожнім місцем посувається разом за один хід, як у справжній фізичній головоломці.",
    "fp_htp_controls_desktop_li3": "<strong>Клавіші зі стрілками</strong> переміщують плитку в порожнє місце з відповідного напрямку.",
    "fp_htp_controls_footer": "Натисніть кнопку <strong>Нова гра</strong>, щоб скинути дошку та почати знову в будь-який момент.",
    "fp_htp_controls_h2": "Управління",
    "fp_htp_controls_mobile_li1": "<strong>Торкніться плитки</strong> поруч із порожнім місцем, щоб посунути її туди.",
    "fp_htp_controls_mobile_li2": "<strong>Торкніться плитки далі</strong> в тому самому рядку або стовпці — і весь рядок або стовпець посувається за один хід.",
    "fp_htp_daily_h2": "Щоденна головоломка",
    "fp_htp_daily_p1": "Щодня опівночі за UTC генерується нова головоломка — однакова перемішана дошка для кожного гравця у світі. Розв'яжіть її, надішліть свій результат і подивіться своє місце в таблиці лідерів.",
    "fp_htp_daily_p2": 'Ви також можете створити власну фотоголоволомку за допомогою <a href="/other/15puzzle/generator">Генератора головоломок</a> — завантажте будь-яке зображення, виберіть режим і поділіться посиланням з ким завгодно.',
    "fp_htp_desc": "Дізнайтеся, як грати у головоломку 15 — класичну гру з плитками, що ковзають. Зрозумійте правила, управління, режими фото та стратегію для швидкого розв'язання.",
    "fp_htp_ex_midgame": "На середині гри. Верхні рядки поступово стають на місця. Зосередьтеся на завершенні одного рядка за раз, зверху вниз.",
    "fp_htp_ex_nearlydone": "Майже готово. Лише нижні рядки залишаються перемішаними. На цьому етапі потрібні невеликі корекції — не псуйте вже розв'язані рядки.",
    "fp_htp_ex_scrambled": "Початкова позиція. Плитки перемішані, але завжди мають розв'язок. Порожнє місце (темний квадрат) може знаходитися будь-де на дошці.",
    "fp_htp_ex_solved": "Розв'язано! Усі плитки стоять у порядку, і повне зображення відкрито. Ваш час і кількість ходів зафіксовані для таблиці лідерів.",
    "fp_htp_example_h2": "Приклад: розв'язання крок за кроком",
    "fp_htp_example_intro": "Наведені нижче знімки екрана показують розв'язання фотоголоволомки з використанням Lady Di's Mines як зображення. Кожна плитка має цифру та фрагмент картинки — тому ви можете використовувати зображення як візуальну підказку під час розв'язання.",
    "fp_htp_goal_h2": "Мета",
    "fp_htp_goal_p1": "Розставте всі 15 плиток у зростаючому порядку — зліва направо, зверху вниз — із порожнім місцем у правому нижньому куті. Розв'язана позиція виглядає так: 1, 2, 3, 4 у верхньому рядку, потім 5, 6, 7, 8, потім 9, 10, 11, 12, потім 13, 14, 15 і порожня клітинка.",
    "fp_htp_goal_p2": "Ваш результат — це поєднання кількості використаних ходів та швидкості розв'язання. Менше ходів і менше часу означає кращу позицію в таблиці лідерів.",
    "fp_htp_intro": "Головоломка 15 — це класична гра з плитками, що ковзають, на сітці 4×4. П'ятнадцять пронумерованих плиток заповнюють дошку, залишаючи одне порожнє місце. Посувайте плитки в порожнє місце, щоб перебудувати їх, доки всі плитки не стануть у порядку від 1 до 15.",
    "fp_htp_photo_h2": "Режими фотоголоволомки",
    "fp_htp_photo_p1": "Щоденна головоломка та власні фотоголоволомки пропонують два різних візуальних режими:",
    "fp_htp_photo_reveal": "<strong>Відкриття при перемозі</strong> — плитки показують лише цифри під час розв'язання. Коли ви правильно розміщуєте останню плитку, повне фото відкривається знизу. Зображення є нагородою за завершення, а не підказкою.",
    "fp_htp_photo_tiles": "<strong>Режим плиток</strong> — кожна плитка показує свою частину фото. Зображення дає вам візуальний контекст для розв'язання — використовуйте картинку як другий шар інформації поверх цифр.",
    "fp_htp_strategy_h2": "Стратегія",
    "fp_htp_strategy_p1": "<strong>Розв'язуйте рядок за рядком зверху.</strong> Рядки 1 і 2 можна кожен завершити та зафіксувати на місці, не зачіпаючи нічого вище. Останні два рядки (плитки 9–15) розв'язуються разом за допомогою техніки обертання.",
    "fp_htp_strategy_p2": "<strong>Ставте плитку 1 і плитку 2 разом.</strong> Спроба посунути плитку 1 на місце самостійно часто зміщує плитку 2. Натомість одночасно маневруйте обома плитками 1 і 2 у їхні правильні позиції у стовпці, а потім разом вводьте їх у верхній рядок.",
    "fp_htp_strategy_p3": "<strong>Використовуйте багатоплиткові ковзання.</strong> Клацання або торкання плитки, що не є безпосередньо сусідньою з порожнім місцем, посуває весь проміжний рядок або стовпець. Це швидше, ніж переміщати плитки по одній, і є необхідним для ефективного розв'язання.",
    "fp_htp_strategy_p4": "<strong>Рахуйте свої ходи.</strong> Кожне ковзання вважається одним ходом, включно з багатоплитковими ковзаннями. Одне добре сплановане багатоплиткове ковзання може замінити кілька одиночних ходів — плануйте наперед, щоб мінімізувати їх кількість.",
    "fp_htp_title": "Як грати у головоломку 15 | minesweeper.org",
    "fp_moves": "Ходи:",
    "fp_name_label": "Ім'я",
    "fp_new_game": "↺ Нова гра",
    "fp_photo_puzzle": "Фотоголоволомка",
    "fp_same_for_all": "Однакова головоломка для всіх · Скидається опівночі UTC",
    "fp_solved": "🎉 Розв'язано!",
    "fp_submit_score": "Надіслати результат",
    "fp_time": "Час:",
    "fp_today_heading": "Сьогодні — ",
}

insert_fp.LANGS["ru"] = {
    "fp_col_moves": "Ходы",
    "fp_gen_copy": "Копировать",
    "fp_gen_delete": "Удалить",
    "fp_gen_file_label": "JPG или PNG, макс. 2МБ",
    "fp_gen_limit_post": "-головоломок. Удалите сохранённую головоломку, чтобы освободить место.",
    "fp_gen_limit_pre": "Вы достигли лимита\xa0",
    "fp_gen_limit_reached": "Лимит головоломок достигнут",
    "fp_gen_mode_h2": "2. Выберите режим фото",
    "fp_gen_mode_hint": "<strong>Плитки:</strong> фото нарезается по плиткам и перемешивается вместе с ними.<br><strong>Открытие при победе:</strong> плитки показывают цифры; решение открывает фото снизу.",
    "fp_gen_mode_reveal": "Открытие при победе",
    "fp_gen_mode_tiles": "Плитки",
    "fp_gen_no_puzzles": "Сохранённых головоломок пока нет. Создайте одну выше!",
    "fp_gen_refresh": "Обновить",
    "fp_gen_refresh_hint": "чтобы увидеть её в сохранённом списке ниже.",
    "fp_gen_save_btn": "Сохранить &amp; Получить ссылку",
    "fp_gen_saved_title": "Головоломка сохранена! Поделитесь этой ссылкой:",
    "fp_gen_scramble": "↺ Перемешать",
    "fp_gen_signin_btn": "Войти",
    "fp_gen_signin_msg": 'Вы должны <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">Войти</a>, чтобы загружать фото и сохранять головоломки.',
    "fp_gen_title_label": "Название головоломки (необязательно)",
    "fp_gen_title_ph": "Моя замечательная головоломка",
    "fp_gen_untitled": "Головоломка без названия",
    "fp_gen_upload_h2": "1. Загрузите фото",
    "fp_gen_your_puzzles": "Ваши сохранённые головоломки",
    "fp_htp_back": "← Играть в сегодняшнюю головоломку",
    "fp_htp_controls_desktop_li1": "<strong>Нажмите на плитку</strong> рядом с пустым местом, чтобы сдвинуть её туда.",
    "fp_htp_controls_desktop_li2": "<strong>Нажмите на плитку подальше</strong> в той же строке или столбце — и весь ряд плиток между ней и пустым местом сдвигается вместе за один ход, как в настоящей физической головоломке.",
    "fp_htp_controls_desktop_li3": "<strong>Клавиши со стрелками</strong> перемещают плитку в пустое место из соответствующего направления.",
    "fp_htp_controls_footer": "Нажмите кнопку <strong>Новая игра</strong>, чтобы сбросить поле и начать заново в любое время.",
    "fp_htp_controls_h2": "Управление",
    "fp_htp_controls_mobile_li1": "<strong>Нажмите на плитку</strong> рядом с пустым местом, чтобы сдвинуть её туда.",
    "fp_htp_controls_mobile_li2": "<strong>Нажмите на плитку подальше</strong> в той же строке или столбце — и весь ряд или столбец сдвигается за один ход.",
    "fp_htp_daily_h2": "Ежедневная головоломка",
    "fp_htp_daily_p1": "Каждый день в полночь по UTC генерируется новая головоломка — одинаковое перемешанное поле для каждого игрока в мире. Решите её, отправьте свой результат и узнайте своё место в таблице лидеров.",
    "fp_htp_daily_p2": 'Вы также можете создать собственную фотоголоволомку с помощью <a href="/other/15puzzle/generator">Генератора головоломок</a> — загрузите любое изображение, выберите режим и поделитесь ссылкой с кем угодно.',
    "fp_htp_desc": "Узнайте, как играть в головоломку 15 — классическую игру с передвижными плитками. Поймите правила, управление, режимы фото и стратегию для быстрого решения.",
    "fp_htp_ex_midgame": "На середине игры. Верхние ряды постепенно встают на места. Сосредоточьтесь на завершении одного ряда за раз, сверху вниз.",
    "fp_htp_ex_nearlydone": "Почти готово. Только нижние ряды остаются перемешанными. На этом этапе нужны небольшие корректировки — не нарушайте уже решённые ряды.",
    "fp_htp_ex_scrambled": "Начальная позиция. Плитки перемешаны, но решение всегда существует. Пустое место (тёмный квадрат) может находиться в любом месте поля.",
    "fp_htp_ex_solved": "Решено! Все плитки стоят по порядку, и полное изображение открыто. Ваше время и количество ходов зафиксированы для таблицы лидеров.",
    "fp_htp_example_h2": "Пример: решение шаг за шагом",
    "fp_htp_example_intro": "Приведённые ниже снимки экрана показывают решение фотоголоволомки с использованием Lady Di's Mines в качестве изображения. Каждая плитка несёт цифру и фрагмент картинки — поэтому вы можете использовать изображение как визуальный ориентир при решении.",
    "fp_htp_goal_h2": "Цель",
    "fp_htp_goal_p1": "Расставьте все 15 плиток в возрастающем порядке — слева направо, сверху вниз — с пустым местом в правом нижнем углу. Решённая позиция выглядит так: 1, 2, 3, 4 в верхнем ряду, затем 5, 6, 7, 8, затем 9, 10, 11, 12, затем 13, 14, 15 и пустая клетка.",
    "fp_htp_goal_p2": "Ваш результат — это сочетание количества использованных ходов и скорости решения. Меньше ходов и меньше времени означает лучшую позицию в таблице лидеров.",
    "fp_htp_intro": "Головоломка 15 — это классическая игра с передвижными плитками на поле 4×4. Пятнадцать пронумерованных плиток заполняют поле, оставляя одно пустое место. Двигайте плитки в пустое место, чтобы перестроить их, пока все плитки не встанут по порядку от 1 до 15.",
    "fp_htp_photo_h2": "Режимы фотоголоволомки",
    "fp_htp_photo_p1": "Ежедневная головоломка и пользовательские фотоголоволомки предлагают два разных визуальных режима:",
    "fp_htp_photo_reveal": "<strong>Открытие при победе</strong> — плитки показывают только цифры во время решения. Когда вы правильно размещаете последнюю плитку, полное фото открывается снизу. Изображение является наградой за завершение, а не подсказкой.",
    "fp_htp_photo_tiles": "<strong>Режим плиток</strong> — каждая плитка показывает свою часть фото. Изображение даёт вам визуальный контекст для решения — используйте картинку как второй слой информации поверх цифр.",
    "fp_htp_strategy_h2": "Стратегия",
    "fp_htp_strategy_p1": "<strong>Решайте ряд за рядом сверху.</strong> Ряды 1 и 2 можно каждый завершить и зафиксировать на месте, не затрагивая ничего выше. Последние два ряда (плитки 9–15) решаются вместе с помощью техники вращения.",
    "fp_htp_strategy_p2": "<strong>Ставьте плитку 1 и плитку 2 вместе.</strong> Попытка сдвинуть плитку 1 на место самостоятельно часто смещает плитку 2. Вместо этого одновременно маневрируйте обеими плитками 1 и 2 на их правильные позиции в столбце, а затем вместе вводите их в верхний ряд.",
    "fp_htp_strategy_p3": "<strong>Используйте многоплиточные сдвиги.</strong> Нажатие на плитку, которая не является непосредственно соседней с пустым местом, сдвигает весь промежуточный ряд или столбец. Это быстрее, чем перемещать плитки по одной, и необходимо для эффективного решения.",
    "fp_htp_strategy_p4": "<strong>Считайте свои ходы.</strong> Каждый сдвиг считается одним ходом, включая многоплиточные сдвиги. Один хорошо спланированный многоплиточный сдвиг может заменить несколько одиночных ходов — планируйте заранее, чтобы минимизировать их количество.",
    "fp_htp_title": "Как играть в головоломку 15 | minesweeper.org",
    "fp_moves": "Ходы:",
    "fp_name_label": "Имя",
    "fp_new_game": "↺ Новая игра",
    "fp_photo_puzzle": "Фотоголоволомка",
    "fp_same_for_all": "Одинаковая головоломка для всех · Сбрасывается в полночь UTC",
    "fp_solved": "🎉 Решено!",
    "fp_submit_score": "Отправить результат",
    "fp_time": "Время:",
    "fp_today_heading": "Сегодня — ",
}

insert_fp.LANGS["pt"] = {
    "fp_col_moves": "Jogadas",
    "fp_gen_copy": "Copiar",
    "fp_gen_delete": "Excluir",
    "fp_gen_file_label": "JPG ou PNG, máx. 2MB",
    "fp_gen_limit_post": " puzzles. Exclua um puzzle salvo para liberar espaço.",
    "fp_gen_limit_pre": "Você atingiu seu limite de\xa0",
    "fp_gen_limit_reached": "Limite de puzzles atingido",
    "fp_gen_mode_h2": "2. Escolha o Modo de Foto",
    "fp_gen_mode_hint": "<strong>Peças:</strong> a foto é dividida entre as peças e embaralhada com elas.<br><strong>Revelar ao vencer:</strong> as peças mostram números; resolver o puzzle revela a foto por baixo.",
    "fp_gen_mode_reveal": "Revelar ao vencer",
    "fp_gen_mode_tiles": "Peças",
    "fp_gen_no_puzzles": "Nenhum puzzle salvo ainda. Crie um acima!",
    "fp_gen_refresh": "Atualizar",
    "fp_gen_refresh_hint": "para vê-lo na sua lista salva abaixo.",
    "fp_gen_save_btn": "Salvar &amp; Obter Link",
    "fp_gen_saved_title": "Puzzle salvo! Compartilhe este link:",
    "fp_gen_scramble": "↺ Embaralhar",
    "fp_gen_signin_btn": "Entrar",
    "fp_gen_signin_msg": 'Você precisa <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">Entrar</a> para enviar fotos e salvar puzzles.',
    "fp_gen_title_label": "Título do puzzle (opcional)",
    "fp_gen_title_ph": "Meu incrível puzzle",
    "fp_gen_untitled": "Puzzle sem título",
    "fp_gen_upload_h2": "1. Envie uma Foto",
    "fp_gen_your_puzzles": "Seus Puzzles Salvos",
    "fp_htp_back": "← Jogar o Puzzle de Hoje",
    "fp_htp_controls_desktop_li1": "<strong>Clique em uma peça</strong> adjacente ao espaço vazio para deslizá-la.",
    "fp_htp_controls_desktop_li2": "<strong>Clique em uma peça mais distante</strong> na mesma linha ou coluna e toda a fileira de peças entre ela e o espaço vazio desliza junto em uma jogada — assim como um puzzle físico de verdade.",
    "fp_htp_controls_desktop_li3": "<strong>Teclas de seta</strong> movem uma peça para o espaço vazio a partir da direção correspondente.",
    "fp_htp_controls_footer": "Use o botão <strong>Novo Jogo</strong> para reiniciar o tabuleiro e começar de novo a qualquer momento.",
    "fp_htp_controls_h2": "Controles",
    "fp_htp_controls_mobile_li1": "<strong>Toque em uma peça</strong> adjacente ao espaço vazio para deslizá-la.",
    "fp_htp_controls_mobile_li2": "<strong>Toque em uma peça mais distante</strong> na mesma linha ou coluna e toda a linha ou coluna desliza em uma jogada.",
    "fp_htp_daily_h2": "Puzzle Diário",
    "fp_htp_daily_p1": "Um novo puzzle é gerado todos os dias à meia-noite UTC — o mesmo tabuleiro embaralhado para todos os jogadores do mundo. Resolva-o, envie sua pontuação e veja como você se classifica no placar.",
    "fp_htp_daily_p2": 'Você também pode criar seu próprio puzzle com foto usando o <a href="/other/15puzzle/generator">Gerador de Puzzles</a> — envie qualquer imagem, escolha seu modo e compartilhe o link com qualquer pessoa.',
    "fp_htp_desc": "Aprenda a jogar o Puzzle de 15 — o clássico jogo de peças deslizantes. Entenda as regras, controles, modos de foto e estratégia para resolvê-lo rapidamente.",
    "fp_htp_ex_midgame": "No meio do jogo. As fileiras superiores estão se encaixando. Concentre-se em completar uma fileira por vez, de cima para baixo.",
    "fp_htp_ex_nearlydone": "Quase terminando. Apenas as fileiras inferiores permanecem embaralhadas. Nesta fase, pequenos ajustes são necessários — evite desfazer o progresso nas fileiras já resolvidas.",
    "fp_htp_ex_scrambled": "A posição inicial. As peças são randomizadas mas sempre têm solução. O espaço vazio (quadrado escuro) pode estar em qualquer lugar do tabuleiro.",
    "fp_htp_ex_solved": "Resolvido! Todas as peças estão em ordem e a imagem completa é revelada. Seu tempo e número de jogadas são registrados para o placar.",
    "fp_htp_example_h2": "Exemplo: Resolvendo Passo a Passo",
    "fp_htp_example_intro": "As capturas de tela abaixo mostram um puzzle com foto sendo resolvido usando Lady Di's Mines como imagem. Cada peça carrega um número e um fragmento da imagem — assim você pode usar a imagem como guia visual enquanto resolve.",
    "fp_htp_goal_h2": "O Objetivo",
    "fp_htp_goal_p1": "Organize todas as 15 peças em ordem crescente — da esquerda para a direita, de cima para baixo — com o espaço vazio no canto inferior direito. A posição resolvida fica assim: 1, 2, 3, 4 na fileira superior, depois 5, 6, 7, 8, depois 9, 10, 11, 12, depois 13, 14, 15 e o espaço em branco.",
    "fp_htp_goal_p2": "Sua pontuação é uma combinação de quantas jogadas você usou e quão rápido resolveu. Menos jogadas e menos tempo significa uma melhor classificação no placar.",
    "fp_htp_intro": "O Puzzle de 15 é um clássico jogo de peças deslizantes jogado em uma grade 4×4. Quinze peças numeradas preenchem o tabuleiro, deixando um espaço vazio. Deslize as peças para o espaço vazio para reorganizá-las até que todas estejam em ordem de 1 a 15.",
    "fp_htp_photo_h2": "Modos de Puzzle com Foto",
    "fp_htp_photo_p1": "O puzzle diário e os puzzles com foto personalizados oferecem dois modos visuais diferentes:",
    "fp_htp_photo_reveal": "<strong>Revelar ao vencer</strong> — as peças mostram apenas números enquanto você resolve. Quando você posiciona a última peça corretamente, a foto completa é revelada por baixo. A imagem é uma recompensa por terminar, não uma dica.",
    "fp_htp_photo_tiles": "<strong>Modo Peças</strong> — cada peça mostra seu recorte da foto. A imagem fornece contexto visual para guiar sua resolução — use a imagem como uma segunda camada de informação além dos números.",
    "fp_htp_strategy_h2": "Estratégia",
    "fp_htp_strategy_p1": "<strong>Resolva fileira por fileira de cima.</strong> As fileiras 1 e 2 podem ser completadas e fixadas no lugar sem perturbar nada acima. As duas últimas fileiras (peças 9–15) são resolvidas juntas usando uma técnica de rotação.",
    "fp_htp_strategy_p2": "<strong>Posicione a peça 1 e a peça 2 juntas.</strong> Tentar deslizar a peça 1 para a posição sozinha frequentemente desloca a peça 2. Em vez disso, manobre as peças 1 e 2 simultaneamente para suas posições corretas na coluna, depois as rotacione para a fileira superior ao mesmo tempo.",
    "fp_htp_strategy_p3": "<strong>Use deslizamentos de múltiplas peças.</strong> Clicar ou tocar em uma peça que não é diretamente adjacente ao espaço vazio desliza toda a fileira ou coluna intermediária. Isso é mais rápido do que mover peças uma por vez e é essencial para uma resolução eficiente.",
    "fp_htp_strategy_p4": "<strong>Conte suas jogadas.</strong> Cada deslizamento conta como uma jogada, incluindo deslizamentos de múltiplas peças. Um único deslizamento bem planejado de múltiplas peças pode economizar várias jogadas individuais — planeje com antecedência para minimizar seu total.",
    "fp_htp_title": "Como Jogar o Puzzle de 15 | minesweeper.org",
    "fp_moves": "Jogadas:",
    "fp_name_label": "Nome",
    "fp_new_game": "↺ Novo Jogo",
    "fp_photo_puzzle": "Puzzle com foto",
    "fp_same_for_all": "Mesmo puzzle para todos · Reinicia à meia-noite UTC",
    "fp_solved": "🎉 Resolvido!",
    "fp_submit_score": "Enviar pontuação",
    "fp_time": "Tempo:",
    "fp_today_heading": "Hoje — ",
}

insert_fp.LANGS["it"] = {
    "fp_col_moves": "Mosse",
    "fp_gen_copy": "Copia",
    "fp_gen_delete": "Elimina",
    "fp_gen_file_label": "JPG o PNG, max 2MB",
    "fp_gen_limit_post": " puzzle. Elimina un puzzle salvato per fare spazio.",
    "fp_gen_limit_pre": "Hai raggiunto il limite di\xa0",
    "fp_gen_limit_reached": "Limite di puzzle raggiunto",
    "fp_gen_mode_h2": "2. Scegli la Modalità Foto",
    "fp_gen_mode_hint": "<strong>Tessere:</strong> la foto viene suddivisa tra le tessere e mescolata con esse.<br><strong>Rivela alla vittoria:</strong> le tessere mostrano numeri; risolvendo il puzzle si rivela la foto sottostante.",
    "fp_gen_mode_reveal": "Rivela alla vittoria",
    "fp_gen_mode_tiles": "Tessere",
    "fp_gen_no_puzzles": "Nessun puzzle salvato ancora. Creane uno sopra!",
    "fp_gen_refresh": "Aggiorna",
    "fp_gen_refresh_hint": "per vederlo nell'elenco salvato qui sotto.",
    "fp_gen_save_btn": "Salva &amp; Ottieni Link",
    "fp_gen_saved_title": "Puzzle salvato! Condividi questo link:",
    "fp_gen_scramble": "↺ Mescola",
    "fp_gen_signin_btn": "Accedi",
    "fp_gen_signin_msg": 'Devi <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">Accedere</a> per caricare foto e salvare puzzle.',
    "fp_gen_title_label": "Titolo del puzzle (opzionale)",
    "fp_gen_title_ph": "Il mio fantastico puzzle",
    "fp_gen_untitled": "Puzzle senza titolo",
    "fp_gen_upload_h2": "1. Carica una Foto",
    "fp_gen_your_puzzles": "I Tuoi Puzzle Salvati",
    "fp_htp_back": "← Gioca al Puzzle di Oggi",
    "fp_htp_controls_desktop_li1": "<strong>Clicca su una tessera</strong> adiacente allo spazio vuoto per farla scorrere.",
    "fp_htp_controls_desktop_li2": "<strong>Clicca su una tessera più lontana</strong> nella stessa riga o colonna e l'intera fila di tessere tra essa e lo spazio vuoto scorre insieme in una sola mossa — proprio come un vero puzzle fisico.",
    "fp_htp_controls_desktop_li3": "<strong>I tasti freccia</strong> spostano una tessera nello spazio vuoto dalla direzione corrispondente.",
    "fp_htp_controls_footer": "Usa il pulsante <strong>Nuova Partita</strong> per resettare il tabellone e ricominciare in qualsiasi momento.",
    "fp_htp_controls_h2": "Controlli",
    "fp_htp_controls_mobile_li1": "<strong>Tocca una tessera</strong> adiacente allo spazio vuoto per farla scorrere.",
    "fp_htp_controls_mobile_li2": "<strong>Tocca una tessera più lontana</strong> nella stessa riga o colonna e l'intera riga o colonna scorre in una sola mossa.",
    "fp_htp_daily_h2": "Puzzle Quotidiano",
    "fp_htp_daily_p1": "Ogni giorno a mezzanotte UTC viene generato un nuovo puzzle — lo stesso tabellone mischiato per ogni giocatore nel mondo. Risolvilo, invia il tuo punteggio e scopri la tua posizione in classifica.",
    "fp_htp_daily_p2": 'Puoi anche creare il tuo puzzle fotografico usando il <a href="/other/15puzzle/generator">Generatore di Puzzle</a> — carica qualsiasi immagine, scegli la modalità e condividi il link con chiunque.',
    "fp_htp_desc": "Scopri come giocare al Puzzle del 15 — il classico gioco di tessere scorrevoli. Comprendi le regole, i controlli, le modalità foto e la strategia per risolverlo velocemente.",
    "fp_htp_ex_midgame": "A metà partita. Le righe superiori stanno andando al loro posto. Concentrati sul completare una riga alla volta dall'alto verso il basso.",
    "fp_htp_ex_nearlydone": "Quasi finito. Solo le righe inferiori rimangono mescolate. In questa fase sono necessari piccoli aggiustamenti — evita di disfare i progressi nelle righe già risolte.",
    "fp_htp_ex_scrambled": "La posizione iniziale. Le tessere sono randomizzate ma sempre risolvibili. Lo spazio vuoto (quadrato scuro) può trovarsi ovunque sul tabellone.",
    "fp_htp_ex_solved": "Risolto! Tutte le tessere sono in ordine e l'immagine completa è rivelata. Il tuo tempo e il conteggio delle mosse sono registrati per la classifica.",
    "fp_htp_example_h2": "Esempio: Risoluzione Passo dopo Passo",
    "fp_htp_example_intro": "Gli screenshot qui sotto mostrano un puzzle fotografico in fase di risoluzione usando Lady Di's Mines come immagine. Ogni tessera porta un numero e un frammento dell'immagine — così puoi usare l'immagine come guida visiva mentre risolvi.",
    "fp_htp_goal_h2": "L'Obiettivo",
    "fp_htp_goal_p1": "Disponi tutte le 15 tessere in ordine crescente — da sinistra a destra, dall'alto verso il basso — con lo spazio vuoto nell'angolo in basso a destra. La posizione risolta appare così: 1, 2, 3, 4 nella riga superiore, poi 5, 6, 7, 8, poi 9, 10, 11, 12, poi 13, 14, 15 e lo spazio bianco.",
    "fp_htp_goal_p2": "Il tuo punteggio è una combinazione di quante mosse hai usato e di quanto velocemente hai risolto. Meno mosse e meno tempo significano una migliore posizione in classifica.",
    "fp_htp_intro": "Il Puzzle del 15 è un classico gioco di tessere scorrevoli su una griglia 4×4. Quindici tessere numerate riempiono il tabellone, lasciando uno spazio vuoto. Fai scorrere le tessere nello spazio vuoto per riordinarle finché tutte non sono in ordine da 1 a 15.",
    "fp_htp_photo_h2": "Modalità Puzzle Fotografico",
    "fp_htp_photo_p1": "Il puzzle quotidiano e i puzzle fotografici personalizzati offrono due diverse modalità visive:",
    "fp_htp_photo_reveal": "<strong>Rivela alla vittoria</strong> — le tessere mostrano solo numeri mentre risolvi. Quando posizioni l'ultima tessera correttamente, la foto completa viene rivelata al di sotto. L'immagine è una ricompensa per aver finito, non un suggerimento.",
    "fp_htp_photo_tiles": "<strong>Modalità Tessere</strong> — ogni tessera mostra la sua porzione della foto. L'immagine ti fornisce un contesto visivo per guidare la risoluzione — usa l'immagine come un secondo livello di informazioni oltre ai numeri.",
    "fp_htp_strategy_h2": "Strategia",
    "fp_htp_strategy_p1": "<strong>Risolvi riga per riga dall'alto.</strong> Le righe 1 e 2 possono essere completate e bloccate al loro posto senza disturbare nulla sopra. Le ultime due righe (tessere 9–15) vengono risolte insieme usando una tecnica di rotazione.",
    "fp_htp_strategy_p2": "<strong>Posiziona la tessera 1 e la tessera 2 insieme.</strong> Cercare di far scorrere la tessera 1 da sola spesso sposta la tessera 2. Invece, manovra entrambe le tessere 1 e 2 nelle loro posizioni corrette nella colonna simultaneamente, poi ruotale nella riga superiore allo stesso tempo.",
    "fp_htp_strategy_p3": "<strong>Usa gli scorrimenti multi-tessera.</strong> Cliccare o toccare una tessera che non è direttamente adiacente allo spazio vuoto fa scorrere l'intera riga o colonna intermedia. Questo è più veloce che spostare le tessere una alla volta ed è essenziale per una risoluzione efficiente.",
    "fp_htp_strategy_p4": "<strong>Conta le tue mosse.</strong> Ogni scorrimento conta come una mossa, inclusi gli scorrimenti multi-tessera. Un singolo scorrimento multi-tessera ben pianificato può risparmiare diverse mosse singole — pianifica in anticipo per minimizzare il tuo conteggio.",
    "fp_htp_title": "Come Giocare al Puzzle del 15 | minesweeper.org",
    "fp_moves": "Mosse:",
    "fp_name_label": "Nome",
    "fp_new_game": "↺ Nuova partita",
    "fp_photo_puzzle": "Puzzle fotografico",
    "fp_same_for_all": "Stesso puzzle per tutti · Si resetta a mezzanotte UTC",
    "fp_solved": "🎉 Risolto!",
    "fp_submit_score": "Invia il tuo punteggio",
    "fp_time": "Tempo:",
    "fp_today_heading": "Oggi — ",
}

if __name__ == "__main__":
    for lang in ["uk", "ru", "pt", "it"]:
        insert_fp.insert_lang(lang)
