# -*- coding: utf-8 -*-
"""t2k_* batch 2: uk, ru, pt, it"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_t2k

insert_t2k.LANGS["uk"] = {
    "t2k_game_over": "😥 Гра закінчена",
    "t2k_htp_back": "← Грати у сьогоднішній пазл",
    "t2k_htp_controls_desktop_li1": "<strong>Клавіші зі стрілками</strong> або <strong>W A S D</strong> — зсунути всі плитки в цьому напрямку.",
    "t2k_htp_controls_desktop_li2": "Кожне натискання клавіші — один хід, навіть якщо переміщається лише одна плитка.",
    "t2k_htp_controls_footer": "Використовуйте кнопку <strong>Нова гра</strong>, щоб скинути поле та почати заново будь-коли.",
    "t2k_htp_controls_h2": "Управління",
    "t2k_htp_controls_mobile_li1": "<strong>Проведіть пальцем</strong> вгору, вниз, вліво або вправо, щоб зсунути всі плитки в цьому напрямку.",
    "t2k_htp_controls_mobile_li2": "Кожен свайп — один хід, навіть якщо переміщається лише одна плитка.",
    "t2k_htp_daily_h2": "Щоденний пазл",
    "t2k_htp_daily_p1": "Щодня генерується новий пазл — одне й те саме початкове поле для кожного гравця у світі. Пазл скидається опівночі UTC. Усі, хто грає у щоденний пазл у певний день, починають з однакового розташування плиток, що робить це чесним змаганням.",
    "t2k_htp_daily_p2": 'Після завершення щоденного пазлу ви можете відправити свій рахунок до <a href="/other/2048/leaderboard">таблиці лідерів 2048</a>. Вам потрібно увійти в систему для відправки.',
    "t2k_htp_desc": "Дізнайтеся, як грати в 2048 — класичний пазл зі злиттям плиток. Зрозумійте правила, управління, підрахунок очок та стратегію для досягнення плитки 2048.",
    "t2k_htp_goal_h2": "Мета",
    "t2k_htp_goal_p1": "Зсувайте плитки на сітці для злиття однакових чисел. Коли дві плитки з однаковим значенням стикаються, вони поєднуються в одну плитку вартістю вдвічі більше — 2 і 2 стають 4, дві 4 стають 8 і так далі. Мета — побудувати плитку, що досягає <strong>2048</strong>.",
    "t2k_htp_goal_p2": "Ви можете продовжувати гру після досягнення 2048, щоб збільшити рахунок. Гра закінчується, коли не залишається ходів — сітка повна і жодні сусідні плитки не мають однакового значення.",
    "t2k_htp_intro": "2048 — це пазл із ковзними плитками на сітці 4×4. Поєднуйте пронумеровані плитки, зсуваючи їх у чотири напрямки. Після кожного ходу з'являється нова плитка. Досягніть плитки 2048, щоб виграти — або продовжуйте заради вищого рахунку.",
    "t2k_htp_scoring_h2": "Підрахунок очок",
    "t2k_htp_scoring_p1": "Кожне злиття додає значення нової об'єднаної плитки до вашого рахунку. Злиття двох плиток 512 в плитку 1024 додає 1024 очки. Об'єднання кількох злиттів за один хід додає їх усі разом.",
    "t2k_htp_scoring_p2": 'У щоденному пазлі ваш фінальний рахунок, кількість ходів та час записуються і надсилаються до <a href="/other/2048/leaderboard">таблиці лідерів</a>. Таблиця лідерів ранжується спочатку за рахунком (вище краще), потім за часом (нижче краще).',
    "t2k_htp_strategy_h2": "Базова стратегія",
    "t2k_htp_strategy_p1": "<strong>Оберіть кут і дотримуйтесь його.</strong> Оберіть один кут — зазвичай нижній — і тримайте там свою найціннішу плитку. Будуйте низхідний ланцюжок плиток уздовж краю, що відходить від нього, щоб кожне злиття природно переходило до наступного.",
    "t2k_htp_strategy_p2": "<strong>Ніколи не зсувайтесь від свого кутового якоря.</strong> Уникайте ходів, які відтягують вашу найбільшу плитку від її кута. Наприклад, якщо ваша найвища плитка знаходиться внизу ліворуч, уникайте зсуву вгору, якщо це не є абсолютно необхідним. Втрата контролю над кутом — ось як закінчується більшість ігор.",
    "t2k_htp_strategy_p3": "<strong>Тримайте верхній рядок повним.</strong> Коли у вас є ланцюжок уздовж верхнього або нижнього краю, намагайтеся тримати цей рядок завжди повним. Це змушує нові плитки з'являтися в іншому місці та зберігає ваш ланцюжок.",
    "t2k_htp_strategy_p4": "<strong>Думайте наперед.</strong> Перед кожним ходом розгляньте, де може з'явитися нова плитка і чи порушить вона ваше розташування. Ходи, що залишають поле у невідновлюваному стані, зазвичай є ознакою того, що ви рухалися без роздумів.",
    "t2k_htp_tiles_h2": "Значення плиток",
    "t2k_htp_tiles_p1": "Плитки завжди починаються як 2 або 4 — є 90% шанс на 2 і 10% на 4. Нові плитки з'являються випадково у порожній клітинці після кожного ходу. Послідовність значень подвоюється з кожним злиттям: 2 → 4 → 8 → 16 → 32 → 64 → 128 → 256 → 512 → 1024 → 2048 і далі.",
    "t2k_htp_tiles_p2": "Лише плитки з однаковим значенням можуть об'єднуватися, і кожна плитка може об'єднатися максимум один раз за хід.",
    "t2k_htp_title": "Як грати в 2048 | minesweeper.org",
    "t2k_keep_going": "Продовжити",
    "t2k_score": "Рахунок:",
    "t2k_solved": "Ви досягли 2048!",
}

insert_t2k.LANGS["ru"] = {
    "t2k_game_over": "😥 Игра окончена",
    "t2k_htp_back": "← Играть в сегодняшний пазл",
    "t2k_htp_controls_desktop_li1": "<strong>Клавиши со стрелками</strong> или <strong>W A S D</strong> — сдвинуть все плитки в этом направлении.",
    "t2k_htp_controls_desktop_li2": "Каждое нажатие клавиши — один ход, даже если перемещается только одна плитка.",
    "t2k_htp_controls_footer": "Используйте кнопку <strong>Новая игра</strong> для сброса поля и начала заново в любое время.",
    "t2k_htp_controls_h2": "Управление",
    "t2k_htp_controls_mobile_li1": "<strong>Проведите пальцем</strong> вверх, вниз, влево или вправо, чтобы сдвинуть все плитки в этом направлении.",
    "t2k_htp_controls_mobile_li2": "Каждый свайп — один ход, даже если перемещается только одна плитка.",
    "t2k_htp_daily_h2": "Ежедневный пазл",
    "t2k_htp_daily_p1": "Каждый день генерируется новый пазл — одно и то же начальное поле для каждого игрока в мире. Пазл сбрасывается в полночь UTC. Все, кто играет в ежедневный пазл в определённый день, начинают с идентичного расположения плиток, делая это честным соревнованием.",
    "t2k_htp_daily_p2": 'После завершения ежедневного пазла вы можете отправить свой результат в <a href="/other/2048/leaderboard">таблицу лидеров 2048</a>. Для отправки необходимо войти в систему.',
    "t2k_htp_desc": "Узнайте, как играть в 2048 — классический пазл со слиянием плиток. Поймите правила, управление, подсчёт очков и стратегию для достижения плитки 2048.",
    "t2k_htp_goal_h2": "Цель",
    "t2k_htp_goal_p1": "Сдвигайте плитки на сетке для слияния одинаковых чисел. Когда две плитки с одинаковым значением сталкиваются, они объединяются в одну плитку стоимостью вдвое больше — 2 и 2 становятся 4, два 4 становятся 8 и так далее. Цель — построить плитку, достигающую <strong>2048</strong>.",
    "t2k_htp_goal_p2": "Вы можете продолжать игру после достижения 2048, чтобы увеличить счёт. Игра заканчивается, когда не остаётся ходов — сетка заполнена и ни одна из соседних плиток не имеет одинакового значения.",
    "t2k_htp_intro": "2048 — это пазл с скользящими плитками на сетке 4×4. Объединяйте пронумерованные плитки, сдвигая их в четыре направления. После каждого хода появляется новая плитка. Достигните плитки 2048, чтобы выиграть — или продолжайте ради более высокого счёта.",
    "t2k_htp_scoring_h2": "Подсчёт очков",
    "t2k_htp_scoring_p1": "Каждое слияние добавляет значение новой объединённой плитки к вашему счёту. Слияние двух плиток 512 в плитку 1024 добавляет 1024 очка. Цепочка нескольких слияний за один ход суммирует все их вместе.",
    "t2k_htp_scoring_p2": 'В ежедневном пазле ваш итоговый счёт, количество ходов и время записываются и отправляются в <a href="/other/2048/leaderboard">таблицу лидеров</a>. Таблица ранжируется сначала по счёту (выше лучше), затем по времени (ниже лучше).',
    "t2k_htp_strategy_h2": "Базовая стратегия",
    "t2k_htp_strategy_p1": "<strong>Выберите угол и придерживайтесь его.</strong> Выберите один угол — обычно нижний — и держите там свою самую ценную плитку. Создавайте убывающую цепочку плиток вдоль края, отходящего от него, чтобы каждое слияние естественно переходило в следующее.",
    "t2k_htp_strategy_p2": "<strong>Никогда не сдвигайтесь от якорного угла.</strong> Избегайте ходов, которые отодвигают вашу самую большую плитку от её угла. Например, если ваша самая высокая плитка находится внизу слева, избегайте сдвига вверх, если только это не абсолютно необходимо. Потеря контроля над углом — вот как заканчивается большинство игр.",
    "t2k_htp_strategy_p3": "<strong>Держите верхний ряд заполненным.</strong> Как только у вас есть цепочка вдоль верхнего или нижнего края, старайтесь всегда держать этот ряд заполненным. Это заставляет новые плитки появляться в другом месте и сохраняет вашу цепочку.",
    "t2k_htp_strategy_p4": "<strong>Думайте наперёд.</strong> Перед каждым ходом подумайте, где может появиться новая плитка и нарушит ли она ваше расположение. Ходы, оставляющие поле в невосстановимом состоянии, обычно являются признаком того, что вы двигались не думая.",
    "t2k_htp_tiles_h2": "Значения плиток",
    "t2k_htp_tiles_p1": "Плитки всегда начинаются как 2 или 4 — есть 90% шанс на 2 и 10% на 4. Новые плитки появляются случайно в пустой ячейке после каждого хода. Последовательность значений удваивается с каждым слиянием: 2 → 4 → 8 → 16 → 32 → 64 → 128 → 256 → 512 → 1024 → 2048 и далее.",
    "t2k_htp_tiles_p2": "Только плитки с одинаковым значением могут объединяться, и каждая плитка может объединиться максимум один раз за ход.",
    "t2k_htp_title": "Как играть в 2048 | minesweeper.org",
    "t2k_keep_going": "Продолжить",
    "t2k_score": "Счёт:",
    "t2k_solved": "Вы достигли 2048!",
}

insert_t2k.LANGS["pt"] = {
    "t2k_game_over": "😥 Fim de jogo",
    "t2k_htp_back": "← Jogar o puzzle de hoje",
    "t2k_htp_controls_desktop_li1": "<strong>Teclas de seta</strong> ou <strong>W A S D</strong> — deslizar todas as peças nessa direção.",
    "t2k_htp_controls_desktop_li2": "Cada tecla pressionada é um movimento, mesmo que apenas uma peça se mova.",
    "t2k_htp_controls_footer": "Use o botão <strong>Novo jogo</strong> para reiniciar o tabuleiro e recomeçar a qualquer momento.",
    "t2k_htp_controls_h2": "Controlos",
    "t2k_htp_controls_mobile_li1": "<strong>Deslize</strong> para cima, baixo, esquerda ou direita para mover todas as peças nessa direção.",
    "t2k_htp_controls_mobile_li2": "Cada deslize é um movimento, mesmo que apenas uma peça se mova.",
    "t2k_htp_daily_h2": "Puzzle diário",
    "t2k_htp_daily_p1": "Cada dia é gerado um novo puzzle — o mesmo tabuleiro inicial para cada jogador no mundo. O puzzle é reiniciado à meia-noite UTC. Todos os que jogam o puzzle diário num determinado dia começam com uma disposição de peças idêntica, tornando-o numa competição justa.",
    "t2k_htp_daily_p2": 'Após completar o puzzle diário pode submeter a sua pontuação para o <a href="/other/2048/leaderboard">ranking 2048</a>. Precisa de ter sessão iniciada para submeter.',
    "t2k_htp_desc": "Aprenda a jogar 2048 — o clássico puzzle de fusão de peças. Compreenda as regras, controlos, pontuação e estratégia para alcançar a peça 2048.",
    "t2k_htp_goal_h2": "O objetivo",
    "t2k_htp_goal_p1": "Deslize peças na grelha para fundir números idênticos. Quando duas peças com o mesmo valor colidem, combinam-se numa única peça com o dobro do valor — um 2 e um 2 tornam-se 4, dois 4s tornam-se 8, e assim por diante. O objetivo é construir uma peça que alcance <strong>2048</strong>.",
    "t2k_htp_goal_p2": "Pode continuar a jogar após atingir 2048 para aumentar a pontuação. O jogo termina quando não restam movimentos — a grelha está cheia e nenhuma peça adjacente partilha o mesmo valor.",
    "t2k_htp_intro": "2048 é um puzzle de peças deslizantes jogado numa grelha 4×4. Combine peças numeradas iguais deslizando-as em quatro direções. A cada movimento aparece uma nova peça. Alcance a peça 2048 para ganhar — ou continue para uma pontuação mais alta.",
    "t2k_htp_scoring_h2": "Pontuação",
    "t2k_htp_scoring_p1": "Cada fusão adiciona o valor da nova peça combinada à sua pontuação. Fundir duas peças de 512 numa peça de 1024 adiciona 1024 pontos. Encadear várias fusões num movimento soma-as todas.",
    "t2k_htp_scoring_p2": 'No puzzle diário, a sua pontuação final, contagem de movimentos e tempo são registados e submetidos para o <a href="/other/2048/leaderboard">ranking</a>. O ranking ordena primeiro por pontuação (maior é melhor), depois por tempo (menor é melhor).',
    "t2k_htp_strategy_h2": "Estratégia básica",
    "t2k_htp_strategy_p1": "<strong>Escolha um canto e comprometa-se.</strong> Escolha um canto — normalmente um canto inferior — e mantenha a sua peça de maior valor lá. Construa uma cadeia decrescente de peças ao longo do bordo afastando-se dele para que cada fusão alimente naturalmente a seguinte.",
    "t2k_htp_strategy_p2": "<strong>Nunca deslize para longe do seu canto de ancoragem.</strong> Evite movimentos que afastem a sua maior peça do seu canto. Por exemplo, se a sua peça mais alta estiver no canto inferior esquerdo, evite deslizar para cima a não ser que seja absolutamente necessário. Perder o controlo do canto é como a maioria dos jogos termina.",
    "t2k_htp_strategy_p3": "<strong>Mantenha a linha do topo cheia.</strong> Quando tiver uma cadeia ao longo do bordo superior ou inferior, tente manter essa linha sempre cheia. Isto força as novas peças a aparecerem noutro lado e preserva a sua cadeia.",
    "t2k_htp_strategy_p4": "<strong>Pense com antecedência.</strong> Antes de cada movimento, considere onde a nova peça pode aparecer e se irá perturbar a sua disposição. Movimentos que deixam o tabuleiro num estado irrecuperável são geralmente um sinal de que se moveu sem pensar.",
    "t2k_htp_tiles_h2": "Valores das peças",
    "t2k_htp_tiles_p1": "As peças começam sempre como 2 ou 4 — há 90% de hipótese de ser 2 e 10% de ser 4. Novas peças aparecem aleatoriamente numa célula vazia após cada movimento. A sequência de valores duplica a cada fusão: 2 → 4 → 8 → 16 → 32 → 64 → 128 → 256 → 512 → 1024 → 2048 e além.",
    "t2k_htp_tiles_p2": "Apenas peças com o mesmo valor podem fundir-se, e cada peça só pode fundir-se uma vez por movimento.",
    "t2k_htp_title": "Como jogar 2048 | minesweeper.org",
    "t2k_keep_going": "Continuar",
    "t2k_score": "Pontuação:",
    "t2k_solved": "Chegou a 2048!",
}

insert_t2k.LANGS["it"] = {
    "t2k_game_over": "😥 Partita finita",
    "t2k_htp_back": "← Gioca il puzzle di oggi",
    "t2k_htp_controls_desktop_li1": "<strong>Tasti freccia</strong> o <strong>W A S D</strong> — scorri tutte le tessere in quella direzione.",
    "t2k_htp_controls_desktop_li2": "Ogni pressione di tasto è una mossa, anche se si sposta solo una tessera.",
    "t2k_htp_controls_footer": "Usa il pulsante <strong>Nuova partita</strong> per azzerare il tabellone e ricominciare in qualsiasi momento.",
    "t2k_htp_controls_h2": "Controlli",
    "t2k_htp_controls_mobile_li1": "<strong>Scorri</strong> su, giù, sinistra o destra per far scorrere tutte le tessere in quella direzione.",
    "t2k_htp_controls_mobile_li2": "Ogni scorrimento è una mossa, anche se si sposta solo una tessera.",
    "t2k_htp_daily_h2": "Puzzle quotidiano",
    "t2k_htp_daily_p1": "Ogni giorno viene generato un nuovo puzzle — lo stesso tabellone iniziale per ogni giocatore nel mondo. Il puzzle si azzera a mezzanotte UTC. Tutti coloro che giocano il puzzle quotidiano in un determinato giorno iniziano da una disposizione di tessere identica, rendendola una competizione equa.",
    "t2k_htp_daily_p2": 'Dopo aver completato il puzzle quotidiano puoi inviare il tuo punteggio alla <a href="/other/2048/leaderboard">classifica 2048</a>. Devi essere connesso per inviare.',
    "t2k_htp_desc": "Impara a giocare a 2048 — il classico puzzle di fusione di tessere. Comprendi le regole, i controlli, il punteggio e la strategia per raggiungere la tessera 2048.",
    "t2k_htp_goal_h2": "L'obiettivo",
    "t2k_htp_goal_p1": "Fai scorrere le tessere sulla griglia per unire numeri identici. Quando due tessere con lo stesso valore si scontrano, si combinano in un'unica tessera del doppio del valore — un 2 e un 2 diventano 4, due 4 diventano 8, e così via. L'obiettivo è costruire una tessera che raggiunga <strong>2048</strong>.",
    "t2k_htp_goal_p2": "Puoi continuare a giocare dopo aver raggiunto 2048 per aumentare il punteggio. Il gioco termina quando non restano mosse — la griglia è piena e nessuna tessera adiacente condivide lo stesso valore.",
    "t2k_htp_intro": "2048 è un puzzle a tessere scorrevoli giocato su una griglia 4×4. Combina tessere numerate uguali facendole scorrere in quattro direzioni. Ad ogni mossa appare una nuova tessera. Raggiungi la tessera 2048 per vincere — o continua per un punteggio più alto.",
    "t2k_htp_scoring_h2": "Punteggio",
    "t2k_htp_scoring_p1": "Ogni fusione aggiunge il valore della nuova tessera combinata al tuo punteggio. Fondere due tessere da 512 in una tessera da 1024 aggiunge 1024 punti. Concatenare più fusioni in una mossa le somma tutte.",
    "t2k_htp_scoring_p2": 'Nel puzzle quotidiano, il punteggio finale, il conteggio delle mosse e il tempo vengono registrati e inviati alla <a href="/other/2048/leaderboard">classifica</a>. La classifica ordina prima per punteggio (più alto è meglio), poi per tempo (più basso è meglio).',
    "t2k_htp_strategy_h2": "Strategia di base",
    "t2k_htp_strategy_p1": "<strong>Scegli un angolo e impegnati.</strong> Scegli un angolo — di solito un angolo inferiore — e tieni lì la tua tessera di valore più alto. Costruisci una catena discendente di tessere lungo il bordo che si allontana da esso, in modo che ogni fusione alimenti naturalmente la successiva.",
    "t2k_htp_strategy_p2": "<strong>Non scorrere mai lontano dall'angolo di ancoraggio.</strong> Evita mosse che allontanano la tua tessera più grande dal suo angolo. Ad esempio, se la tua tessera più alta è in basso a sinistra, evita di scorrere verso l'alto a meno che non sia assolutamente necessario. Perdere il controllo dell'angolo è come finiscono la maggior parte delle partite.",
    "t2k_htp_strategy_p3": "<strong>Tieni la riga superiore piena.</strong> Una volta che hai una catena lungo il bordo superiore o inferiore, cerca di tenerla sempre piena. Questo costringe le nuove tessere ad apparire altrove e preserva la tua catena.",
    "t2k_htp_strategy_p4": "<strong>Pensa in anticipo.</strong> Prima di ogni mossa, considera dove potrebbe apparire la nuova tessera e se disturberà il tuo layout. Le mosse che lasciano il tabellone in uno stato irrecuperabile sono di solito un segnale che ti sei mosso senza pensare.",
    "t2k_htp_tiles_h2": "Valori delle tessere",
    "t2k_htp_tiles_p1": "Le tessere iniziano sempre come 2 o 4 — c'è il 90% di probabilità di un 2 e il 10% di un 4. Nuove tessere appaiono casualmente in una cella vuota dopo ogni mossa. La sequenza dei valori raddoppia ad ogni fusione: 2 → 4 → 8 → 16 → 32 → 64 → 128 → 256 → 512 → 1024 → 2048 e oltre.",
    "t2k_htp_tiles_p2": "Solo le tessere con lo stesso valore possono fondersi, e ogni tessera può fondersi al massimo una volta per mossa.",
    "t2k_htp_title": "Come giocare a 2048 | minesweeper.org",
    "t2k_keep_going": "Continua",
    "t2k_score": "Punteggio:",
    "t2k_solved": "Hai raggiunto 2048!",
}

if __name__ == "__main__":
    for lang in ["uk", "ru", "pt", "it"]:
        insert_t2k.insert_lang(lang)
