# -*- coding: utf-8 -*-
"""quests batch 4: pl, tl, th, pgl"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_quests

insert_quests.LANGS["pl"] = {
    "quests_title": "Zadania",
    "quests_subtitle": "Wykonuj zadania, aby zdobywac nagrody. Postep jest zapisywany w przegladarce.",
    "quests_daily_title": "Codzienne zadanie",
    "quests_daily_note": "Jedno zadanie dziennie, zmienia sie co 24 godziny.",
    "quests_seasonal_title": "Zadania sezonowe",
    "quests_seasonal_note": "Wszystkie trzy sa aktywne przez caly miesiac. Postep przenosi sie z dnia na dzien.",
    "quests_rewards_title": "Nagrody",
    "quests_rewards_note": "Zdobadz dowolna nagrode, aby wylac reklamy na tym urzadzeniu.",
    "quests_reward_active": "Nagroda aktywna:",
    "quests_reward_active_desc": "Reklamy sa wylaczone — kontynuuj tak!",
    "quests_streak_reward_title": "20-dniowa seria codziennych zadan",
    "quests_streak_reward_desc": "Wykonuj codzienne zadanie przez 20 kolejnych dni.",
    "quests_season_reward_title": "10 codziennych zadan w tym sezonie",
    "quests_season_reward_desc": "Wykonaj codzienne zadanie w dowolnych 10 dniach tego miesiaca.",
    "quests_og_title": "Zadania Sapera",
    "quests_og_desc": "Wykonuj codzienne i miesieczne zadania Sapera. Zdobadz serie 20 dni lub ukonczaj 10 zadan w sezonie, aby wylac reklamy.",
    "quest_complete": "Ukonczone!",
    "quest_unlocked": "Odblokowane!",
    "quest_not_complete": "Jeszcze nie ukonczono",
    "quest_play": "Graj",
    "quest_days": "dni",
    "quest_daily_easy_win": "Wygraj Latwy Saper",
    "quest_daily_rush_5": "Wyczysc 5 min w trybie Rush",
    "quest_daily_tentaizu": "Ukonczaj codziennie zagadke Tentaizu",
    "quest_season_intermediate_win": "Wygraj Sredni Saper",
    "quest_season_rush_100": "Wyczysc 100 min w trybie Rush",
    "quest_season_tentaizu_10": "Ukonczaj 10 codziennych zagadek Tentaizu",
    "quest_reward_reason_streak": "20-dniowa seria codziennych zadan",
    "quest_reward_reason_season": "10 codziennych zadan w tym sezonie",
    "quest_toast_daily_easy": "Codzienne zadanie ukonczone! Latwy Saper wygrany.",
    "quest_toast_daily_rush": "Codzienne zadanie ukonczone! 5 min Rush wyczyszczone.",
    "quest_toast_daily_tentaizu": "Codzienne zadanie ukonczone! Zagadka Tentaizu ukonczona.",
    "quest_toast_reward_unlocked": "Nagroda odblokowana! Reklamy wylaczone — {reason}.",
    "quest_toast_season_intermediate": "Zadanie sezonowe ukonczone! Sredni Saper wygrany!",
    "quest_toast_season_rush": "Zadanie sezonowe ukonczone! 100 min Rush wyczyszczone!",
    "quest_toast_season_tentaizu": "Zadanie sezonowe ukonczone! 10 zagadek Tentaizu ukonczono!",
}

insert_quests.LANGS["tl"] = {
    "quests_title": "Mga Misyon",
    "quests_subtitle": "Kumpletuhin ang mga misyon para kumita ng mga gantimpala. Naitatago ang progreso sa iyong browser.",
    "quests_daily_title": "Araw-araw na Misyon",
    "quests_daily_note": "Isang misyon bawat araw, nagpapalitan bawat 24 na oras.",
    "quests_seasonal_title": "Mga Misyon ng Panahon",
    "quests_seasonal_note": "Lahat ng tatlo ay aktibo sa buong buwan. Ang progreso ay naihahatid araw-araw.",
    "quests_rewards_title": "Mga Gantimpala",
    "quests_rewards_note": "Kumita ng alinmang gantimpala upang i-disable ang mga ad sa device na ito.",
    "quests_reward_active": "Gantimpala aktibo:",
    "quests_reward_active_desc": "Ang mga ad ay naka-disable — ipagpatuloy!",
    "quests_streak_reward_title": "20-Araw na Streak ng Araw-araw na Misyon",
    "quests_streak_reward_desc": "Kumpletuhin ang iyong araw-araw na misyon sa loob ng 20 magkakasunod na araw.",
    "quests_season_reward_title": "10 Araw-araw na Misyon Ngayong Panahon",
    "quests_season_reward_desc": "Kumpletuhin ang iyong araw-araw na misyon sa anumang 10 araw ngayong buwan.",
    "quests_og_title": "Mga Misyon ng Minesweeper",
    "quests_og_desc": "Kumpletuhin ang araw-araw at buwanang mga misyon ng Minesweeper. Kumita ng 20-araw na streak o tapusin ang 10 misyon sa isang panahon upang i-disable ang mga ad.",
    "quest_complete": "Kumpleto!",
    "quest_unlocked": "Na-unlock!",
    "quest_not_complete": "Hindi pa kumpleto",
    "quest_play": "Laruin",
    "quest_days": "araw",
    "quest_daily_easy_win": "Manalo sa Madaling Minesweeper",
    "quest_daily_rush_5": "Linisin ang 5 mina sa Rush mode",
    "quest_daily_tentaizu": "Kumpletuhin ang araw-araw na puzzle ng Tentaizu",
    "quest_season_intermediate_win": "Manalo sa Intermediate na Minesweeper",
    "quest_season_rush_100": "Linisin ang 100 mina sa Rush mode",
    "quest_season_tentaizu_10": "Kumpletuhin ang 10 araw-araw na puzzle ng Tentaizu",
    "quest_reward_reason_streak": "20-araw na streak ng araw-araw na misyon",
    "quest_reward_reason_season": "10 araw-araw na misyon ngayong panahon",
    "quest_toast_daily_easy": "Araw-araw na misyon kumpleto! Madaling Minesweeper nanalo.",
    "quest_toast_daily_rush": "Araw-araw na misyon kumpleto! 5 Rush mina nalinis.",
    "quest_toast_daily_tentaizu": "Araw-araw na misyon kumpleto! Puzzle ng Tentaizu nakumpleto.",
    "quest_toast_reward_unlocked": "Gantimpala na-unlock! Mga ad na-disable — {reason}.",
    "quest_toast_season_intermediate": "Misyon ng panahon kumpleto! Intermediate na Minesweeper nanalo!",
    "quest_toast_season_rush": "Misyon ng panahon kumpleto! 100 Rush mina nalinis!",
    "quest_toast_season_tentaizu": "Misyon ng panahon kumpleto! 10 puzzle ng Tentaizu nakumpleto!",
}

insert_quests.LANGS["th"] = {
    "quests_title": "ภารกิจ",
    "quests_subtitle": "ทำภารกิจให้สำเร็จเพื่อรับรางวัล ความคืบหน้าจะถูกบันทึกในเบราว์เซอร์ของคุณ",
    "quests_daily_title": "ภารกิจประจำวัน",
    "quests_daily_note": "ภารกิจหนึ่งงานต่อวัน สลับทุก 24 ชั่วโมง",
    "quests_seasonal_title": "ภารกิจตามฤดูกาล",
    "quests_seasonal_note": "ทั้งสามภารกิจเปิดใช้งานตลอดเดือน ความคืบหน้าจะสะสมต่อเนื่องทุกวัน",
    "quests_rewards_title": "รางวัล",
    "quests_rewards_note": "รับรางวัลใดก็ได้เพื่อปิดโฆษณาบนอุปกรณ์นี้",
    "quests_reward_active": "รางวัลที่ใช้งานอยู่:",
    "quests_reward_active_desc": "โฆษณาถูกปิดอยู่ — ทำต่อไป!",
    "quests_streak_reward_title": "ภารกิจประจำวันติดต่อกัน 20 วัน",
    "quests_streak_reward_desc": "ทำภารกิจประจำวันให้สำเร็จ 20 วันติดต่อกัน",
    "quests_season_reward_title": "ภารกิจประจำวัน 10 ครั้งในฤดูกาลนี้",
    "quests_season_reward_desc": "ทำภารกิจประจำวันให้สำเร็จในวันใดก็ได้ 10 วันในเดือนนี้",
    "quests_og_title": "ภารกิจ Minesweeper",
    "quests_og_desc": "ทำภารกิจรายวันและรายเดือนของ Minesweeper ให้สำเร็จ สะสม 20 วันติดต่อกัน หรือทำให้เสร็จ 10 ภารกิจในฤดูกาลเพื่อปิดโฆษณา",
    "quest_complete": "เสร็จสิ้น!",
    "quest_unlocked": "ปลดล็อคแล้ว!",
    "quest_not_complete": "ยังไม่เสร็จสิ้น",
    "quest_play": "เล่น",
    "quest_days": "วัน",
    "quest_daily_easy_win": "ชนะ Minesweeper ระดับง่าย",
    "quest_daily_rush_5": "กำจัดระเบิด 5 ลูกในโหมด Rush",
    "quest_daily_tentaizu": "แก้ปริศนา Tentaizu ประจำวัน",
    "quest_season_intermediate_win": "ชนะ Minesweeper ระดับกลาง",
    "quest_season_rush_100": "กำจัดระเบิด 100 ลูกในโหมด Rush",
    "quest_season_tentaizu_10": "แก้ปริศนา Tentaizu ประจำวัน 10 ครั้ง",
    "quest_reward_reason_streak": "ภารกิจประจำวันติดต่อกัน 20 วัน",
    "quest_reward_reason_season": "ภารกิจประจำวัน 10 ครั้งในฤดูกาลนี้",
    "quest_toast_daily_easy": "ภารกิจประจำวันสำเร็จ! ชนะ Minesweeper ระดับง่ายแล้ว",
    "quest_toast_daily_rush": "ภารกิจประจำวันสำเร็จ! กำจัดระเบิด Rush 5 ลูกแล้ว",
    "quest_toast_daily_tentaizu": "ภารกิจประจำวันสำเร็จ! แก้ปริศนา Tentaizu แล้ว",
    "quest_toast_reward_unlocked": "ปลดล็อครางวัลแล้ว! ปิดโฆษณาแล้ว — {reason}",
    "quest_toast_season_intermediate": "ภารกิจตามฤดูกาลสำเร็จ! ชนะ Minesweeper ระดับกลางแล้ว!",
    "quest_toast_season_rush": "ภารกิจตามฤดูกาลสำเร็จ! กำจัดระเบิด Rush 100 ลูกแล้ว!",
    "quest_toast_season_tentaizu": "ภารกิจตามฤดูกาลสำเร็จ! แก้ปริศนา Tentaizu 10 ครั้งแล้ว!",
}

insert_quests.LANGS["pgl"] = {
    "quests_title": "Estquay",
    "quests_subtitle": "Ompleteay estquay otay earnyay ewardsray. Ogresspray isway avedsay inyay ouryay owserbray.",
    "quests_daily_title": "Ailyday Estquay",
    "quests_daily_note": "Oneway estquay erpay ayday, otatesray everyyway 24 ourshay.",
    "quests_seasonal_title": "Easonalsay Estquay",
    "quests_seasonal_note": "Allway eethray arehay activeway orfay ethay olewwhay onthmay. Ogresspray arriesway overway ayday otay ayday.",
    "quests_rewards_title": "Ewardsray",
    "quests_rewards_note": "Earnyay eitherway ewardray otay isableday adsway onway isthay eviceday.",
    "quests_reward_active": "Ewardray activeway:",
    "quests_reward_active_desc": "Adsway arehay isableddlay — eepkay itway upway!",
    "quests_streak_reward_title": "20-Ayday Ailyday Estquay Eatrekstray",
    "quests_streak_reward_desc": "Ompleteay ouryay ailyday estquay onway 20 onsecutivecay aysday.",
    "quests_season_reward_title": "10 Ailyday Estquay Isthay Easonay",
    "quests_season_reward_desc": "Ompleteay ouryay ailyday estquay onway anyway 10 aysday isthay onthmay.",
    "quests_og_title": "Inesweepermay Estquay",
    "quests_og_desc": "Ompleteay ailyday andway onthlymay Inesweepermay estquay. Earnyay away 20-ayday eatrekstray orway inishfay 10 estquay inyay away easonway otay isableday adsway.",
    "quest_complete": "Ompleteday!",
    "quest_unlocked": "Unlockedway!",
    "quest_not_complete": "Otnay etyay ompletedcay",
    "quest_play": "Ayplay",
    "quest_days": "aysday",
    "quest_daily_easy_win": "Inway Easyw Inesweepermay",
    "quest_daily_rush_5": "Learcay 5 inesmay onway Ushray odemay",
    "quest_daily_tentaizu": "Learcay ethay ailyday Entaizutay uzzlepay",
    "quest_season_intermediate_win": "Inway Intermediateway Inesweepermay",
    "quest_season_rush_100": "Learcay 100 inesmay onway Ushray odemay",
    "quest_season_tentaizu_10": "Learcay 10 ailyday Entaizutay uzzlespay",
    "quest_reward_reason_streak": "20-ayday ailyday estquay eatrekstray",
    "quest_reward_reason_season": "10 ailyday estquay isthay easonway",
    "quest_toast_daily_easy": "Ailyday estquay ompleteday! Easyway Inesweepermay onway.",
    "quest_toast_daily_rush": "Ailyday estquay ompleteday! 5 Ushray inesmay learedcay.",
    "quest_toast_daily_tentaizu": "Ailyday estquay ompleteday! Entaizutay uzzlepay learedcay.",
    "quest_toast_reward_unlocked": "Ewardray unlockedway! Adsway isableddlay — {reason}.",
    "quest_toast_season_intermediate": "Easonalsay estquay ompleteday! Intermediateway Inesweepermay onway!",
    "quest_toast_season_rush": "Easonalsay estquay ompleteday! 100 Ushray inesmay learedcay!",
    "quest_toast_season_tentaizu": "Easonalsay estquay ompleteday! 10 Entaizutay uzzlespay learedcay!",
}

if __name__ == "__main__":
    for lang in ["pl", "tl", "th", "pgl"]:
        insert_quests.insert_lang(lang)
