# -*- coding: utf-8 -*-
"""15-Puzzle fp_* batch 4: pl, tl, th, pgl"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_fp

insert_fp.LANGS["pl"] = {
    "fp_col_moves": "Ruchy",
    "fp_gen_copy": "Kopiuj",
    "fp_gen_delete": "Usuń",
    "fp_gen_file_label": "JPG lub PNG, maks. 2 MB",
    "fp_gen_limit_post": "-puzzli. Usuń zapisaną łamiġłówkę, aby zwolnić miejsce.",
    "fp_gen_limit_pre": "Osiągnięto\xa0limit\xa0",
    "fp_gen_limit_reached": "Osiągnięto limit łamiġłówek",
    "fp_gen_mode_h2": "2. Wybierz tryb zdjęcia",
    "fp_gen_mode_hint": "<strong>Kafelki:</strong> zdjęcie jest podzielone na kafelki i wymie szane razem z nimi.<br><strong>Odkryj po wygranej:</strong> kafelki pokazują liczby; rozwiązanie ujawnia zdjęcie pod spodem.",
    "fp_gen_mode_reveal": "Odkryj po wygranej",
    "fp_gen_mode_tiles": "Kafelki",
    "fp_gen_no_puzzles": "Brak zapisanych łamiġłówek. Utwórz jedną powyżej!",
    "fp_gen_refresh": "Odśwież",
    "fp_gen_refresh_hint": "aby zobaczyć ją na liście zapisanych poniżej.",
    "fp_gen_save_btn": "Zapisz &amp; uzyskaj link",
    "fp_gen_saved_title": "Łamiġłówka zapisana! Udostępnij ten link:",
    "fp_gen_scramble": "↺ Przetasuj",
    "fp_gen_signin_btn": "Zaloguj się",
    "fp_gen_signin_msg": 'Musisz <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">Zalogować się</a>, aby przesyłać zdjęcia i zapisywać łamiġłówki.',
    "fp_gen_title_label": "Tytuł łamiġłówki (opcjonalnie)",
    "fp_gen_title_ph": "Moja niesamowita łamiġłówka",
    "fp_gen_untitled": "Łamiġłówka bez tytułu",
    "fp_gen_upload_h2": "1. Prześlij zdjęcie",
    "fp_gen_your_puzzles": "Twoje zapisane łamiġłówki",
    "fp_htp_back": "← Zagraj w dzisiejszą łamiġłówkę",
    "fp_htp_controls_desktop_li1": "<strong>Kliknij kafelek</strong> sąsiadujący z pustym miejscem, aby go przesunąć.",
    "fp_htp_controls_desktop_li2": "<strong>Kliknij kafelek dalej</strong> w tym samym wierszu lub kolumnie, a cała linia kafelków między nim a pustym miejscem przesunie się razem w jednym ruchu — dokładnie jak w prawdziwej fizycznej układance.",
    "fp_htp_controls_desktop_li3": "<strong>Klawisze strzałek</strong> przesuwają kafelek do pustego miejsca z odpowiedniego kierunku.",
    "fp_htp_controls_footer": "Użyj przycisku <strong>Nowa gra</strong>, aby zresetować planszę i zacząć od nowa w dowolnym momencie.",
    "fp_htp_controls_h2": "Sterowanie",
    "fp_htp_controls_mobile_li1": "<strong>Dotknąć kafelka</strong> sąsiadującego z pustym miejscem, aby go przesunąć.",
    "fp_htp_controls_mobile_li2": "<strong>Dotknąć kafelka dalej</strong> w tym samym wierszu lub kolumnie, a cały wiersz lub kolumna przesunie się w jednym ruchu.",
    "fp_htp_daily_h2": "Dzienna łamiġłówka",
    "fp_htp_daily_p1": "Nowa łamiġłówka jest generowana każdego dnia o północy UTC — ta sama przemie szana plansza dla każdego gracza na świecie. Rozwiąż ją, prześlij swój wynik i sprawdź, jak wypadasz w rankingu.",
    "fp_htp_daily_p2": 'Możesz też stworzyć własną łamiġłówkę fotograficzną za pomocą <a href="/other/15puzzle/generator">Generatora łamiġłówek</a> — prześlij dowolny obraz, wybierz tryb i udostępnij link każdemu.',
    "fp_htp_desc": "Dowiedz się, jak grać w Układankę 15 — klasyczną grę z przesuwan ymi kafelkami. Poznaj zasady, sterowanie, tryby zdjęciowe i strategię szybkiego rozwiązywania.",
    "fp_htp_ex_midgame": "W połowie gry. Górne wiersze zajmują swoje miejsca. Skup się na układaniu jednego wiersza na raz, od góry do dołu.",
    "fp_htp_ex_nearlydone": "Prawie gotowe. Tylko dolne wiersze pozostają pomie szane. Na tym etapie potrzebne są drobne korekty — unikaj cofania postępu w już rozwiązanych wierszach.",
    "fp_htp_ex_scrambled": "Pozycja startowa. Kafelki są losowo ułożone, ale zawsze możliwe do rozwiązania. Puste miejsce (ciemny kwadrat) może znajdować się w dowolnym miejscu na planszy.",
    "fp_htp_ex_solved": "Rozwiązane! Wszystkie kafelki są w kolejności, a pełny obraz zostaje ujawniony. Twój czas i liczba ruchów są zapisywane w rankingu.",
    "fp_htp_example_h2": "Przykład: rozwiązywanie krok po kroku",
    "fp_htp_example_intro": "Poniższe zrzuty ekranu pokazują rozwiązywanie łamiġłówki fotograficznej z Lady Di's Mines jako obrazem. Każdy kafelek niesie numer i fragment obrazu — możesz więc używać go jako wizualnego przewodnika podczas rozwiązywania.",
    "fp_htp_goal_h2": "Cel",
    "fp_htp_goal_p1": "Ułóż wszystkie 15 kafelków w kolejności rosnącej — od lewej do prawej, od góry do dołu — z pustym miejscem w prawym dolnym rogu. Rozwiązana pozycja wygląda tak: 1, 2, 3, 4 w górnym wierszu, następnie 5, 6, 7, 8, potem 9, 10, 11, 12, a na końcu 13, 14, 15 i puste pole.",
    "fp_htp_goal_p2": "Twój wynik to kombinacja liczby użytych ruchów i czasu rozwiązania. Mniej ruchów i krótszy czas oznaczają lepszą pozycję w rankingu.",
    "fp_htp_intro": "Układanka 15 to klasyczna gra z przesuwan ymi kafelkami rozgrywana na siatce 4×4. Piętnaście ponumerowanych kafelków wypełnia planszę, zostawiając jedno puste miejsce. Przesuwaj kafelki na puste miejsce, aby je przestawiać, aż każdy kafelek będzie w kolejności od 1 do 15.",
    "fp_htp_photo_h2": "Tryby łamiġłówki fotograficznej",
    "fp_htp_photo_p1": "Dzienna łamiġłówka i niestandardowe łamiġłówki fotograficzne oferują dwa różne tryby wizualne:",
    "fp_htp_photo_reveal": "<strong>Odkryj po wygranej</strong> — kafelki pokazują tylko liczby podczas rozwiązywania. Gdy ułożysz ostatni kafelek poprawnie, pełne zdjęcie zostaje ujawnione pod spodem. Obraz jest nagrodą za ukończenie, nie podpowiedzią.",
    "fp_htp_photo_tiles": "<strong>Tryb kafelków</strong> — każdy kafelek pokazuje swój wycinek zdjęcia. Obraz daje ci wizualny kontekst do kierowania rozwiązywaniem — użyj obrazu jako drugiej warstwy informacji ponad liczbami.",
    "fp_htp_strategy_h2": "Strategia",
    "fp_htp_strategy_p1": "<strong>Rozwiązuj wiersz po wierszu od góry.</strong> Wiersze 1 i 2 można każdy ukończyć i zablokować na miejscu bez zakłócania czegokolwiek powyżej. Ostatnie dwa wiersze (kafelki 9–15) są rozwiązywane razem przy użyciu techniki rotacji.",
    "fp_htp_strategy_p2": "<strong>Układaj kafelek 1 i kafelek 2 razem.</strong> Próba samodzielnego przesunięcia kafelka 1 na miejsce często przesuwa kafelek 2. Zamiast tego manewruj oboma kafelkami 1 i 2 jednocześnie na właściwe pozycje kolumny, a następnie obróć je razem do górnego wiersza.",
    "fp_htp_strategy_p3": "<strong>Używaj przesunięć wielu kafelków.</strong> Kliknięcie lub dotknięcie kafelka, który nie sąsiaduje bezpośrednio z pustym miejscem, przesuwa cały pośredni wiersz lub kolumnę. Jest to szybsze niż przesuwanie kafelków jeden po jednym i jest kluczowe dla efektywnego rozwiązywania.",
    "fp_htp_strategy_p4": "<strong>Licz swoje ruchy.</strong> Każde przesunięcie liczy się jako jeden ruch, łącznie z przesunięciami wielu kafelków. Jedno dobrze zaplanowane przesunięcie wielu kafelków może zaoszczędzić kilka ruchów pojedynczych — planuj z wyprzedzeniem, aby zminimalizować swój wynik.",
    "fp_htp_title": "Jak grać w Układankę 15 | minesweeper.org",
    "fp_moves": "Ruchy:",
    "fp_name_label": "Nazwa",
    "fp_new_game": "↺ Nowa gra",
    "fp_photo_puzzle": "Łamiġłówka fotograficzna",
    "fp_same_for_all": "Ta sama łamiġłówka dla wszystkich · Reset o północy UTC",
    "fp_solved": "🎉 Rozwiązano!",
    "fp_submit_score": "Prześlij swój wynik",
    "fp_time": "Czas:",
    "fp_today_heading": "Dziś — ",
}

insert_fp.LANGS["tl"] = {
    "fp_col_moves": "Mga Galaw",
    "fp_gen_copy": "Kopyahin",
    "fp_gen_delete": "Tanggalin",
    "fp_gen_file_label": "JPG o PNG, max 2MB",
    "fp_gen_limit_post": "-puzzle na limitasyon. Magtanggal ng naka-save na puzzle para gumawa ng espasyo.",
    "fp_gen_limit_pre": "Naabot mo na ang iyong\xa0",
    "fp_gen_limit_reached": "Naabot ang limitasyon ng puzzle",
    "fp_gen_mode_h2": "2. Pumili ng Photo Mode",
    "fp_gen_mode_hint": "<strong>Mga Tile:</strong> ang larawan ay hiniwa sa mga tile at pinagulo kasama ang mga ito.<br><strong>Ihayag sa panalo:</strong> nagpapakita ng mga numero ang mga tile; ang paglutas ay nagbubunyag ng larawan sa ilalim.",
    "fp_gen_mode_reveal": "Ihayag sa panalo",
    "fp_gen_mode_tiles": "Mga Tile",
    "fp_gen_no_puzzles": "Wala pang naka-save na puzzle. Gumawa ng isa sa itaas!",
    "fp_gen_refresh": "I-refresh",
    "fp_gen_refresh_hint": "para makita ito sa iyong naka-save na listahan sa ibaba.",
    "fp_gen_save_btn": "I-save &amp; Kumuha ng Link",
    "fp_gen_saved_title": "Nai-save ang puzzle! Ibahagi ang link na ito:",
    "fp_gen_scramble": "↺ Guluhin",
    "fp_gen_signin_btn": "Mag-sign in",
    "fp_gen_signin_msg": 'Kailangan mong <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">Mag-sign In</a> para mag-upload ng mga larawan at mag-save ng mga puzzle.',
    "fp_gen_title_label": "Pamagat ng puzzle (opsyonal)",
    "fp_gen_title_ph": "Ang aking kamangha-manghang puzzle",
    "fp_gen_untitled": "Puzzle na walang pamagat",
    "fp_gen_upload_h2": "1. Mag-upload ng Larawan",
    "fp_gen_your_puzzles": "Iyong Mga Naka-save na Puzzle",
    "fp_htp_back": "← Laruin ang Puzzle Ngayon",
    "fp_htp_controls_desktop_li1": "<strong>I-click ang isang tile</strong> na katabi ng walang laman na espasyo para i-slide ito papasok.",
    "fp_htp_controls_desktop_li2": "<strong>I-click ang isang tile na mas malayo</strong> sa parehong row o column at ang buong linya ng mga tile sa pagitan nito at ng walang laman na espasyo ay magsa-slide nang magkasama sa isang galaw — tulad ng isang tunay na pisikal na puzzle.",
    "fp_htp_controls_desktop_li3": "<strong>Mga arrow key</strong> ay nagpapalipat ng tile papasok sa walang laman na espasyo mula sa kaukulang direksyon.",
    "fp_htp_controls_footer": "Gamitin ang button na <strong>Bagong Laro</strong> para i-reset ang board at magsimulang muli anumang oras.",
    "fp_htp_controls_h2": "Mga Kontrol",
    "fp_htp_controls_mobile_li1": "<strong>I-tap ang isang tile</strong> na katabi ng walang laman na espasyo para i-slide ito papasok.",
    "fp_htp_controls_mobile_li2": "<strong>I-tap ang isang tile na mas malayo</strong> sa parehong row o column at ang buong row o column ay magsa-slide sa isang galaw.",
    "fp_htp_daily_h2": "Araw-araw na Puzzle",
    "fp_htp_daily_p1": "Isang bagong puzzle ang ginagawa bawat araw sa hatinggabi UTC — ang parehong halo-halong board para sa bawat manlalaro sa buong mundo. Lutasin ito, isumite ang iyong puntos, at tingnan kung paano ka nag-rank sa leaderboard.",
    "fp_htp_daily_p2": 'Maaari ka ring lumikha ng sariling photo puzzle gamit ang <a href="/other/15puzzle/generator">Puzzle Generator</a> — mag-upload ng anumang larawan, piliin ang iyong mode, at ibahagi ang link sa sinuman.',
    "fp_htp_desc": "Alamin kung paano laruin ang 15-Puzzle — ang klasikong laro ng mga nahuhulog na tile. Unawain ang mga patakaran, kontrol, mga photo mode, at estratehiya para malutas ito nang mabilis.",
    "fp_htp_ex_midgame": "Sa kalagitnaan. Ang mga nangungunang row ay nahuhulog sa lugar. Mag-focus sa pagkumpleto ng isang row sa isang pagkakataon mula sa itaas pababa.",
    "fp_htp_ex_nearlydone": "Halos tapos na. Ang mga row sa ibaba lamang ang nananatiling magulo. Sa yugtong ito kailangan ng maliliit na pagsasaayos — iwasang i-undo ang pag-unlad sa mga row na nalutas na.",
    "fp_htp_ex_scrambled": "Ang panimulang posisyon. Ang mga tile ay random ngunit laging nararalutas. Ang walang laman na espasyo (madilim na parisukat) ay maaaring nasa kahit saan sa board.",
    "fp_htp_ex_solved": "Nalutas! Lahat ng tile ay nasa tamang ayos at ang buong larawan ay nahayag. Ang iyong oras at bilang ng galaw ay naitala para sa leaderboard.",
    "fp_htp_example_h2": "Halimbawa: Paglutas Hakbang-hakbang",
    "fp_htp_example_intro": "Ang mga screenshot sa ibaba ay nagpapakita ng isang photo puzzle na niresolba gamit ang Lady Di's Mines bilang larawan. Bawat tile ay may numero at isang fragment ng larawan — kaya maaari mong gamitin ang larawan bilang visual na gabay habang niresolba mo ito.",
    "fp_htp_goal_h2": "Ang Layunin",
    "fp_htp_goal_p1": "Ayusin ang lahat ng 15 tile sa pataas na pagkakasunod — mula kaliwa hanggang kanan, mula itaas hanggang ibaba — na may walang laman na espasyo sa kanang sulok sa ibaba. Ang nalutas na posisyon ay ganito: 1, 2, 3, 4 sa nangungunang row, pagkatapos 5, 6, 7, 8, pagkatapos 9, 10, 11, 12, pagkatapos 13, 14, 15 at ang blangko.",
    "fp_htp_goal_p2": "Ang iyong puntos ay kumbinasyon ng bilang ng mga galaw na ginamit mo at kung gaano kabilis mo nalutas ito. Mas kaunting galaw at mas kaunting oras ay nangangahulugang mas magandang ranggo sa leaderboard.",
    "fp_htp_intro": "Ang 15-Puzzle ay isang klasikong laro ng mga nahuhulog na tile na nilalaro sa isang 4\xd74 na grid. Labinlimang numerong tile ang pumupuno sa board, na nag-iiwan ng isang walang laman na espasyo. I-slide ang mga tile sa walang laman na espasyo para muling ayusin ang mga ito hanggang sa bawat tile ay nasa ayos mula 1 hanggang 15.",
    "fp_htp_photo_h2": "Mga Photo Puzzle Mode",
    "fp_htp_photo_p1": "Ang araw-araw na puzzle at mga custom na photo puzzle ay nag-aalok ng dalawang iba't ibang visual na mode:",
    "fp_htp_photo_reveal": "<strong>Ihayag sa panalo</strong> — nagpapakita lamang ng mga numero ang mga tile habang niresolba mo ito. Kapag nailagay mo nang tama ang huling tile, ang buong larawan ay nahayag sa ilalim. Ang larawan ay isang gantimpala para sa pagtatapos, hindi isang pahiwatig.",
    "fp_htp_photo_tiles": "<strong>Tiles mode</strong> — bawat tile ay nagpapakita ng hiwa nito ng larawan. Ang larawan ay nagbibigay sa iyo ng visual na konteksto para gabayan ang iyong paglulutas — gamitin ang larawan bilang pangalawang layer ng impormasyon sa ibabaw ng mga numero.",
    "fp_htp_strategy_h2": "Estratehiya",
    "fp_htp_strategy_p1": "<strong>Lutasin ang row sa bawat row mula sa itaas.</strong> Ang mga row 1 at 2 ay maaaring bawat isa na makumpleto at ma-lock sa lugar nang hindi naaabala ang anumang nasa itaas. Ang huling dalawang row (mga tile 9–15) ay nalulutas nang magkasama gamit ang isang rotation technique.",
    "fp_htp_strategy_p2": "<strong>Ilagay ang tile 1 at tile 2 nang magkasama.</strong> Ang pagsubok na i-slide ang tile 1 sa posisyon nang mag-isa ay madalas na nagpapalipat ng tile 2. Sa halip, i-manoeuvre ang parehong tile 1 at tile 2 sa kanilang tamang posisyon ng column nang sabay-sabay, pagkatapos i-rotate ang mga ito papasok sa nangungunang row sa parehong oras.",
    "fp_htp_strategy_p3": "<strong>Gumamit ng multi-tile slides.</strong> Ang pag-click o pag-tap ng isang tile na hindi direktang katabi ng walang laman na espasyo ay nagsa-slide ng buong row o column na nasa pagitan. Ito ay mas mabilis kaysa sa paglipat ng mga tile isa-isa at mahalaga para sa mahusay na paglulutas.",
    "fp_htp_strategy_p4": "<strong>Bilangin ang iyong mga galaw.</strong> Bawat slide ay binibilang bilang isang galaw, kasama ang mga multi-tile slide. Ang isang mabuting planong multi-tile slide ay maaaring makatipid ng ilang single-tile na galaw — mag-plano nang maaga para mabawasan ang iyong bilang.",
    "fp_htp_title": "Paano Laruin ang 15-Puzzle | minesweeper.org",
    "fp_moves": "Mga Galaw:",
    "fp_name_label": "Pangalan",
    "fp_new_game": "↺ Bagong Laro",
    "fp_photo_puzzle": "Photo puzzle",
    "fp_same_for_all": "Parehong puzzle para sa lahat \xb7 Na-reset sa hatinggabi UTC",
    "fp_solved": "🎉 Nalutas!",
    "fp_submit_score": "Isumite ang iyong puntos",
    "fp_time": "Oras:",
    "fp_today_heading": "Ngayon — ",
}

insert_fp.LANGS["th"] = {
    "fp_col_moves": "การเดิน",
    "fp_gen_copy": "คัดลอก",
    "fp_gen_delete": "ลบ",
    "fp_gen_file_label": "JPG หรือ PNG ขนาดสูงสุด 2MB",
    "fp_gen_limit_post": "-ปริศนา โปรดลบปริศนาที่บันทึกไว้เพื่อเพิ่มพื้นที่",
    "fp_gen_limit_pre": "คุณถึงขีดจำกัด\xa0",
    "fp_gen_limit_reached": "ถึงขีดจำกัดของปริศนาแล้ว",
    "fp_gen_mode_h2": "2. เลือกโหมดรูปภาพ",
    "fp_gen_mode_hint": "<strong>กระเบื้อง:</strong> รูปภาพถูกตัดแบ่งไปยังกระเบื้องและสับเปลี่ยนพร้อมกับกระเบื้อง<br><strong>เปิดเผยเมื่อชนะ:</strong> กระเบื้องแสดงตัวเลข การแก้ปริศนาจะเปิดเผยรูปภาพด้านล่าง",
    "fp_gen_mode_reveal": "เปิดเผยเมื่อชนะ",
    "fp_gen_mode_tiles": "กระเบื้อง",
    "fp_gen_no_puzzles": "ยังไม่มีปริศนาที่บันทึกไว้ สร้างอันหนึ่งด้านบน!",
    "fp_gen_refresh": "รีเฟรช",
    "fp_gen_refresh_hint": "เพื่อดูในรายการที่บันทึกด้านล่าง",
    "fp_gen_save_btn": "บันทึก &amp; รับลิงก์",
    "fp_gen_saved_title": "บันทึกปริศนาแล้ว! แชร์ลิงก์นี้:",
    "fp_gen_scramble": "↺ สับเปลี่ยน",
    "fp_gen_signin_btn": "เข้าสู่ระบบ",
    "fp_gen_signin_msg": 'คุณต้อง <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">เข้าสู่ระบบ</a> เพื่ออัปโหลดรูปภาพและบันทึกปริศนา',
    "fp_gen_title_label": "ชื่อปริศนา (ไม่บังคับ)",
    "fp_gen_title_ph": "ปริศนาสุดเจ๋งของฉัน",
    "fp_gen_untitled": "ปริศนาไม่มีชื่อ",
    "fp_gen_upload_h2": "1. อัปโหลดรูปภาพ",
    "fp_gen_your_puzzles": "ปริศนาที่บันทึกของคุณ",
    "fp_htp_back": "← เล่นปริศนาวันนี้",
    "fp_htp_controls_desktop_li1": "<strong>คลิกกระเบื้อง</strong> ที่อยู่ติดกับช่องว่างเพื่อเลื่อนเข้าไป",
    "fp_htp_controls_desktop_li2": "<strong>คลิกกระเบื้องที่อยู่ไกลออกไป</strong> ในแถวหรือคอลัมน์เดียวกัน และกระเบื้องทั้งแถวระหว่างกระเบื้องนั้นกับช่องว่างจะเลื่อนพร้อมกันในการเดินเดียว เหมือนปริศนาจริงๆ",
    "fp_htp_controls_desktop_li3": "<strong>ปุ่มลูกศร</strong> เลื่อนกระเบื้องเข้าสู่ช่องว่างจากทิศทางที่สอดคล้องกัน",
    "fp_htp_controls_footer": "ใช้ปุ่ม <strong>เกมใหม่</strong> เพื่อรีเซ็ตกระดานและเริ่มต้นใหม่ได้ตลอดเวลา",
    "fp_htp_controls_h2": "การควบคุม",
    "fp_htp_controls_mobile_li1": "<strong>แตะกระเบื้อง</strong> ที่อยู่ติดกับช่องว่างเพื่อเลื่อนเข้าไป",
    "fp_htp_controls_mobile_li2": "<strong>แตะกระเบื้องที่อยู่ไกลออกไป</strong> ในแถวหรือคอลัมน์เดียวกัน และทั้งแถวหรือคอลัมน์จะเลื่อนในการเดินเดียว",
    "fp_htp_daily_h2": "ปริศนาประจำวัน",
    "fp_htp_daily_p1": "ปริศนาใหม่ถูกสร้างทุกวันเที่ยงคืน UTC — กระดานสับเปลี่ยนเดิมสำหรับผู้เล่นทุกคนทั่วโลก แก้ปริศนา ส่งคะแนนของคุณ และดูอันดับของคุณในลีดเดอร์บอร์ด",
    "fp_htp_daily_p2": 'คุณยังสามารถสร้างปริศนารูปภาพของคุณเองโดยใช้ <a href="/other/15puzzle/generator">เครื่องสร้างปริศนา</a> — อัปโหลดภาพใดก็ได้ เลือกโหมด และแชร์ลิงก์กับใครก็ได้',
    "fp_htp_desc": "เรียนรู้วิธีเล่นปริศนา 15 ชิ้น — เกมกระเบื้องเลื่อนแบบคลาสสิก ทำความเข้าใจกฎ การควบคุม โหมดรูปภาพ และกลยุทธ์ในการแก้ปริศนาอย่างรวดเร็ว",
    "fp_htp_ex_midgame": "ระหว่างทาง แถวบนกำลังเข้าที่ มุ่งเน้นการทำให้ครบทีละแถวจากบนลงล่าง",
    "fp_htp_ex_nearlydone": "เกือบเสร็จแล้ว มีเพียงแถวล่างที่ยังคงสับเปลี่ยนอยู่ ในขั้นตอนนี้ต้องการการปรับเล็กน้อย — หลีกเลี่ยงการยกเลิกความคืบหน้าในแถวที่แก้ไปแล้ว",
    "fp_htp_ex_scrambled": "ตำแหน่งเริ่มต้น กระเบื้องถูกสุ่มแต่แก้ได้เสมอ ช่องว่าง (สี่เหลี่ยมสีเข้ม) สามารถอยู่ที่ใดก็ได้บนกระดาน",
    "fp_htp_ex_solved": "แก้ได้แล้ว! กระเบื้องทั้งหมดเรียงตามลำดับและรูปภาพเต็มรูปแบบถูกเปิดเผย เวลาและจำนวนการเดินของคุณถูกบันทึกไว้สำหรับลีดเดอร์บอร์ด",
    "fp_htp_example_h2": "ตัวอย่าง: การแก้ปริศนาทีละขั้นตอน",
    "fp_htp_example_intro": "ภาพหน้าจอด้านล่างแสดงปริศนารูปภาพที่กำลังถูกแก้โดยใช้ Lady Di's Mines เป็นภาพ กระเบื้องแต่ละชิ้นมีตัวเลขและส่วนหนึ่งของภาพ — ดังนั้นคุณสามารถใช้ภาพเป็นแนวทางทางสายตาขณะแก้ปริศนา",
    "fp_htp_goal_h2": "เป้าหมาย",
    "fp_htp_goal_p1": "จัดเรียงกระเบื้องทั้ง 15 ชิ้นตามลำดับจากน้อยไปมาก — จากซ้ายไปขวา บนลงล่าง — โดยมีช่องว่างอยู่มุมขวาล่าง ตำแหน่งที่แก้ได้มีลักษณะดังนี้: 1, 2, 3, 4 ในแถวบน จากนั้น 5, 6, 7, 8 จากนั้น 9, 10, 11, 12 จากนั้น 13, 14, 15 และช่องว่าง",
    "fp_htp_goal_p2": "คะแนนของคุณคือการผสมผสานของจำนวนการเดินที่ใช้และความเร็วในการแก้ปริศนา การเดินน้อยลงและเวลาน้อยลงหมายความว่าอันดับในลีดเดอร์บอร์ดดีขึ้น",
    "fp_htp_intro": "ปริศนา 15 ชิ้นเป็นเกมกระเบื้องเลื่อนแบบคลาสสิกที่เล่นบนตาราง 4\xd74 กระเบื้องที่มีหมายเลข 15 ชิ้นเติมเต็มกระดาน เหลือช่องว่างหนึ่งช่อง เลื่อนกระเบื้องเข้าสู่ช่องว่างเพื่อจัดเรียงใหม่จนกว่ากระเบื้องทุกชิ้นจะเรียงตามลำดับจาก 1 ถึง 15",
    "fp_htp_photo_h2": "โหมดปริศนารูปภาพ",
    "fp_htp_photo_p1": "ปริศนาประจำวันและปริศนารูปภาพที่กำหนดเองมีสองโหมดภาพที่แตกต่างกัน:",
    "fp_htp_photo_reveal": "<strong>เปิดเผยเมื่อชนะ</strong> — กระเบื้องแสดงเฉพาะตัวเลขขณะที่คุณแก้ปริศนา เมื่อวางกระเบื้องสุดท้ายถูกต้อง รูปภาพเต็มรูปแบบจะถูกเปิดเผยด้านล่าง รูปภาพเป็นรางวัลสำหรับการทำให้เสร็จ ไม่ใช่คำใบ้",
    "fp_htp_photo_tiles": "<strong>โหมดกระเบื้อง</strong> — กระเบื้องแต่ละชิ้นแสดงส่วนหนึ่งของรูปภาพ รูปภาพให้บริบทด้านสายตาเพื่อนำทางการแก้ปริศนา — ใช้ภาพเป็นชั้นข้อมูลที่สองเหนือตัวเลข",
    "fp_htp_strategy_h2": "กลยุทธ์",
    "fp_htp_strategy_p1": "<strong>แก้ปริศนาทีละแถวจากบนลงล่าง</strong> แถว 1 และ 2 สามารถแต่ละแถวทำให้เสร็จและล็อคในตำแหน่งได้โดยไม่รบกวนสิ่งใดด้านบน สองแถวสุดท้าย (กระเบื้อง 9–15) จะแก้ร่วมกันโดยใช้เทคนิคการหมุน",
    "fp_htp_strategy_p2": "<strong>วางกระเบื้อง 1 และกระเบื้อง 2 ด้วยกัน</strong> การพยายามเลื่อนกระเบื้อง 1 เข้าตำแหน่งคนเดียวมักจะเคลื่อนกระเบื้อง 2 ออกไป แต่ควรซ้อมรบกระเบื้อง 1 และ 2 ทั้งคู่ไปยังตำแหน่งคอลัมน์ที่ถูกต้องพร้อมกัน แล้วหมุนเข้าแถวบนสุดในเวลาเดียวกัน",
    "fp_htp_strategy_p3": "<strong>ใช้การเลื่อนหลายกระเบื้อง</strong> การคลิกหรือแตะกระเบื้องที่ไม่ได้อยู่ติดกับช่องว่างโดยตรงจะเลื่อนทั้งแถวหรือคอลัมน์ที่อยู่ระหว่างกลาง ซึ่งเร็วกว่าการเลื่อนกระเบื้องทีละชิ้นและจำเป็นสำหรับการแก้ปริศนาอย่างมีประสิทธิภาพ",
    "fp_htp_strategy_p4": "<strong>นับการเดินของคุณ</strong> การเลื่อนทุกครั้งนับเป็นการเดินหนึ่งครั้ง รวมถึงการเลื่อนหลายกระเบื้อง การเลื่อนหลายกระเบื้องที่วางแผนดีเพียงครั้งเดียวสามารถประหยัดการเดินกระเบื้องเดี่ยวหลายครั้ง — วางแผนล่วงหน้าเพื่อลดจำนวนการเดิน",
    "fp_htp_title": "วิธีเล่นปริศนา 15 ชิ้น | minesweeper.org",
    "fp_moves": "การเดิน:",
    "fp_name_label": "ชื่อ",
    "fp_new_game": "↺ เกมใหม่",
    "fp_photo_puzzle": "ปริศนารูปภาพ",
    "fp_same_for_all": "ปริศนาเดียวกันสำหรับทุกคน · รีเซ็ตเที่ยงคืน UTC",
    "fp_solved": "🎉 แก้ได้แล้ว!",
    "fp_submit_score": "ส่งคะแนนของคุณ",
    "fp_time": "เวลา:",
    "fp_today_heading": "วันนี้ — ",
}

insert_fp.LANGS["pgl"] = {
    "fp_col_moves": "Ovesmay",
    "fp_gen_copy": "Opycay",
    "fp_gen_delete": "Eleteday",
    "fp_gen_file_label": "JPG orway PNG, axmay 2MB",
    "fp_gen_limit_post": "-uzzlepay imitlay. Eleteday away avedsay uzzlepay otay akemay oomray.",
    "fp_gen_limit_pre": "Ouyay'evay eachedray ouryay\xa0",
    "fp_gen_limit_reached": "Uzzlepay imitlay eachedray",
    "fp_gen_mode_h2": "2. Oosechay Otophay Odemay",
    "fp_gen_mode_hint": "<strong>Ilestay:</strong> ethay otophay isway icedslway acrossway ethay ilestay andway crambledsay ithway emthay.<br><strong>Evealray onway inway:</strong> ilestay owshay umbersnay; olvingsay evealstray ethay otophay underneathway.",
    "fp_gen_mode_reveal": "Evealray onway inway",
    "fp_gen_mode_tiles": "Ilestay",
    "fp_gen_no_puzzles": "Onay avedsay uzzlespay etyay. Eatecray oneway aboveay!",
    "fp_gen_refresh": "Efreshray",
    "fp_gen_refresh_hint": "otay eesay itway inway ouryay avedsay istlay elowbay.",
    "fp_gen_save_btn": "Avesay &amp; Etgay Inklay",
    "fp_gen_saved_title": "Uzzlepay avedsay! Areshay isthay inklay:",
    "fp_gen_scramble": "↺ Cramblesay",
    "fp_gen_signin_btn": "Ignsay inway",
    "fp_gen_signin_msg": 'Ouyay ustmay <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">Ignsay Inway</a> otay uploadway otosphay andway avesay uzzlespay.',
    "fp_gen_title_label": "Uzzlepay itletay (optionalway)",
    "fp_gen_title_ph": "Ymay awesomeway uzzlepay",
    "fp_gen_untitled": "Untitledway uzzlepay",
    "fp_gen_upload_h2": "1. Uploadway away Otophay",
    "fp_gen_your_puzzles": "Ouryay Avedsay Uzzlespay",
    "fp_htp_back": "← Ayplay Odaytay's Uzzlepay",
    "fp_htp_controls_desktop_li1": "<strong>Ickclay away iletay</strong> adjacentway otay ethay emptyway acespay otay ideslway itway inway.",
    "fp_htp_controls_desktop_li2": "<strong>Ickclay away iletay urtherfay awayway</strong> inway ethay amesay owray orway olumncay andway ethay entireway inelway ofway ilestay etweenbay itway andway ethay emptyway acespay idesslay ogethertay inway oneway ovemay — ustjay ikelay away ealray ysicalpay uzzlepay.",
    "fp_htp_controls_desktop_li3": "<strong>Arrowway eyskay</strong> ovemay away iletay intoway ethay emptyway acespay omfray ethay orrespondingcay irectionday.",
    "fp_htp_controls_footer": "Useway ethay <strong>Ewnay Amegay</strong> uttonbay otay esetray ethay oardbay andway artstay overway atway anyway imetay.",
    "fp_htp_controls_h2": "Ontrolscay",
    "fp_htp_controls_mobile_li1": "<strong>Aptay away iletay</strong> adjacentway otay ethay emptyway acespay otay ideslway itway inway.",
    "fp_htp_controls_mobile_li2": "<strong>Aptay away iletay urtherfay awayway</strong> inway ethay amesay owray orway olumncay andway ethay olwhay owray orway olumncay idesslay inway oneway ovemay.",
    "fp_htp_daily_h2": "Ailyday Uzzlepay",
    "fp_htp_daily_p1": "Away ewnay uzzlepay isway eneratedgay everyway ayday atway idnightmay UTC — ethay amesay crambledsay oardbay orfay everyway ayerplay orldwideway. Olvesay itway, ubmitsay ouryay orescsay, andway eesay owhay ouyay ankray onway ethay eaderboardlay.",
    "fp_htp_daily_p2": 'Ouyay ancay alsoay eatecray ouryay ownway otophay uzzlepay usingway ethay <a href="/other/15puzzle/generator">Uzzlepay Eneratorgay</a> — uploadway anyway imageway, oosechay ouryay odemay, andway areshay ethay inklay ithway anyoneway.',
    "fp_htp_desc": "Earnlay owhay otay ayplay ethay 15-Uzzlepay — ethay assicalclay idingsley iletay amegay. Understandway ethay ulesray, ontrolscay, otophay odesmay, andway ategystray otay olvesay itway astfay.",
    "fp_htp_ex_midgame": "Idwaymay oughthray. Ethay optay owsray arehay allingfay intoway acepay. Ocusfay onway ompletingcay oneway owray atway away imetay omfray ethay optay ownday.",
    "fp_htp_ex_nearlydone": "Earlynay inishedfay. Onlyway ethay ottombay owsray emainray crambledsay. Atway isthay tagestay allsmay adjustmentsway arehay eededway — avoidway undoingway ogresspray inway owsray alreadyway olvedsay.",
    "fp_htp_ex_scrambled": "Ethay artingstay ositionpay. Ilestay arehay andomisedrray utbay alwaysway olvablesay. Ethay emptyway acespay (arkday quaresay) ancay ebay anywhereay onway ethay oardbay.",
    "fp_htp_ex_solved": "Olvedsay! Allway ilestay arehay inway orderway andway ethay ullfay imageway isway evealedray. Ouryay imetay andway ovemay ountcay arehay ecordedray orfay ethay eaderboardlay.",
    "fp_htp_example_h2": "Exampleway: Olvingsay Epstay ybay Epstay",
    "fp_htp_example_intro": "Ethay creenshotssay elowbay owshay away otophay uzzlepay eingbay olvedsay usingway Lady Di's Mines asway ethay imageway. Eachway iletay arriesway away umbernay andway away agmentfray ofway ethay icturepay — osay ouyay ancay useway ethay imageway asway away isualvay uideGay ilewhay ouyay olvesay.",
    "fp_htp_goal_h2": "Ethay Oalway",
    "fp_htp_goal_p1": "Arrangeway allway 15 ilestay inway ascendingway orderway — eftlay otay ightray, optay otay ottombay — ithway ethay emptyway acespay inway ethay ottom-rightbay ornercay. Ethay olvedsay ositionpay ookslay ikelay isthay: 1, 2, 3, 4 acrossway ethay optay owray, enthway 5, 6, 7, 8, enthway 9, 10, 11, 12, enthway 13, 14, 15 andway ethay ankblay.",
    "fp_htp_goal_p2": "Ouryay orescsay isway away ombinationcay ofway owhay anymay ovesmay ouyay usedway andway owhay astfay ouyay olvedsay itway. Ewerfay ovesmay andway esslay imetay eansmay away etterbay eaderboardlay ankingray.",
    "fp_htp_intro": "Ethay 15-Uzzlepay isway away assicalclay idingsley iletay amegay ayedplay onway away 4\xd74 idgray. Ifteenfay umberednay ilestay illfay ethay oardbay, eavingleay oneway emptyway acespay. Ideslway ilestay intoway ethay emptyway acespay otay earrangeray emthay untilway everyway iletay isway inway orderway omfray 1 otay 15.",
    "fp_htp_photo_h2": "Otophay Uzzlepay Odesmay",
    "fp_htp_photo_p1": "Ethay ailyday uzzlepay andway ustomcay otophay uzzlespay offerway otway ifferentday isualvay odesmay:",
    "fp_htp_photo_reveal": "<strong>Evealray onway inway</strong> — ilestay owshay onlyway umbersnay ilewhay ouyay olvesay. Enthway ouyay acepay ethay astlay iletay orrectlycay, ethay ullfay otophay isway evealedray underneathway. Ethay imageway isway away ewardray orfay inishingfay, otnay away inthay.",
    "fp_htp_photo_tiles": "<strong>Ilestay odemay</strong> — eachway iletay owshay itsway iceslway ofway ethay otophay. Ethay imageway ivesgay ouyay isualvay ontextcay otay uideGay ouryay olvingsay — useway ethay icturepay asway away econdsay ayerlay ofway informationway onway optay ofway ethay umbersnay.",
    "fp_htp_strategy_h2": "Ategystray",
    "fp_htp_strategy_p1": "<strong>Olvesay owray ybay owray omfray ethay optay.</strong> Owsray 1 andway 2 ancay eachway ebay ompletedcay andway ockedlay inway acepay ithoutway isturbingday anythingway aboveay. Ethay inalfay otway owsray (ilestay 9–15) arehay olvedsay ogethertay usingway away otationray echniquetay.",
    "fp_htp_strategy_p2": "<strong>Aceplay iletay 1 andway iletay 2 ogethertay.</strong> Yingtray otay ideslway iletay 1 intoway ositionpay ybay itselfway oftenway isplacesday iletay 2. Insteadway, anoeuvreway othbay ilestay 1 andway iletay 2 intoway eirthay orrectcay olumncay ositionspay imultaneouslysay, enthway otateray emthay intoway ethay optay owray atway ethay amesay imetay.",
    "fp_htp_strategy_p3": "<strong>Useway ulti-may iletay idesslay.</strong> Ickingclay orway appingtay away iletay atthay isway otnay irectlyday adjacentway otay ethay emptyway acespay idesslay ethay olwhay interveningway owray orway olumncay. Isthay isway asterfay anthay ovingmay ilestay oneway atway away imetay andway isway essentialway orfay efficientway olvingsay.",
    "fp_htp_strategy_p4": "<strong>Ountcay ouryay ovesmay.</strong> Everyway ideslway ountscay asway oneway ovemay, includingway ulti-may iletay idesslay. Away inglesay ell-plannedway ulti-may iletay ideslway ancay avesay everalsay ingle-may iletay ovesmay — anplay aheadway otay inimisemay ouryay ountcay.",
    "fp_htp_title": "Owhay otay Ayplay ethay 15-Uzzlepay | minesweeper.org",
    "fp_moves": "Ovesmay:",
    "fp_name_label": "Amenay",
    "fp_new_game": "↺ Ewnay Amegay",
    "fp_photo_puzzle": "Otophay uzzlepay",
    "fp_same_for_all": "Amesay uzzlepay orfay everyoneway \xb7 Esetsray atway idnightmay UTC",
    "fp_solved": "🎉 Olvedsay!",
    "fp_submit_score": "Ubmitsay ouryay orescsay",
    "fp_time": "Imetay:",
    "fp_today_heading": "Odaytay — ",
}

if __name__ == "__main__":
    for lang in ["pl", "tl", "th", "pgl"]:
        insert_fp.insert_lang(lang)
