"""mj_* batch 2: uk, ru, pt, it"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_mj

insert_mj.LANGS["uk"] = {
    "mj_hint_free": "Показати вільні плитки",
    "mj_hint_match": "Показати збіги",
    "mj_htp_back": "Грати у сьогоднішній пазл",
    "mj_htp_controls_h2": "Управління",
    "mj_htp_controls_li1": "<strong>Натисніть на вільну плитку</strong>, щоб вибрати її (виділена золотом).",
    "mj_htp_controls_li2": "<strong>Натисніть на другу вільну плитку</strong> того ж типу, щоб видалити пару.",
    "mj_htp_controls_li3": "<strong>Натисніть на вибрану плитку ще раз</strong>, щоб скасувати вибір.",
    "mj_htp_controls_li4": "<strong>Скасувати</strong> відміняє одну підібрану пару за раз.",
    "mj_htp_daily_h2": "Щоденний пазл",
    "mj_htp_daily_p": "Щодня генерується нова дошка на основі поточної дати — однакова дошка для всіх гравців у світі. Таймер запускається, коли ви натискаєте на першу плитку. Завершіть дошку, щоб відправити свій час до таблиці лідерів.",
    "mj_htp_desc": "Дізнайтеся правила Маджонг Пасьянс — підбирайте пари вільних плиток, використовуйте підказки та очистіть дошку Черепаха.",
    "mj_htp_free_h2": "Що таке вільна плитка?",
    "mj_htp_free_p": "Плитка є <strong>вільною</strong>, якщо виконуються дві умови: (1) жодна плитка не складена на ній зверху, і (2) вона відкрита з лівого <em>або</em> правого боку — тобто немає сусідньої плитки на тому ж шарі принаймні з одного боку.",
    "mj_htp_goal_h2": "Мета",
    "mj_htp_goal_p": "Видаліть усі 144 плитки з дошки, вибираючи відповідні пари. Обидві плитки у парі повинні бути <strong>вільними</strong>. Гра виграна, коли дошка порожня.",
    "mj_htp_hints_h2": "Кнопки підказок",
    "mj_htp_hints_p": "<strong>Показати вільні плитки</strong> підсвічує синім усі доступні плитки. <strong>Показати збіги</strong> підсвічує зеленим вільні плитки, у яких є принаймні один відповідний вільний партнер.",
    "mj_htp_intro": "Маджонг Пасьянс — це гра для одного гравця із підбором плиток. 144 плитки складені у класичну формацію Черепаха. Ваша мета — видалити всі плитки, підбираючи ідентичні вільні пари.",
    "mj_htp_refs_h2": "Посилання",
    "mj_htp_refs_p": 'Ця реалізація заснована на проекті з відкритим кодом <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a> від ffalt. Дізнайтеся більше про гру на <a href="https://uk.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B4%D0%B6%D0%BE%D0%BD%D0%B3_%D0%BF%D0%B0%D1%81%D1%8C%D1%8F%D0%BD%D1%81" target="_blank" rel="noopener noreferrer">Вікіпедії</a>.',
    "mj_htp_tiles_h2": "Типи плиток &amp; підбір",
    "mj_htp_tiles_p": "Повний набір містить 144 плитки: дев'ять Кіл (1–9), дев'ять Бамбуків (1–9), дев'ять Знаків (1–9), чотири Вітри (Схід, Південь, Захід, Північ), три Дракони (Червоний, Зелений, Білий), чотири Пори року та чотири Квіти. Більшість плиток підходять лише до ідентичних пар. <strong>Виняток:</strong> будь-які дві плитки Пори року підходять одна до одної, і будь-які дві плитки Квітки підходять одна до одної.",
    "mj_htp_title": "Як грати в Маджонг Пасьянс | minesweeper.org",
    "mj_lb_all_heading": "За весь час",
    "mj_lb_season_heading": "Цього місяця",
    "mj_lb_tab_all": "За весь час",
    "mj_lb_tab_daily": "Сьогодні",
    "mj_lb_tab_season": "Цього місяця",
    "mj_name_label": "Ім'я",
    "mj_new_game": "Нова гра",
    "mj_play_today": "Грати сьогодні",
    "mj_removed_pairs": "Видалені пари",
    "mj_same_for_all": "Однакова дошка для всіх · Скидається опівночі UTC",
    "mj_solved": "🎉 Вирішено!",
    "mj_submit_btn": "Відправити рахунок",
    "mj_submit_score": "Відправити свій рахунок",
    "mj_time": "Час:",
    "mj_today_heading": "Сьогодні — ",
    "mj_undo": "Скасувати",
}

insert_mj.LANGS["ru"] = {
    "mj_hint_free": "Показать свободные плитки",
    "mj_hint_match": "Показать совпадения",
    "mj_htp_back": "Играть в сегодняшний пазл",
    "mj_htp_controls_h2": "Управление",
    "mj_htp_controls_li1": "<strong>Нажмите на свободную плитку</strong>, чтобы выбрать её (выделена золотом).",
    "mj_htp_controls_li2": "<strong>Нажмите на вторую свободную плитку</strong> того же типа, чтобы удалить пару.",
    "mj_htp_controls_li3": "<strong>Нажмите на выбранную плитку снова</strong>, чтобы отменить выбор.",
    "mj_htp_controls_li4": "<strong>Отмена</strong> отменяет одну подобранную пару за раз.",
    "mj_htp_daily_h2": "Ежедневный пазл",
    "mj_htp_daily_p": "Каждый день генерируется новое поле на основе сегодняшней даты — одно и то же поле для всех игроков по всему миру. Таймер запускается при нажатии на первую плитку. Завершите поле, чтобы отправить своё время в таблицу лидеров.",
    "mj_htp_desc": "Узнайте правила Маджонг Пасьянса — подбирайте пары свободных плиток, используйте подсказки и очищайте поле Черепаха.",
    "mj_htp_free_h2": "Что такое свободная плитка?",
    "mj_htp_free_p": "Плитка является <strong>свободной</strong>, если выполняются два условия: (1) на ней не лежит никаких других плиток, и (2) она открыта с левой <em>или</em> правой стороны — то есть нет соседней плитки на том же слое хотя бы с одной стороны.",
    "mj_htp_goal_h2": "Цель",
    "mj_htp_goal_p": "Уберите все 144 плитки с поля, выбирая совпадающие пары. Обе плитки в паре должны быть <strong>свободными</strong>. Игра выиграна, когда поле пустое.",
    "mj_htp_hints_h2": "Кнопки подсказок",
    "mj_htp_hints_p": "<strong>Показать свободные плитки</strong> выделяет синим все доступные плитки. <strong>Показать совпадения</strong> выделяет зелёным свободные плитки, у которых есть хотя бы один подходящий свободный партнёр.",
    "mj_htp_intro": "Маджонг Пасьянс — это одиночная игра по подбору плиток. 144 плитки сложены в классическую формацию Черепаха. Ваша цель — убрать все плитки, подбирая идентичные свободные пары.",
    "mj_htp_refs_h2": "Источники",
    "mj_htp_refs_p": 'Эта реализация основана на проекте с открытым исходным кодом <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a> от ffalt. Узнайте больше об игре на <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B4%D0%B6%D0%BE%D0%BD%D0%B3_%D0%BF%D0%B0%D1%81%D1%8C%D1%8F%D0%BD%D1%81" target="_blank" rel="noopener noreferrer">Википедии</a>.',
    "mj_htp_tiles_h2": "Типы плиток &amp; подбор",
    "mj_htp_tiles_p": "Полный набор включает 144 плитки: девять Кругов (1–9), девять Бамбуков (1–9), девять Знаков (1–9), четыре Ветра (Восток, Юг, Запад, Север), три Дракона (Красный, Зелёный, Белый), четыре Времени года и четыре Цветка. Большинство плиток совпадают только с идентичными парами. <strong>Исключение:</strong> любые две плитки Времени года совпадают друг с другом, и любые две плитки Цветка совпадают друг с другом.",
    "mj_htp_title": "Как играть в Маджонг Пасьянс | minesweeper.org",
    "mj_lb_all_heading": "За всё время",
    "mj_lb_season_heading": "В этом месяце",
    "mj_lb_tab_all": "За всё время",
    "mj_lb_tab_daily": "Сегодня",
    "mj_lb_tab_season": "В этом месяце",
    "mj_name_label": "Имя",
    "mj_new_game": "Новая игра",
    "mj_play_today": "Играть сегодня",
    "mj_removed_pairs": "Удалённые пары",
    "mj_same_for_all": "Одинаковое поле для всех · Сброс в полночь UTC",
    "mj_solved": "🎉 Решено!",
    "mj_submit_btn": "Отправить результат",
    "mj_submit_score": "Отправить свой результат",
    "mj_time": "Время:",
    "mj_today_heading": "Сегодня — ",
    "mj_undo": "Отменить",
}

insert_mj.LANGS["pt"] = {
    "mj_hint_free": "Mostrar peças livres",
    "mj_hint_match": "Mostrar correspondências",
    "mj_htp_back": "Jogar o puzzle de hoje",
    "mj_htp_controls_h2": "Controlos",
    "mj_htp_controls_li1": "<strong>Clique numa peça livre</strong> para a selecionar (realçada a dourado).",
    "mj_htp_controls_li2": "<strong>Clique numa segunda peça livre</strong> do mesmo tipo para remover o par.",
    "mj_htp_controls_li3": "<strong>Clique novamente na peça selecionada</strong> para a desselecionar.",
    "mj_htp_controls_li4": "<strong>Desfazer</strong> retrocede um par combinado de cada vez.",
    "mj_htp_daily_h2": "Puzzle diário",
    "mj_htp_daily_p": "Todos os dias é gerado um novo tabuleiro a partir da data de hoje — o mesmo tabuleiro para todos os jogadores em todo o mundo. O temporizador inicia quando clica na sua primeira peça. Complete o tabuleiro para submeter o seu tempo ao ranking.",
    "mj_htp_desc": "Aprenda as regras do Mahjong Solitaire — combine pares de peças livres, use dicas e esvazie o tabuleiro Tartaruga.",
    "mj_htp_free_h2": "O que é uma peça livre?",
    "mj_htp_free_p": "Uma peça está <strong>livre</strong> quando duas condições são cumpridas: (1) nenhuma peça está empilhada em cima dela, e (2) está aberta no seu lado esquerdo <em>ou</em> direito — ou seja, não há nenhuma peça adjacente na mesma camada em pelo menos um lado.",
    "mj_htp_goal_h2": "O objetivo",
    "mj_htp_goal_p": "Remova todas as 144 peças do tabuleiro selecionando pares correspondentes. Ambas as peças de um par devem estar <strong>livres</strong>. O jogo é ganho quando o tabuleiro está vazio.",
    "mj_htp_hints_h2": "Botões de dica",
    "mj_htp_hints_p": "<strong>Mostrar peças livres</strong> realça a azul todas as peças atualmente acessíveis. <strong>Mostrar correspondências</strong> realça a verde as peças livres que têm pelo menos um parceiro livre correspondente.",
    "mj_htp_intro": "O Mahjong Solitaire é um jogo de correspondência de peças para um jogador. 144 peças estão empilhadas na formação clássica da Tartaruga. O seu objetivo é remover todas as peças combinando pares livres idênticos.",
    "mj_htp_refs_h2": "Referências",
    "mj_htp_refs_p": 'Esta implementação é baseada no projeto de código aberto <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a> de ffalt. Saiba mais sobre o jogo na <a href="https://pt.wikipedia.org/wiki/Mahjong_solitaire" target="_blank" rel="noopener noreferrer">Wikipédia</a>.',
    "mj_htp_tiles_h2": "Tipos de peças &amp; correspondência",
    "mj_htp_tiles_p": "O conjunto completo usa 144 peças: nove Círculos (1–9), nove Bambus (1–9), nove Caracteres (1–9), quatro Ventos (Este, Sul, Oeste, Norte), três Dragões (Vermelho, Verde, Branco), quatro Estações e quatro Flores. A maioria das peças só combina com pares idênticos. <strong>Exceção:</strong> quaisquer duas peças de Estação combinam entre si, e quaisquer duas peças de Flor combinam entre si.",
    "mj_htp_title": "Como jogar Mahjong Solitaire | minesweeper.org",
    "mj_lb_all_heading": "Desde sempre",
    "mj_lb_season_heading": "Este mês",
    "mj_lb_tab_all": "Desde sempre",
    "mj_lb_tab_daily": "Hoje",
    "mj_lb_tab_season": "Este mês",
    "mj_name_label": "Nome",
    "mj_new_game": "Novo jogo",
    "mj_play_today": "Jogar hoje",
    "mj_removed_pairs": "Pares removidos",
    "mj_same_for_all": "Mesmo tabuleiro para todos · Reinicia à meia-noite UTC",
    "mj_solved": "🎉 Resolvido!",
    "mj_submit_btn": "Enviar pontuação",
    "mj_submit_score": "Envie a sua pontuação",
    "mj_time": "Tempo:",
    "mj_today_heading": "Hoje — ",
    "mj_undo": "Desfazer",
}

insert_mj.LANGS["it"] = {
    "mj_hint_free": "Mostra tessere libere",
    "mj_hint_match": "Mostra corrispondenze",
    "mj_htp_back": "Gioca il puzzle di oggi",
    "mj_htp_controls_h2": "Controlli",
    "mj_htp_controls_li1": "<strong>Clicca su una tessera libera</strong> per selezionarla (evidenziata in oro).",
    "mj_htp_controls_li2": "<strong>Clicca su una seconda tessera libera</strong> dello stesso tipo per rimuovere la coppia.",
    "mj_htp_controls_li3": "<strong>Clicca di nuovo sulla tessera selezionata</strong> per deselezionarla.",
    "mj_htp_controls_li4": "<strong>Annulla</strong> torna indietro di una coppia abbinata alla volta.",
    "mj_htp_daily_h2": "Puzzle quotidiano",
    "mj_htp_daily_p": "Ogni giorno viene generato un nuovo tabellone dalla data odierna — lo stesso tabellone per ogni giocatore in tutto il mondo. Il timer inizia quando fai clic sulla prima tessera. Completa il tabellone per inviare il tuo tempo alla classifica.",
    "mj_htp_desc": "Impara le regole del Mahjong Solitaire — abbina coppie di tessere libere, usa i suggerimenti e svuota il tabellone Tartaruga.",
    "mj_htp_free_h2": "Cos'è una tessera libera?",
    "mj_htp_free_p": "Una tessera è <strong>libera</strong> quando sono soddisfatte due condizioni: (1) nessuna tessera è impilata sopra di essa, e (2) è aperta sul lato sinistro <em>o</em> destro — ovvero nessuna tessera adiacente sullo stesso strato su almeno un lato.",
    "mj_htp_goal_h2": "L'obiettivo",
    "mj_htp_goal_p": "Rimuovi tutte le 144 tessere dal tabellone selezionando coppie corrispondenti. Entrambe le tessere di una coppia devono essere <strong>libere</strong>. Il gioco è vinto quando il tabellone è vuoto.",
    "mj_htp_hints_h2": "Pulsanti suggerimento",
    "mj_htp_hints_p": "<strong>Mostra tessere libere</strong> evidenzia in blu tutte le tessere attualmente accessibili. <strong>Mostra corrispondenze</strong> evidenzia in verde le tessere libere che hanno almeno un partner libero corrispondente.",
    "mj_htp_intro": "Il Mahjong Solitaire è un gioco di abbinamento di tessere per un singolo giocatore. 144 tessere sono impilate nella classica formazione a Tartaruga. Il tuo obiettivo è rimuovere tutte le tessere abbinando paia libere identiche.",
    "mj_htp_refs_h2": "Riferimenti",
    "mj_htp_refs_p": 'Questa implementazione è basata sul progetto open-source <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a> di ffalt. Scopri di più sul gioco su <a href="https://it.wikipedia.org/wiki/Mahjong_solitaire" target="_blank" rel="noopener noreferrer">Wikipedia</a>.',
    "mj_htp_tiles_h2": "Tipi di tessere &amp; abbinamento",
    "mj_htp_tiles_p": "Il set completo usa 144 tessere: nove Cerchi (1–9), nove Bambù (1–9), nove Caratteri (1–9), quattro Venti (Est, Sud, Ovest, Nord), tre Draghi (Rosso, Verde, Bianco), quattro Stagioni e quattro Fiori. La maggior parte delle tessere si abbina solo con paia identiche. <strong>Eccezione:</strong> due qualsiasi tessere Stagione si abbinano tra loro, e due qualsiasi tessere Fiore si abbinano tra loro.",
    "mj_htp_title": "Come giocare a Mahjong Solitaire | minesweeper.org",
    "mj_lb_all_heading": "Da sempre",
    "mj_lb_season_heading": "Questo mese",
    "mj_lb_tab_all": "Da sempre",
    "mj_lb_tab_daily": "Oggi",
    "mj_lb_tab_season": "Questo mese",
    "mj_name_label": "Nome",
    "mj_new_game": "Nuova partita",
    "mj_play_today": "Gioca oggi",
    "mj_removed_pairs": "Coppie rimosse",
    "mj_same_for_all": "Stesso tabellone per tutti · Si azzera a mezzanotte UTC",
    "mj_solved": "🎉 Risolto!",
    "mj_submit_btn": "Invia punteggio",
    "mj_submit_score": "Invia il tuo punteggio",
    "mj_time": "Tempo:",
    "mj_today_heading": "Oggi — ",
    "mj_undo": "Annulla",
}

if __name__ == "__main__":
    for lang in ["uk", "ru", "pt", "it"]:
        insert_mj.insert_lang(lang)
