# -*- coding: utf-8 -*-
"""t2k_* batch 4: pl, tl, th, pgl"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_t2k

insert_t2k.LANGS["pl"] = {
    "t2k_game_over": "😥 Koniec gry",
    "t2k_htp_back": "← Graj w dzisiejsza zagadke",
    "t2k_htp_controls_desktop_li1": "<strong>Klawisze strzalek</strong> lub <strong>W A S D</strong> — przesuniecie wszystkich kafelkow w tym kierunku.",
    "t2k_htp_controls_desktop_li2": "Kazde nacisniecie klawisza to jeden ruch, nawet jesli przesuwa sie tylko jeden kafelek.",
    "t2k_htp_controls_footer": "Uzyj przycisku <strong>Nowa gra</strong>, aby zresetowac plansze i zaczac od nowa w dowolnym momencie.",
    "t2k_htp_controls_h2": "Sterowanie",
    "t2k_htp_controls_mobile_li1": "<strong>Przesun palcem</strong> w gore, dol, lewo lub prawo, aby przesunac wszystkie kafelki w tym kierunku.",
    "t2k_htp_controls_mobile_li2": "Kazde przesuniecnie to jeden ruch, nawet jesli przesuwa sie tylko jeden kafelek.",
    "t2k_htp_daily_h2": "Codzienna zagadka",
    "t2k_htp_daily_p1": "Kazdy dzien generuje nowa zagadke — ta sama plansze startowa dla kazdego gracza na swiecie. Zagadka resetuje sie o polnocy UTC. Wszyscy grajacy w codzienna zagadke danego dnia zaczynaja od identycznego ukladu kafelkow, tworzac uczciwa rywalizacje.",
    "t2k_htp_daily_p2": 'Po ukonczeniu codziennej zagadki mozesz wyslac swoj wynik do <a href="/other/2048/leaderboard">tabeli wynikow 2048</a>. Musisz byc zalogowany, aby wyslac.',
    "t2k_htp_desc": "Naucz sie grac w 2048 — klasyczna zagadke laczenia kafelkow. Zrozum zasady, sterowanie, punktacje i strategie, aby osiagnac kafelek 2048.",
    "t2k_htp_goal_h2": "Cel gry",
    "t2k_htp_goal_p1": "Przesuwaj kafelki na siatce, aby laczyc identyczne liczby. Gdy dwa kafelki o tej samej wartosci ze soba zderzaja, lacza sie w jeden kafelek o podwojnej wartosci — 2 i 2 staja sie 4, dwa 4 staja sie 8 i tak dalej. Celem jest zbudowanie kafelka, ktory osiagnie <strong>2048</strong>.",
    "t2k_htp_goal_p2": "Mozesz kontynuowac gre po osiagnieciu 2048, aby zwiekszyc swoj wynik. Gra konczy sie, gdy nie zostaly zadne ruchy — siatka jest pelna i zadne sasiednie kafelki nie maja tej samej wartosci.",
    "t2k_htp_intro": "2048 to zagadka z przesuwanymi kafelkami na siatce 4x4. Lacze ponumerowane kafelki, przesuwajac je w czterech kierunkach. Po kazdym ruchu pojawia sie nowy kafelek. Osiagnij kafelek 2048, aby wygrac — lub kontynuuj dla wyzszego wyniku.",
    "t2k_htp_scoring_h2": "Punktacja",
    "t2k_htp_scoring_p1": "Kazde polaczenie dodaje wartosc nowego polaczonego kafelka do twojego wyniku. Polaczenie dwoch kafelkow 512 w kafelek 1024 dodaje 1024 punkty. Lancuchowanie kilku polaczen w jednym ruchu sumuje je wszystkie.",
    "t2k_htp_scoring_p2": 'W codziennej zagadce twoj koncowy wynik, liczba ruchow i czas sa rejestrowane i wysylane do <a href="/other/2048/leaderboard">tabeli wynikow</a>. Tabela sortuje najpierw wedlug wyniku (wyzszy jest lepszy), nastepnie wedlug czasu (nizszy jest lepszy).',
    "t2k_htp_strategy_h2": "Podstawowa strategia",
    "t2k_htp_strategy_p1": "<strong>Wybierz naroznik i trzymaj sie go.</strong> Wybierz jeden naroznik — zazwyczaj dolny — i trzymaj tam swoj najcenniejszy kafelek. Buduj malejacy lancuch kafelkow wzdluz krawedzi odchodzacej od niego, tak aby kazde polaczenie naturalnie wchodziło w nastepne.",
    "t2k_htp_strategy_p2": "<strong>Nigdy nie przesuwaj od swojego naroznika kotwy.</strong> Unikaj ruchow, ktore odciagaja twoj najwiekszy kafelek od jego naroznika. Na przyklad, jesli twoj najwyzszy kafelek jest w lewym dolnym rogu, unikaj przesuwania w gore, chyba ze jest to absolutnie konieczne. Utrata kontroli nad naroznikiem to sposob, w jaki konczy sie wiekszosc gier.",
    "t2k_htp_strategy_p3": "<strong>Trzymaj gorny rzad pelny.</strong> Gdy masz lancuch wzdluz gornej lub dolnej krawedzi, staraj sie zawsze trzymac ten rzad pelny. To zmusza nowe kafelki do pojawienia sie gdzie indziej i zachowuje twoj lancuch.",
    "t2k_htp_strategy_p4": "<strong>Mysl z wyprzedzeniem.</strong> Przed kazdym ruchem zastanow sie, gdzie moze pojawic sie nowy kafelek i czy zaklocy twoj uklad. Ruchy, ktore zostawiaja plansze w nierealnym stanie, sa zazwyczaj znakiem, ze ruszylas sie bez mysli.",
    "t2k_htp_tiles_h2": "Wartosci kafelkow",
    "t2k_htp_tiles_p1": "Kafelki zawsze zaczynaja sie jako 2 lub 4 — jest 90% szans na 2 i 10% na 4. Nowe kafelki pojawiaja sie losowo w pustej komorce po kazdym ruchu. Sekwencja wartosci podwaja sie z kazdym polaczeniem: 2 -> 4 -> 8 -> 16 -> 32 -> 64 -> 128 -> 256 -> 512 -> 1024 -> 2048 i dalej.",
    "t2k_htp_tiles_p2": "Tylko kafelki o tej samej wartosci moga sie laczyc, a kazdy kafelek moze polaczyc sie co najwyzej raz na ruch.",
    "t2k_htp_title": "Jak grac w 2048 | minesweeper.org",
    "t2k_keep_going": "Kontynuuj",
    "t2k_score": "Wynik:",
    "t2k_solved": "Osiagnales 2048!",
}

insert_t2k.LANGS["tl"] = {
    "t2k_game_over": "😥 Game Over",
    "t2k_htp_back": "← Laruin ang puzzle ngayon",
    "t2k_htp_controls_desktop_li1": "<strong>Mga arrow key</strong> o <strong>W A S D</strong> — i-slide ang lahat ng tile sa direksyong iyon.",
    "t2k_htp_controls_desktop_li2": "Bawat pagpindot ng key ay isang galaw, kahit isang tile lamang ang gumalaw.",
    "t2k_htp_controls_footer": "Gamitin ang button na <strong>Bagong laro</strong> upang i-reset ang board at magsimula muli anumang oras.",
    "t2k_htp_controls_h2": "Mga kontrol",
    "t2k_htp_controls_mobile_li1": "<strong>Mag-swipe</strong> pataas, pababa, pakaliwa, o pakanan upang i-slide ang lahat ng tile sa direksyong iyon.",
    "t2k_htp_controls_mobile_li2": "Bawat swipe ay isang galaw, kahit isang tile lamang ang gumalaw.",
    "t2k_htp_daily_h2": "Araw-araw na palaisipan",
    "t2k_htp_daily_p1": "Bawat araw ay may bagong palaisipan na nabuo — parehong simulating board para sa bawat manlalaro sa buong mundo. Ang palaisipan ay nire-reset sa hatinggabi UTC. Lahat ng naglalaro ng araw-araw na palaisipan sa isang partikular na araw ay nagsisimula mula sa magkaparehong layout ng tile, na ginagawa itong isang makatarungang kompetisyon.",
    "t2k_htp_daily_p2": 'Pagkatapos makumpleto ang araw-araw na palaisipan maaari kang magsumite ng iyong iskor sa <a href="/other/2048/leaderboard">2048 leaderboard</a>. Kailangan mong naka-sign in upang magsumite.',
    "t2k_htp_desc": "Alamin kung paano maglaro ng 2048 — ang klasikong puzzle ng pagsasama ng tile. Unawain ang mga patakaran, kontrol, pagmamarka, at estratehiya upang maabot ang 2048 tile.",
    "t2k_htp_goal_h2": "Ang layunin",
    "t2k_htp_goal_p1": "Mag-slide ng mga tile sa grid upang pagsamahin ang magkaparehong numero. Kapag dalawang tile na may parehong halaga ang nagbanggaan, pinagsama ang mga ito sa isang tile na may doble ng halaga — ang 2 at 2 ay nagiging 4, dalawang 4 ay nagiging 8, at iba pa. Ang layunin ay bumuo ng tile na umabot sa <strong>2048</strong>.",
    "t2k_htp_goal_p2": "Maaari kang magpatuloy na maglaro pagkatapos maabot ang 2048 upang mapataas ang iyong iskor. Nagtatapos ang laro kapag walang natitirang galaw — ang grid ay puno at walang magkaratig na tile na nagbabahagi ng parehong halaga.",
    "t2k_htp_intro": "Ang 2048 ay isang sliding tile puzzle na nilalaro sa isang 4×4 na grid. Pagsamahin ang mga numbered tile sa pamamagitan ng pag-slide ng mga ito sa apat na direksyon. Sa bawat galaw ay lumalabas ang bagong tile. Abutin ang 2048 tile upang manalo — o magpatuloy para sa mas mataas na iskor.",
    "t2k_htp_scoring_h2": "Pagmamarka",
    "t2k_htp_scoring_p1": "Bawat pagsasama ay nagdadagdag ng halaga ng bagong pinagsaming tile sa iyong iskor. Ang pagsasama ng dalawang 512 tile sa isang 1024 tile ay nagdadagdag ng 1024 puntos. Ang pag-chain ng ilang pagsasama sa isang galaw ay idinaragdag ang lahat ng mga ito.",
    "t2k_htp_scoring_p2": 'Sa araw-araw na palaisipan, ang iyong panghuling iskor, bilang ng galaw, at oras ay naitala at isinumite sa <a href="/other/2048/leaderboard">leaderboard</a>. Ang leaderboard ay inuuri una ayon sa iskor (mas mataas ay mas magaling), pagkatapos ay ayon sa oras (mas mababa ay mas magaling).',
    "t2k_htp_strategy_h2": "Pangunahing estratehiya",
    "t2k_htp_strategy_p1": "<strong>Pumili ng sulok at manatili dito.</strong> Pumili ng isang sulok — kadalasang isang ibabang sulok — at panatilihin ang iyong pinakamataas na halaga ng tile doon. Bumuo ng pababang chain ng mga tile sa gilid na lumayo rito upang ang bawat pagsasama ay natural na pumunta sa susunod.",
    "t2k_htp_strategy_p2": "<strong>Huwag mag-slide palayo mula sa iyong anchor corner.</strong> Iwasan ang mga galaw na humihila sa iyong pinakamalaking tile palayo sa sulok nito. Halimbawa, kung ang iyong pinakamataas na tile ay nasa ibabang kaliwa, iwasan ang pag-swipe pataas maliban kung ito ay ganap na kinakailangan. Ang pagkawala ng kontrol sa sulok ay kung paano nagtatapos ang karamihan ng mga laro.",
    "t2k_htp_strategy_p3": "<strong>Panatilihing puno ang itaas na hilera.</strong> Kapag mayroon kang chain sa kabuuan ng tuktok o ibabang gilid, subukang panatilihing puno ang hilera na iyon sa lahat ng oras. Pinipilit nito ang mga bagong tile na lumabas sa ibang lugar at pinapanatili ang iyong chain.",
    "t2k_htp_strategy_p4": "<strong>Mag-isip nang maaga.</strong> Bago ang bawat galaw, isaalang-alang kung saan maaaring lumabas ang bagong tile at kung maaari itong makagambala sa iyong layout. Ang mga galaw na nag-iiwan ng board sa hindi na mapanumbalakin na estado ay karaniwang isang palatandaan na kumilos ka nang walang pag-iisip.",
    "t2k_htp_tiles_h2": "Mga halaga ng tile",
    "t2k_htp_tiles_p1": "Ang mga tile ay palaging nagsisimula bilang 2 o 4 — mayroong 90% na pagkakataon ng 2 at 10% na pagkakataon ng 4. Ang mga bagong tile ay lilitaw nang random sa isang walang laman na cell pagkatapos ng bawat galaw. Ang pagkakasunod-sunod ng mga halaga ay nagdoble sa bawat pagsasama: 2 → 4 → 8 → 16 → 32 → 64 → 128 → 256 → 512 → 1024 → 2048 at higit pa.",
    "t2k_htp_tiles_p2": "Ang mga tile lamang na may parehong halaga ay maaaring magsama, at ang bawat tile ay maaari lamang magsama nang isang beses bawat galaw.",
    "t2k_htp_title": "Paano Maglaro ng 2048 | minesweeper.org",
    "t2k_keep_going": "Magpatuloy",
    "t2k_score": "Iskor:",
    "t2k_solved": "Nakarating ka sa 2048!",
}

insert_t2k.LANGS["th"] = {
    "t2k_game_over": "😥 เกมจบ",
    "t2k_htp_back": "← เล่นปริศนาวันนี้",
    "t2k_htp_controls_desktop_li1": "<strong>ปุ่มลูกศร</strong> หรือ <strong>W A S D</strong> — เลื่อนกระเบื้องทั้งหมดไปในทิศทางนั้น",
    "t2k_htp_controls_desktop_li2": "การกดแต่ละครั้งคือการเคลื่อนที่หนึ่งครั้ง แม้จะมีกระเบื้องเพียงชิ้นเดียวเลื่อนก็ตาม",
    "t2k_htp_controls_footer": "ใช้ปุ่ม <strong>เกมใหม่</strong> เพื่อรีเซ็ตกระดานและเริ่มต้นใหม่ได้ทุกเมื่อ",
    "t2k_htp_controls_h2": "วิธีควบคุม",
    "t2k_htp_controls_mobile_li1": "<strong>ปัด</strong>ขึ้น ลง ซ้าย หรือขวา เพื่อเลื่อนกระเบื้องทั้งหมดไปในทิศทางนั้น",
    "t2k_htp_controls_mobile_li2": "การปัดแต่ละครั้งคือการเคลื่อนที่หนึ่งครั้ง แม้จะมีกระเบื้องเพียงชิ้นเดียวเลื่อนก็ตาม",
    "t2k_htp_daily_h2": "ปริศนาประจำวัน",
    "t2k_htp_daily_p1": "ทุกวันจะสร้างปริศนาใหม่ — กระดานเริ่มต้นเดียวกันสำหรับผู้เล่นทุกคนทั่วโลก ปริศนาจะรีเซ็ตเที่ยงคืน UTC ทุกคนที่เล่นปริศนาประจำวันในวันนั้นจะเริ่มต้นจากการจัดเรียงกระเบื้องที่เหมือนกัน ทำให้เป็นการแข่งขันที่ยุติธรรม",
    "t2k_htp_daily_p2": 'หลังจากทำปริศนาประจำวันเสร็จ คุณสามารถส่งคะแนนไปยัง <a href="/other/2048/leaderboard">กระดานผู้นำ 2048</a> ได้ คุณต้องเข้าสู่ระบบเพื่อส่ง',
    "t2k_htp_desc": "เรียนรู้วิธีเล่น 2048 — ปริศนาการรวมกระเบื้องคลาสสิก ทำความเข้าใจกฎ การควบคุม การให้คะแนน และกลยุทธ์เพื่อไปถึงกระเบื้อง 2048",
    "t2k_htp_goal_h2": "เป้าหมาย",
    "t2k_htp_goal_p1": "เลื่อนกระเบื้องบนตารางเพื่อรวมตัวเลขที่เหมือนกัน เมื่อกระเบื้องสองชิ้นที่มีค่าเท่ากันชนกัน พวกมันจะรวมกันเป็นกระเบื้องชิ้นเดียวที่มีค่าสองเท่า — 2 และ 2 กลายเป็น 4, สอง 4 กลายเป็น 8 เป็นต้น เป้าหมายคือสร้างกระเบื้องที่ถึง <strong>2048</strong>",
    "t2k_htp_goal_p2": "คุณสามารถเล่นต่อหลังจากถึง 2048 เพื่อเพิ่มคะแนน เกมจบเมื่อไม่มีการเคลื่อนที่เหลือ — ตารางเต็มและไม่มีกระเบื้องที่อยู่ติดกันที่มีค่าเท่ากัน",
    "t2k_htp_intro": "2048 เป็นปริศนากระเบื้องเลื่อนที่เล่นบนตาราง 4x4 รวมกระเบื้องที่มีตัวเลขเหมือนกันโดยเลื่อนไปสี่ทิศทาง ทุกการเคลื่อนที่จะมีกระเบื้องใหม่ปรากฏขึ้น ถึงกระเบื้อง 2048 เพื่อชนะ — หรือเล่นต่อเพื่อคะแนนที่สูงกว่า",
    "t2k_htp_scoring_h2": "การให้คะแนน",
    "t2k_htp_scoring_p1": "การรวมแต่ละครั้งจะเพิ่มค่าของกระเบื้องที่รวมใหม่ไปยังคะแนนของคุณ การรวมกระเบื้อง 512 สองชิ้นเป็นกระเบื้อง 1024 จะเพิ่ม 1024 คะแนน การเชื่อมโยงการรวมหลายครั้งในการเคลื่อนที่เดียวจะบวกทั้งหมดเข้าด้วยกัน",
    "t2k_htp_scoring_p2": 'ในปริศนาประจำวัน คะแนนสุดท้าย จำนวนการเคลื่อนที่ และเวลาจะถูกบันทึกและส่งไปยัง <a href="/other/2048/leaderboard">กระดานผู้นำ</a> กระดานผู้นำจัดอันดับตามคะแนนก่อน (สูงกว่าดีกว่า) แล้วตามเวลา (ต่ำกว่าดีกว่า)',
    "t2k_htp_strategy_h2": "กลยุทธ์พื้นฐาน",
    "t2k_htp_strategy_p1": "<strong>เลือกมุมและยึดมั่น</strong> เลือกมุมหนึ่ง — โดยปกติเป็นมุมล่าง — และเก็บกระเบื้องที่มีค่าสูงสุดไว้ที่นั่น สร้างโซ่กระเบื้องที่ลดลงตามขอบที่ออกไปจากมัน เพื่อให้การรวมแต่ละครั้งไหลไปสู่ครั้งต่อไปโดยธรรมชาติ",
    "t2k_htp_strategy_p2": "<strong>อย่าเลื่อนออกจากมุมยึดของคุณ</strong> หลีกเลี่ยงการเคลื่อนที่ที่ดึงกระเบื้องที่ใหญ่ที่สุดออกจากมุม ตัวอย่างเช่น ถ้ากระเบื้องที่สูงสุดอยู่ที่มุมล่างซ้าย หลีกเลี่ยงการเลื่อนขึ้นเว้นแต่จำเป็นอย่างยิ่ง การสูญเสียการควบคุมมุมคือสาเหตุที่เกมส่วนใหญ่จบ",
    "t2k_htp_strategy_p3": "<strong>เก็บแถวบนสุดให้เต็ม</strong> เมื่อมีโซ่ตลอดขอบบนหรือล่าง พยายามเก็บแถวนั้นให้เต็มตลอดเวลา สิ่งนี้บังคับให้กระเบื้องใหม่ปรากฏในที่อื่นและรักษาโซ่ของคุณ",
    "t2k_htp_strategy_p4": "<strong>คิดล่วงหน้า</strong> ก่อนแต่ละการเคลื่อนที่ พิจารณาว่ากระเบื้องใหม่อาจปรากฏที่ไหนและจะรบกวนการจัดเรียงของคุณหรือไม่ การเคลื่อนที่ที่ทิ้งกระดานไว้ในสภาพที่ไม่สามารถกู้คืนได้มักเป็นสัญญาณว่าคุณเคลื่อนที่โดยไม่คิด",
    "t2k_htp_tiles_h2": "ค่ากระเบื้อง",
    "t2k_htp_tiles_p1": "กระเบื้องเริ่มต้นเป็น 2 หรือ 4 เสมอ — มีโอกาส 90% ของ 2 และ 10% ของ 4 กระเบื้องใหม่ปรากฏแบบสุ่มในเซลล์ว่างหลังแต่ละการเคลื่อนที่ ลำดับค่าเพิ่มเป็นสองเท่าด้วยการรวมแต่ละครั้ง: 2 → 4 → 8 → 16 → 32 → 64 → 128 → 256 → 512 → 1024 → 2048 และอื่นๆ",
    "t2k_htp_tiles_p2": "เฉพาะกระเบื้องที่มีค่าเท่ากันเท่านั้นที่สามารถรวมกันได้ และกระเบื้องแต่ละชิ้นสามารถรวมได้สูงสุดครั้งเดียวต่อการเคลื่อนที่",
    "t2k_htp_title": "วิธีเล่น 2048 | minesweeper.org",
    "t2k_keep_going": "เล่นต่อ",
    "t2k_score": "คะแนน:",
    "t2k_solved": "คุณถึง 2048 แล้ว!",
}

insert_t2k.LANGS["pgl"] = {
    "t2k_game_over": "😥 Amegay Overway",
    "t2k_htp_back": "← Ayplay Odaytay's Uzzlepay",
    "t2k_htp_controls_desktop_li1": "<strong>Arrowway eyskay</strong> orway <strong>W A S D</strong> — ideslway allway ilestay inway atthay irectionday.",
    "t2k_htp_controls_desktop_li2": "Everyway eypresskay isway oneway ovemay, evenway ifway onlyway oneway iletay iftsshay.",
    "t2k_htp_controls_footer": "Useway ethay <strong>Ewnay Amegay</strong> uttonbay otay esetray ethay oardbay andway artstay overway atway anyway imetay.",
    "t2k_htp_controls_h2": "Ontrolscay",
    "t2k_htp_controls_mobile_li1": "<strong>Wipesay</strong> upway, ownday, eftlay, orway ightray otay ideslway allway ilestay inway atthay irectionday.",
    "t2k_htp_controls_mobile_li2": "Eachway wipesay isway oneway ovemay, evenway ifway onlyway oneway iletay iftsshay.",
    "t2k_htp_daily_h2": "Ailyday Uzzlepay",
    "t2k_htp_daily_p1": "Eachway ayday away ewnay uzzlepay isway eededsay — ethay amesay artingstay oardbay orfay everyway ayerplay aroundway ethay orldway. Ethay uzzlepay esetsray atway idnightmay UTC. Everyoneway ayingplay ethay ailyday uzzlepay onway away ivenGay ayday artsstay omfray anway identicalway iletay ayoutlay, akingmay itway away airfay ead-to-headhay ompetitioncay.",
    "t2k_htp_daily_p2": 'Afterway ompletingcay ethay ailyday uzzlepay ouyay ancay ubmitsay ouryay orescsay otay ethay <a href="/other/2048/leaderboard">2048 eaderboardlay</a>. Ouyay eednay otay ebay ignedsay inway otay ubmitsay.',
    "t2k_htp_desc": "Earnlay owhay otay ayplay 2048 — ethay assicclway iletay-ergingmay uzzlepay. Understandway ethay ulesray, ontrolscay, oringscsay, andway ategystray otay eachray ethay 2048 iletay.",
    "t2k_htp_goal_h2": "Ethay Oalway",
    "t2k_htp_goal_p1": "Ideslway ilestay onway ethay idgray otay ergemay identicalway umbersnay. Enthway otway ilestay ithway ethay amesay aluevay ollidecay eythay ombinecay intoway away inglesay iletay orthway wiceday ethay aluevay — away 2 andway away 2 ecomebay away 4, otway 4s ecomebay anway 8, andway osay onway. Ethay oalway isway otay uildbay away iletay atthay eachesray <strong>2048</strong>.",
    "t2k_htp_goal_p2": "Ouyay ancay eepkay ayingplay afterway eachingray 2048 otay ushpay ouryay orescsay igherhay. Ethay amegay endsway enthway onay ovesmay emainray — ethay idgray isway ullfay andway onay adjacentway ilestay areshay ethay amesay aluevay.",
    "t2k_htp_intro": "2048 isway away idingsley iletay uzzlepay ayedplay onway away 4x4 idgray. Ombinecay atchingmay umberednay ilestay ybay idingsley emthay inway ourfay irectiondsay. Everyway ovemay away ewnay iletay appearsway. Eachray ethay 2048 iletay otay inway — orway eepkay oinggay orfay away igherhay orescsay.",
    "t2k_htp_scoring_h2": "Oringscsay",
    "t2k_htp_scoring_p1": "Eachway ergemay addsway ethay aluevay ofway ethay ewnay ombinedcay iletay otay ouryay orescsay. Ergingmay otway 512 ilestay intoway away 1024 iletay addsway 1024 ointspay. Ainingchay everalsay ergesway inway oneway ovemay addsway allway ofway emthay ogethertay.",
    "t2k_htp_scoring_p2": 'Onway ethay ailyday uzzlepay, ouryay inalfay orescsay, ovemay ountcay, andway imetay arehay ecordedray andway ubmittedsay otay ethay <a href="/other/2048/leaderboard">eaderboardlay</a>. Ethay eaderboardlay anksray irstfay ybay orescsay (igherhay isway etterbay), enthway ybay imetay (owerlay isway etterbay).',
    "t2k_htp_strategy_h2": "Asicbay Ategystray",
    "t2k_htp_strategy_p1": "<strong>Ickpay away ornercay andway ommitcay otay itway.</strong> Oosechay oneway ornercay — usuallyyway away ottombay ornercay — andway eepkay ouryay ighest-valuehay iletay erethay. Uildbay away escendingday ainchay ofway ilestay alongway ethay edgeway eadingleay awayway omfray itway osay atthay everyway ergemay aturallynay eedsway intoway ethay extnay.",
    "t2k_htp_strategy_p2": "<strong>Evernay ideslway awayway omfray ouryay anchornay ornercay.</strong> Avoidway ovesmay atthay ullpay ouryay argestlay iletay awayway omfray itsway ornercay. Orfay exampleway, ifway ouryay ighesthay iletay isway inway ethay ottom-leftbay, avoidway wipingsay upway unlessway itway isway absolutelyway ecessarynay. Osinglay ontrolcay ofway ethay ornercay isway owhay ostmay amesgay endway.",
    "t2k_htp_strategy_p3": "<strong>Eepkay ethay optay owray ullfay.</strong> Onceway ouyay avehay away ainchay acrossway ethay optay orway ottombay edgeway, ytray otay eepkay atthay owray ullfay atway allway imestay. Isthay orcesway ewnay ilestay otay appearway elsewhereway andway reservespay ouryay ainchay.",
    "t2k_htp_strategy_p4": "<strong>Inkthay aheadway.</strong> Eforebay eachway ovemay, onsidercay erethwhay ethay ewnay iletay ightmay appearway andway etherwhay itway illway isruptday ouryay ayoutlay. Ovesmay atthay eavelway ethay oardbay inway anway unrecoverableway atesstay arehay usuallyyway away ignsay atthay ouyay ovedmay ithoutway inkingthay.",
    "t2k_htp_tiles_h2": "Iletay Aluesvay",
    "t2k_htp_tiles_p1": "Ilestay alwaysway artstay asway 2 orway 4 — erethay isway away 90% ancechay ofway away 2 andway away 10% ancechay ofway away 4. Ewnay ilestay appearway andomlyray inway anway emptyyway ellcay afterway everyway ovemay. Ethay equencesay ofway aluesvay oublesday ithway eachway ergemay: 2 -> 4 -> 8 -> 16 -> 32 -> 64 -> 128 -> 256 -> 512 -> 1024 -> 2048 andway eyondbay.",
    "t2k_htp_tiles_p2": "Onlyway ilestay ithway ethay amesay aluevay ancay ergemay, andway eachway iletay ancay ergemay atmostway onceway erpay ovemay.",
    "t2k_htp_title": "Owhay otay Ayplay 2048 | minesweeper.org",
    "t2k_keep_going": "Eepkay Oinggay",
    "t2k_score": "Orescsay:",
    "t2k_solved": "Ouyay eachedray 2048!",
}

if __name__ == "__main__":
    for lang in ["pl", "tl", "th", "pgl"]:
        insert_t2k.insert_lang(lang)
