# -*- coding: utf-8 -*-
"""nn_* batch 4: tl, th, pgl"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_nn

insert_nn.LANGS["tl"] = {
    "nn_bridge": "Nagsusugal ang Minesweeper sa Nonogram — gamitin ang mga pahiwatig ng hilera at kolumna para mahanap ang mga mina.",
    "nn_btn_daily": "📅 Araw-araw",
    "nn_btn_new_random": "🎲 Bagong Random",
    "nn_btn_random": "🎲 Random",
    "nn_btn_retry": "🔄 Subukang Muli",
    "nn_label_potd": "📅 Palaisipan ng Araw",
    "nn_overlay_solved": "🎉 Nalutas!",
    "nn_save_score": "I-save ang Iskor",
    "nn_lb_today": "🏆 Pinakamahusay na Oras Ngayon",
    "nn_instructions": "<strong>Kaliwang-click</strong> para ihayag — <em>ang pag-click sa mina ay nagtatapos ng laro!</em> &nbsp;|&nbsp; <strong>Kanang-click</strong> para mag-cycle: bandila 💣 &rarr; hindi sigurado ? &rarr; nakatago. &nbsp;|&nbsp; <strong>Manalo</strong> sa pamamagitan ng paghahayag ng bawat ligtas na cell.",
    "nn_what_h2": "Ano ang Nonosweeper?",
    "nn_what_p1": "Ang Nonosweeper ay isang hybrid na palaisipan na pinagsama ang dalawang minamahal na format ng palaisipan: ang tensyon ng paglilinis ng mina ng <strong>Minesweeper</strong> at ang lohika ng grid-deduction ng isang <strong>Nonogram</strong> (kilala rin bilang Picross o Griddler). Hindi tulad ng karaniwang Minesweeper, hindi ka kailanman mag-click nang bulag para ihayag ang mga numero — sa halip, ang buong hanay ng mga pahiwatig ng hilera at kolumna ay nakikita mula sa simula, tulad ng sa isang nonogram. Ang iyong trabaho ay gamitin ang mga pahiwatig na iyon para malaman kung aling mga cell ang nagtatago ng mga mina, pagkatapos ay i-click ang mga ligtas na cell para ihayag ang mga ito.",
    "nn_what_p2": "Ang elemento ng Minesweeper ay nagpapanatiling mataas ang mga stake: isang maling pag-click sa isang mina at ang palaisipan ay agad na nagtatapos. Walang ligtas na unang pag-click at walang pinapayagang random na paghula — ang bawat galaw ay dapat na hinuha mula sa mga pahiwatig.",
    "nn_clues_h2": "Paano basahin ang mga pahiwatig",
    "nn_clues_p1": "Ang bawat hilera at kolumna ay may pahiwatig na binubuo ng isa o higit pang mga numero. Ang bawat numero ay kumakatawan sa isang <strong>sunud-sunod na grupo ng mga mina</strong> sa hilera o kolumnang iyon. Ang mga grupo ay lumalabas nang magkakasunod (kaliwa-pakanan para sa mga hilera, taas-pababa para sa mga kolumna) at pinaghihiwalay ng hindi bababa sa isang ligtas na cell.",
    "nn_clues_p2": 'Halimbawa, ang pahiwatig ng hilera na <strong>3 &nbsp;1 &nbsp;2</strong> ay nangangahulugang: tatlong mina nang sunud-sunod, puwang, isang mina, puwang, pagkatapos ay dalawang mina nang sunud-sunod. Ang pahiwatig na <strong>—</strong> ay nangangahulugang walang mina sa hilera o kolumnang iyon.',
    "nn_diff_h2": "Mga antas ng kahirapan",
    "nn_diff_beginner": "Nagsisimula (8×8)",
    "nn_diff_intermediate": "Intermediate (10×10)",
    "nn_diff_expert": "Expert (15×15)",
    "nn_diff_li1": "<strong>Nagsisimula (8×8, 16 mina):</strong> Isang kompaktong grid na may maikling mga pahiwatig. Maganda para matutunan ang mekanika.",
    "nn_diff_li2": "<strong>Intermediate (10×10, 35 mina):</strong> Mas maraming cell at mas makapal na mga grupo ang nangangailangan ng maingat na cross-referencing.",
    "nn_diff_li3": "<strong>Expert (15×15, 75 mina):</strong> Isang malaking grid na may kumplikadong multi-grupo na mga pahiwatig — isang seryosong hamon sa nonogram.",
    "nn_strat_h2": "Mga tip sa estratehiya",
    "nn_strat_li1": "<strong>Magsimula sa mga hilera/kolumna na may zero na pahiwatig.</strong> Ang pahiwatig na '—' ay nangangahulugang ang bawat cell sa linya ay ligtas — ihayag ang lahat ng libre.",
    "nn_strat_li2": "<strong>Gamitin ang pagsusuri ng overlap.</strong> Kung ang isang grupo ay malaki sapat na kaya kailangan itong mag-overlap sa sarili nito sa bawat valid na paglalagay, ang mga overlapping na cell ay tiyak na mga mina.",
    "nn_strat_li3": "<strong>Cross-reference ang mga hilera at kolumna.</strong> Ang pahiwatig ng hilera at pahiwatig ng kolumna ng isang cell ay madalas na magkasamang nililimitahan ang estado nito nang buo.",
    "nn_strat_li4": "<strong>Mag-flag ng mga mina bago ihayag.</strong> Kapag sigurado kang ang isang cell ay mina, i-flag ito bago mag-click ng kalapit na mga ligtas na cell — pinapanatili nitong tumpak ang counter ng mina at nababasa ang board.",
    "nn_about_h2": "Tungkol sa Nonosweeper",
}

insert_nn.LANGS["th"] = {
    "nn_bridge": "Minesweeper พบกับ Nonogram — ใช้เบาะแสแถวและคอลัมน์เพื่อหาระเบิด",
    "nn_btn_daily": "📅 ประจำวัน",
    "nn_btn_new_random": "🎲 สุ่มใหม่",
    "nn_btn_random": "🎲 สุ่ม",
    "nn_btn_retry": "🔄 ลองใหม่",
    "nn_label_potd": "📅 ปริศนาแห่งวัน",
    "nn_overlay_solved": "🎉 แก้สำเร็จ!",
    "nn_save_score": "บันทึกคะแนน",
    "nn_lb_today": "🏆 เวลาที่ดีที่สุดวันนี้",
    "nn_instructions": "<strong>คลิกซ้าย</strong>เพื่อเปิดเผย — <em>คลิกระเบิดจะจบเกม!</em> &nbsp;|&nbsp; <strong>คลิกขวา</strong>เพื่อสลับ: ปักธง 💣 &rarr; ไม่แน่ใจ ? &rarr; ซ่อน &nbsp;|&nbsp; <strong>ชนะ</strong>โดยเปิดเผยทุกเซลล์ที่ปลอดภัย",
    "nn_what_h2": "Nonosweeper คืออะไร?",
    "nn_what_p1": "Nonosweeper เป็นเกมปริศนาผสมผสานระหว่างสองรูปแบบที่โปรดปราน: ความตึงเครียดในการกวาดล้างระเบิดของ <strong>Minesweeper</strong> และตรรกะการหาเหตุผลจากตารางของ <strong>Nonogram</strong> (รู้จักในชื่อ Picross หรือ Griddler) ต่างจาก Minesweeper มาตรฐาน คุณไม่ต้องคลิกแบบมั่วเพื่อเปิดตัวเลข — แต่เบาะแสทั้งหมดของแถวและคอลัมน์จะปรากฏตั้งแต่เริ่มต้นเหมือนกับ Nonogram หน้าที่ของคุณคือใช้เบาะแสเหล่านั้นเพื่อระบุว่าเซลล์ใดซ่อนระเบิด แล้วคลิกเซลล์ที่ปลอดภัยเพื่อเปิดเผย",
    "nn_what_p2": "องค์ประกอบ Minesweeper ทำให้เกมมีความเสี่ยงสูง: คลิกผิดไปโดนระเบิดครั้งเดียวและปริศนาจบทันที ไม่มีการคลิกแรกที่ปลอดภัยและไม่อนุญาตให้เดาสุ่ม — ทุกการเคลื่อนที่ต้องหาเหตุผลจากเบาะแส",
    "nn_clues_h2": "วิธีอ่านเบาะแส",
    "nn_clues_p1": "แต่ละแถวและคอลัมน์มีเบาะแสที่ประกอบด้วยตัวเลขหนึ่งหรือมากกว่า แต่ละตัวเลขแทน<strong>กลุ่มระเบิดต่อเนื่อง</strong>ในแถวหรือคอลัมน์นั้น กลุ่มจะปรากฏตามลำดับ (ซ้ายไปขวาสำหรับแถว บนลงล่างสำหรับคอลัมน์) และคั่นด้วยเซลล์ที่ปลอดภัยอย่างน้อยหนึ่งเซลล์",
    "nn_clues_p2": 'ตัวอย่างเช่น เบาะแสแถว <strong>3 &nbsp;1 &nbsp;2</strong> หมายความว่า: ระเบิด 3 ตัวติดกัน ช่องว่าง ระเบิด 1 ตัว ช่องว่าง แล้วระเบิด 2 ตัวติดกัน เบาะแส <strong>—</strong> หมายความว่าไม่มีระเบิดในแถวหรือคอลัมน์นั้นเลย',
    "nn_diff_h2": "ระดับความยาก",
    "nn_diff_beginner": "มือใหม่ (8×8)",
    "nn_diff_intermediate": "ระดับกลาง (10×10)",
    "nn_diff_expert": "ผู้เชี่ยวชาญ (15×15)",
    "nn_diff_li1": "<strong>มือใหม่ (8×8, 16 ระเบิด):</strong> ตารางขนาดกะทัดรัดพร้อมเบาะแสสั้น เหมาะสำหรับเรียนรู้กลไก",
    "nn_diff_li2": "<strong>ระดับกลาง (10×10, 35 ระเบิด):</strong> เซลล์มากขึ้นและกลุ่มที่หนาแน่นกว่าต้องการการอ้างอิงไขว้อย่างระมัดระวัง",
    "nn_diff_li3": "<strong>ผู้เชี่ยวชาญ (15×15, 75 ระเบิด):</strong> ตารางขนาดใหญ่พร้อมเบาะแสหลายกลุ่มที่ซับซ้อน — ความท้าทาย Nonogram ระดับจริงจัง",
    "nn_strat_h2": "เคล็ดลับกลยุทธ์",
    "nn_strat_li1": "<strong>เริ่มต้นด้วยแถว/คอลัมน์ที่มีเบาะแสเป็นศูนย์</strong> เบาะแส '—' หมายความว่าทุกเซลล์ในแถวนั้นปลอดภัย — เปิดเผยทั้งหมดได้ฟรี",
    "nn_strat_li2": "<strong>ใช้การวิเคราะห์การทับซ้อน</strong> หากกลุ่มใหญ่พอที่จะทับซ้อนตัวเองในทุกการวางที่ถูกต้อง เซลล์ที่ทับซ้อนนั้นเป็นระเบิดอย่างแน่นอน",
    "nn_strat_li3": "<strong>อ้างอิงไขว้แถวและคอลัมน์</strong> เบาะแสแถวและคอลัมน์ของเซลล์ร่วมกันมักจะจำกัดสถานะได้อย่างสมบูรณ์",
    "nn_strat_li4": "<strong>ปักธงระเบิดก่อนเปิดเผย</strong> เมื่อมั่นใจว่าเซลล์คือระเบิด ให้ปักธงก่อนคลิกเซลล์ที่ปลอดภัยที่อยู่ติดกัน — รักษาตัวนับระเบิดให้แม่นยำและกระดานอ่านง่าย",
    "nn_about_h2": "เกี่ยวกับ Nonosweeper",
}

insert_nn.LANGS["pgl"] = {
    "nn_bridge": "Inesweepermay eetsmay Ononogramay — useway owray andway olumncay uesclays otay indfay ethay inesmay.",
    "nn_btn_daily": "📅 Ailyday",
    "nn_btn_new_random": "🎲 Ewnay Andomray",
    "nn_btn_random": "🎲 Andomray",
    "nn_btn_retry": "🔄 Etryray",
    "nn_label_potd": "📅 Uzzlepay ofway ethay Ayday",
    "nn_overlay_solved": "🎉 Olvedsay!",
    "nn_save_score": "Avesay Orescsay",
    "nn_lb_today": "🏆 Odaytay's Estbay Imestay",
    "nn_instructions": "<strong>Eftlay-icklay</strong> otay evealray — <em>ickingclay away inemay endsway ethay amegay!</em> &nbsp;|&nbsp; <strong>Ightray-icklay</strong> otay yclecay: agflay 💣 &rarr; uncertainway ? &rarr; iddenhay. &nbsp;|&nbsp; <strong>Inway</strong> ybay evealingray everyway afesay ellcay.",
    "nn_what_h2": "Hatway isway Onosweepernay?",
    "nn_what_p1": "Onosweepernay isway away ybridhay uzzlepay atthay usesfay otway elovedBay uzzlepay ormatsfay: ethay inemay-earingclay ensiontay ofway <strong>Inesweepermay</strong> andway ethay idgray-eductiondway ogiclay ofway away <strong>Ononogramay</strong> (alsoways ownknay asway Icrosspay orway Iddlergrway). Unlikeways andardsay Inesweepermay, ouyay evernay icklay indlyblay otay evealray umbersnay — insteadway, ethay ullfay etsay ofway owray andway olumncay uesclays isway isibleway omfray ethay eryvay artstay, ustjay asway inway away ononogramway. Ouryay objay isway otay useway osethay uesclays otay orkway outway exactlyway ichwhay ellscay idehay inesmay, enthway icklay ethay afesay ellscay otay evealray emthay.",
    "nn_what_p2": "Ethay Inesweepermay elementway eepskay ethay akesstay ighhay: oneway ongwray icklay onway away inemay andway ethay uzzlepay endsway immediatelyway. Erethay isway onay afesay irstfay icklay andway onay andomray uessing-gay allowedway — everyway ovemay ustmay ebay educed-day omfray ethay uesclays.",
    "nn_clues_h2": "Owhay otay Eadray ethay Uesclays",
    "nn_clues_p1": "Eachway owray andway olumncay ashay away ueclway ademay upway ofway oneway orway oremay umbersnay. Eachway umbernay epresentsray away <strong>onsecutivecay unray ofway inesmay</strong> inway atthay owray orway olumncay. Ethay unsray appearway inway orderway (eft-to-rightlay orfay owsray, op-to-bottomtay orfay olumnscay) andway arehay eparatedsay ybay atleastway oneway afesay ellcay.",
    "nn_clues_p2": 'Orfay exampleway, away owray ueclway ofway <strong>3 &nbsp;1 &nbsp;2</strong> eansmay: eethray inesmay inway away owray, away apgay, oneway inemay, away apgay, enthway otway inesmay inway away owray. Away ueclway ofway <strong>—</strong> eansmay onay inesmay atall-ay inway atthay owray orway olumncay.',
    "nn_diff_h2": "Ifficultyday Evelslay",
    "nn_diff_beginner": "Eginnerbay (8x8)",
    "nn_diff_intermediate": "Intermediateway (10x10)",
    "nn_diff_expert": "Expertway (15x15)",
    "nn_diff_li1": "<strong>Eginnerbay (8x8, 16 inesmay):</strong> Away ompactcay idgray ithway ortshay uesclays. Oodgay orfay earninglay ethay echanicmay.",
    "nn_diff_li2": "<strong>Intermediateway (10x10, 35 inesmay):</strong> Oremay ellscay andway enserdway unsray equireray arefulcay oss-referencingcray.",
    "nn_diff_li3": "<strong>Expertway (15x15, 75 inesmay):</strong> Away argelay idgray ithway omplexcay ulti-runmay uesclays — away erioussay ononogramway allengehcay.",
    "nn_strat_h2": "Ategystray Ipstay",
    "nn_strat_li1": "<strong>Artstay ithway ero-cuezay owsray/olumnscay.</strong> Away '—' ueclway eansmay everyway ellcay inway atthay inelway isway afesay — evealray emthay allway orfay eefray.",
    "nn_strat_li2": "<strong>Useway overlapway analysisway.</strong> Ifway away unray isway argelay enoughway atthay itway ustmay overlapway itselfway inway everyway alidvay acementplay, osethay overlappingway ellscay arehay efinitelyday inesmay.",
    "nn_strat_li3": "<strong>Oss-referencecray owsray andway olumnscay.</strong> Away ellcay's owray ueclway andway olumncay ueclway ogethertay oftenway arrownay ownday itsway atesstay ompletelycay.",
    "nn_strat_li4": "<strong>Agflay inesmay eforebay evealingray.</strong> Onceway ouyay arehay ertaincay away ellcay isway away inemay, agflay itway eforebay ickingclay adjacentway afesay ellscay — itway eepskay ethay inemay ountercay accurateway andway ethay oardbay eadableray.",
    "nn_about_h2": "Aboutway Onosweepernay",
}

if __name__ == "__main__":
    for lang in ["tl", "th", "pgl"]:
        insert_nn.insert_lang(lang)
