# -*- coding: utf-8 -*-
"""mj_* batch 4: pl, tl, th, pgl"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_mj

insert_mj.LANGS["pl"] = {
    "mj_hint_free": "Pokaz wolne plytki",
    "mj_hint_match": "Pokaz pasujace pary",
    "mj_htp_back": "Graj w dzisiejsza zagadke",
    "mj_htp_controls_h2": "Sterowanie",
    "mj_htp_controls_li1": "<strong>Kliknij wolna plytke</strong>, aby ja wybrac (podswietlona na zloto).",
    "mj_htp_controls_li2": "<strong>Kliknij druga wolna plytke</strong> tego samego typu, aby usunac pare.",
    "mj_htp_controls_li3": "<strong>Kliknij ponownie wybrana plytke</strong>, aby anulowac wybor.",
    "mj_htp_controls_li4": "<strong>Cofnij</strong> cofa jedna dopasowana pare na raz.",
    "mj_htp_daily_h2": "Codzienna zagadka",
    "mj_htp_daily_p": "Kazdy dzien generuje nowa plansze na podstawie dzisiejszej daty — ta sama plansze dla kazdego gracza na swiecie. Timer startuje przy kliknieciu pierwszej plytki. Ukon plansze, aby wyslac swoj czas do tabeli wynikow.",
    "mj_htp_desc": "Poznaj zasady Mahjong Solitaire — dopasowuj pary wolnych plytek, uzywaj wskazowek i oprozniaj plansze Zolwia.",
    "mj_htp_free_h2": "Co to jest wolna plytka?",
    "mj_htp_free_p": "Plytka jest <strong>wolna</strong>, gdy spelniaja sie dwa warunki: (1) zadna plytka nie jest na niej ułozona, i (2) jest otwarta po lewej <em>lub</em> prawej stronie — tzn. brak sasiednich plytek na tej samej warstwie co najmniej z jednej strony.",
    "mj_htp_goal_h2": "Cel gry",
    "mj_htp_goal_p": "Usun wszystkie 144 plytki z planszy, wybierajac pasujace pary. Obie plytki w parze musza byc <strong>wolne</strong>. Gra jest wygrana, gdy plansza jest pusta.",
    "mj_htp_hints_h2": "Przyciski wskazowek",
    "mj_htp_hints_p": "<strong>Pokaz wolne plytki</strong> podswietla na niebiesko wszystkie aktualnie dostepne plytki. <strong>Pokaz pasujace pary</strong> podswietla na zielono wolne plytki, ktore maja co najmniej jednego pasujacego wolnego partnera.",
    "mj_htp_intro": "Mahjong Solitaire to jednoosobowa gra dopasowywania plytek. 144 plytki ulozone sa w klasyczny ksztalt Zolwia. Twoim celem jest usuniecie wszystkich plytek przez dopasowywanie identycznych wolnych par.",
    "mj_htp_refs_h2": "Zrodla",
    "mj_htp_refs_p": 'Ta implementacja jest oparta na projekcie open-source <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a> autorstwa ffalt. Dowiedz sie wiecej o grze na <a href="https://pl.wikipedia.org/wiki/Mahjong_solitaire" target="_blank" rel="noopener noreferrer">Wikipedii</a>.',
    "mj_htp_tiles_h2": "Typy plytek &amp; dopasowywanie",
    "mj_htp_tiles_p": "Pelny zestaw uzywa 144 plytek: dziewiec Kol (1–9), dziewiec Bambusow (1–9), dziewiec Znakow (1–9), cztery Wiatry (Wschod, Poludnie, Zachod, Polnoc), trzy Smoki (Czerwony, Zielony, Bialy), cztery Pory roku i cztery Kwiaty. Wiekszosc plytek pasuje tylko do identycznych par. <strong>Wyjatek:</strong> dowolne dwie plytki Por roku pasuja do siebie, a dowolne dwie plytki Kwiatow rowniez pasuja do siebie.",
    "mj_htp_title": "Jak grac w Mahjong Solitaire | minesweeper.org",
    "mj_lb_all_heading": "W sumie",
    "mj_lb_season_heading": "W tym miesiacu",
    "mj_lb_tab_all": "W sumie",
    "mj_lb_tab_daily": "Dzis",
    "mj_lb_tab_season": "W tym miesiacu",
    "mj_name_label": "Nazwa",
    "mj_new_game": "Nowa gra",
    "mj_play_today": "Graj dzisiaj",
    "mj_removed_pairs": "Usuniete pary",
    "mj_same_for_all": "Ta sama plansza dla wszystkich · Resetuje sie o polnocy UTC",
    "mj_solved": "🎉 Rozwiazano!",
    "mj_submit_btn": "Wyslij wynik",
    "mj_submit_score": "Wyslij swoj wynik",
    "mj_time": "Czas:",
    "mj_today_heading": "Dzis — ",
    "mj_undo": "Cofnij",
}

insert_mj.LANGS["tl"] = {
    "mj_hint_free": "Ipakita ang mga libreng tile",
    "mj_hint_match": "Ipakita ang mga tugma",
    "mj_htp_back": "Laruin ang puzzle ngayon",
    "mj_htp_controls_h2": "Mga kontrol",
    "mj_htp_controls_li1": "<strong>I-click ang isang libreng tile</strong> upang piliin ito (naka-highlight sa ginto).",
    "mj_htp_controls_li2": "<strong>I-click ang pangalawang libreng tile</strong> ng parehong uri upang alisin ang pares.",
    "mj_htp_controls_li3": "<strong>I-click muli ang napiling tile</strong> upang i-deselect ito.",
    "mj_htp_controls_li4": "<strong>I-undo</strong> ang isang nagtugmang pares nang paisa-isa.",
    "mj_htp_daily_h2": "Araw-araw na palaisipan",
    "mj_htp_daily_p": "Bawat araw ay may bagong board na nabuo mula sa petsa ngayon — parehong board para sa bawat manlalaro sa buong mundo. Nagsisimula ang timer kapag na-click mo ang iyong unang tile. Kumpletuhin ang board upang isumite ang iyong oras sa leaderboard.",
    "mj_htp_desc": "Alamin ang mga patakaran ng Mahjong Solitaire — itugma ang mga libreng tile pair, gumamit ng mga hint, at linisin ang Turtle board.",
    "mj_htp_free_h2": "Ano ang libreng tile?",
    "mj_htp_free_p": "Ang isang tile ay <strong>libre</strong> kapag natutugunan ang dalawang kondisyon: (1) walang tile na nakasalansan sa ibabaw nito, at (2) ito ay bukas sa kaliwa <em>o</em> kanang bahagi — ibig sabihin, walang katabing tile sa parehong layer sa kahit isang panig.",
    "mj_htp_goal_h2": "Ang layunin",
    "mj_htp_goal_p": "Alisin ang lahat ng 144 tile mula sa board sa pamamagitan ng pagpili ng mga katugmang pares. Ang parehong mga tile sa isang pares ay dapat na <strong>libre</strong>. Ang laro ay nananalo kapag ang board ay walang laman.",
    "mj_htp_hints_h2": "Mga button ng hint",
    "mj_htp_hints_p": "<strong>Ipakita ang mga libreng tile</strong> ay nag-highlight ng asul sa lahat ng kasalukuyang naa-access na mga tile. <strong>Ipakita ang mga tugma</strong> ay nag-highlight ng berde sa mga libreng tile na may kahit isang katugmang libreng kasosyo.",
    "mj_htp_intro": "Ang Mahjong Solitaire ay isang one-player tile-matching na laro. Ang 144 tile ay nakahanay sa klasikong Turtle na pormasyon. Ang iyong layunin ay alisin ang lahat ng tile sa pamamagitan ng pagtutugma ng magkaparehong libreng pares.",
    "mj_htp_refs_h2": "Mga sanggunian",
    "mj_htp_refs_p": 'Ang implementasyong ito ay batay sa open-source na proyekto <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a> ni ffalt. Matuto nang higit pa tungkol sa laro sa <a href="https://en.wikipedia.org/wiki/Mahjong_solitaire" target="_blank" rel="noopener noreferrer">Wikipedia</a>.',
    "mj_htp_tiles_h2": "Mga uri ng tile &amp; pagtutugma",
    "mj_htp_tiles_p": "Ang buong set ay gumagamit ng 144 tile: siyam na Bilog (1–9), siyam na Kawayan (1–9), siyam na Character (1–9), apat na Hangin (Silangan, Timog, Kanluran, Hilaga), tatlong Dragon (Pula, Berde, Puti), apat na Panahon, at apat na Bulaklak. Karamihan sa mga tile ay tumutugma lamang sa magkaparehong pares. <strong>Pagbubukod:</strong> anumang dalawang tile ng Panahon ay tumutugma sa isa't isa, at anumang dalawang tile ng Bulaklak ay tumutugma rin sa isa't isa.",
    "mj_htp_title": "Paano Maglaro ng Mahjong Solitaire | minesweeper.org",
    "mj_lb_all_heading": "Lahat ng oras",
    "mj_lb_season_heading": "Ngayong buwan",
    "mj_lb_tab_all": "Lahat ng oras",
    "mj_lb_tab_daily": "Ngayon",
    "mj_lb_tab_season": "Ngayong buwan",
    "mj_name_label": "Pangalan",
    "mj_new_game": "Bagong laro",
    "mj_play_today": "Laruin ngayon",
    "mj_removed_pairs": "Mga inalis na pares",
    "mj_same_for_all": "Parehong board para sa lahat · Nire-reset sa hatinggabi UTC",
    "mj_solved": "🎉 Nalutas!",
    "mj_submit_btn": "Isumite ang puntos",
    "mj_submit_score": "Isumite ang iyong puntos",
    "mj_time": "Oras:",
    "mj_today_heading": "Ngayon — ",
    "mj_undo": "I-undo",
}

insert_mj.LANGS["th"] = {
    "mj_hint_free": "แสดงกระเบื้องที่ว่าง",
    "mj_hint_match": "แสดงคู่ที่จับคู่ได้",
    "mj_htp_back": "เล่นปริศนาวันนี้",
    "mj_htp_controls_h2": "วิธีควบคุม",
    "mj_htp_controls_li1": "<strong>คลิกกระเบื้องที่ว่าง</strong>เพื่อเลือก (ไฮไลต์ด้วยสีทอง)",
    "mj_htp_controls_li2": "<strong>คลิกกระเบื้องที่ว่างชิ้นที่สอง</strong>ประเภทเดียวกันเพื่อลบคู่",
    "mj_htp_controls_li3": "<strong>คลิกกระเบื้องที่เลือกอีกครั้ง</strong>เพื่อยกเลิกการเลือก",
    "mj_htp_controls_li4": "<strong>เลิกทำ</strong>ย้อนกลับครั้งละหนึ่งคู่",
    "mj_htp_daily_h2": "ปริศนาประจำวัน",
    "mj_htp_daily_p": "ทุกวันจะสร้างกระดานใหม่จากวันที่ปัจจุบัน — กระดานเดียวกันสำหรับผู้เล่นทุกคนทั่วโลก ตัวจับเวลาจะเริ่มเมื่อคุณคลิกกระเบื้องแรก ทำกระดานให้สำเร็จเพื่อส่งเวลาของคุณไปยังกระดานผู้นำ",
    "mj_htp_desc": "เรียนรู้กฎของ Mahjong Solitaire — จับคู่กระเบื้องที่ว่าง ใช้คำใบ้ และทำกระดานเต่าให้ว่าง",
    "mj_htp_free_h2": "กระเบื้องที่ว่างคืออะไร?",
    "mj_htp_free_p": "กระเบื้องเป็น<strong>กระเบื้องที่ว่าง</strong>เมื่อตรงตามสองเงื่อนไข: (1) ไม่มีกระเบื้องวางซ้อนอยู่ด้านบน และ (2) เปิดทางด้านซ้าย<em>หรือ</em>ขวา — หมายความว่าไม่มีกระเบื้องอยู่ติดกันในชั้นเดียวกันอย่างน้อยหนึ่งด้าน",
    "mj_htp_goal_h2": "เป้าหมาย",
    "mj_htp_goal_p": "นำกระเบื้องทั้ง 144 ชิ้นออกจากกระดานโดยเลือกคู่ที่ตรงกัน กระเบื้องทั้งสองในคู่ต้อง<strong>ว่าง</strong> เกมชนะเมื่อกระดานว่างเปล่า",
    "mj_htp_hints_h2": "ปุ่มคำใบ้",
    "mj_htp_hints_p": "<strong>แสดงกระเบื้องที่ว่าง</strong>จะไฮไลต์กระเบื้องที่เข้าถึงได้ทั้งหมดด้วยสีน้ำเงิน <strong>แสดงคู่ที่จับคู่ได้</strong>จะไฮไลต์กระเบื้องที่ว่างซึ่งมีคู่ที่ว่างที่ตรงกันอย่างน้อยหนึ่งชิ้นด้วยสีเขียว",
    "mj_htp_intro": "Mahjong Solitaire เป็นเกมจับคู่กระเบื้องสำหรับผู้เล่นคนเดียว กระเบื้อง 144 ชิ้นวางซ้อนกันในรูปแบบเต่าแบบคลาสสิก เป้าหมายคือนำกระเบื้องทั้งหมดออกโดยจับคู่กระเบื้องที่ว่างที่เหมือนกัน",
    "mj_htp_refs_h2": "อ้างอิง",
    "mj_htp_refs_p": 'การใช้งานนี้อ้างอิงจากโครงการโอเพ่นซอร์ส <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a> โดย ffalt เรียนรู้เพิ่มเติมเกี่ยวกับเกมนี้ที่ <a href="https://en.wikipedia.org/wiki/Mahjong_solitaire" target="_blank" rel="noopener noreferrer">Wikipedia</a>',
    "mj_htp_tiles_h2": "ประเภทกระเบื้อง &amp; การจับคู่",
    "mj_htp_tiles_p": "ชุดเต็มใช้กระเบื้อง 144 ชิ้น: วงกลม 9 ชิ้น (1–9), ไม้ไผ่ 9 ชิ้น (1–9), ตัวอักษร 9 ชิ้น (1–9), ลม 4 ชิ้น (ตะวันออก ใต้ ตะวันตก เหนือ), มังกร 3 ชิ้น (แดง เขียว ขาว), ฤดูกาล 4 ชิ้น และดอกไม้ 4 ชิ้น กระเบื้องส่วนใหญ่จับคู่ได้เฉพาะกับคู่ที่เหมือนกัน <strong>ข้อยกเว้น:</strong> กระเบื้องฤดูกาลสองชิ้นใดก็ได้จับคู่กัน และกระเบื้องดอกไม้สองชิ้นใดก็ได้ก็จับคู่กัน",
    "mj_htp_title": "วิธีเล่น Mahjong Solitaire | minesweeper.org",
    "mj_lb_all_heading": "ตลอดเวลา",
    "mj_lb_season_heading": "เดือนนี้",
    "mj_lb_tab_all": "ตลอดเวลา",
    "mj_lb_tab_daily": "วันนี้",
    "mj_lb_tab_season": "เดือนนี้",
    "mj_name_label": "ชื่อ",
    "mj_new_game": "เกมใหม่",
    "mj_play_today": "เล่นวันนี้",
    "mj_removed_pairs": "คู่ที่ลบแล้ว",
    "mj_same_for_all": "กระดานเดียวกันสำหรับทุกคน · รีเซ็ตเที่ยงคืน UTC",
    "mj_solved": "🎉 แก้สำเร็จ!",
    "mj_submit_btn": "ส่งคะแนน",
    "mj_submit_score": "ส่งคะแนนของคุณ",
    "mj_time": "เวลา:",
    "mj_today_heading": "วันนี้ — ",
    "mj_undo": "เลิกทำ",
}

insert_mj.LANGS["pgl"] = {
    "mj_hint_free": "Owshay Eefray Ilestay",
    "mj_hint_match": "Owshay Atchesmay",
    "mj_htp_back": "Ayplay Odaytay's Uzzlepay",
    "mj_htp_controls_h2": "Ontrolscay",
    "mj_htp_controls_li1": "<strong>Icklay away eefray iletay</strong> otay electsay itway (ighlightedhay inway oldgay).",
    "mj_htp_controls_li2": "<strong>Icklay away econdsay eefray iletay</strong> ithway ethay amesay ypetay otay emoveray ethay airpay.",
    "mj_htp_controls_li3": "<strong>Icklay ethay electedsay iletay againway</strong> otay eselect-day itway.",
    "mj_htp_controls_li4": "<strong>Ndoway</strong> epsstay ackbay oneway atchedmay airpay atway away imetay.",
    "mj_htp_daily_h2": "Ailyday Uzzlepay",
    "mj_htp_daily_p": "Eachway ayday away ewnay oardbay isway eneratedgay omfray odaytay's ateday — ethay amesay oardbay orfay everyway ayerplay orldwideway. Ethay imertay artsstay enthway ouyay icklay ouryay irstfay iletay. Ompleteay ethay oardbay otay ubmitsay ouryay imetay otay ethay eaderboardlay.",
    "mj_htp_desc": "Earnlay ethay ulesray ofway Ahjongmay Olitairesay — atchmay eefray iletay airspay, useway intshay, andway learcay ethay Urtletay oardbay.",
    "mj_htp_free_h2": "Hatway isway away Eefray Iletay?",
    "mj_htp_free_p": "Away iletay isway <strong>eefray</strong> enthway otway onditionscay arehay etmay: (1) onay iletay isway tackedstay onway optay ofway itway, andway (2) itway isway openway onway itsway eftlay <em>orway</em> ightray idesay — eaningmay onay adjacentway iletay onway ethay amesay ayerlay onway atleastway oneway idesay.",
    "mj_htp_goal_h2": "Ethay Oalway",
    "mj_htp_goal_p": "Emoveray allway 144 ilestay omfray ethay oardbay ybay electingsay atchingmay airspay. Othbay ilestay inway away airpay ustmay ebay <strong>eefray</strong>. Ethay amegay isway onway enthway ethay oardbay isway emptywayway.",
    "mj_htp_hints_h2": "Inthay Uttonsbay",
    "mj_htp_hints_p": "<strong>Owshay Eefray Ilestay</strong> ighlightshay allway urrentlycay accessibleway ilestay inway blueway. <strong>Owshay Atchesmay</strong> ighlightshay eefray ilestay atthay avehay atleastway oneway atchingmay eefray artnerpay inway eengrway.",
    "mj_htp_intro": "Ahjongmay Olitairesay isway away one-playerway iletay-atchingmay amegay. 144 ilestay arehay tackedstay inway ethay assicclway Urtletay ormationfay. Ouryay oalway isway otay emoveray allway ilestay ybay atchingmay identicalway eefray airspay.",
    "mj_htp_refs_h2": "Eferencesray",
    "mj_htp_refs_p": 'Isthay implementationway isway asedbay onway ethay open-sourceway ojectpray <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">ahmay</a> ybay ffalt. Earnlay oremay aboutway ethay amegay onway <a href="https://en.wikipedia.org/wiki/Mahjong_solitaire" target="_blank" rel="noopener noreferrer">Ikipediaway</a>.',
    "mj_htp_tiles_h2": "Iletay Ypestay &amp; Atchingmay",
    "mj_htp_tiles_p": "Ethay ullfay etsay usesway 144 ilestay: ninenay Irclescay (1-9), ninenay Amboobay (1-9), ninenay Aracterchay (1-9), ourfay Indsway (Eastway, Outhsay, Estway, Orthnay), eethray Agonsway (Edray, Eengrway, Itewhay), ourfay Asonssay, andway ourfay Owersflay. Ostmay ilestay atchmay onlyway identicalway airspay. <strong>Xceptionway:</strong> anyway otway Easonway ilestay atchmay eachway otherway, andway anyway otway Owerfly ilestay atchmay eachway otherway.",
    "mj_htp_title": "Owhay otay Ayplay Ahjongmay Olitairesay | minesweeper.org",
    "mj_lb_all_heading": "Allway Imetay",
    "mj_lb_season_heading": "Isthay Onthmay",
    "mj_lb_tab_all": "Allway Imetay",
    "mj_lb_tab_daily": "Odaytay",
    "mj_lb_tab_season": "Isthay Onthmay",
    "mj_name_label": "Amenay",
    "mj_new_game": "Ewnay Amegay",
    "mj_play_today": "Ayplay Odaytay",
    "mj_removed_pairs": "Emovedray Airspay",
    "mj_same_for_all": "Amesay oardbay orfay everyoneway · Esetsray atway idnightmay UTC",
    "mj_solved": "🎉 Olvedsay!",
    "mj_submit_btn": "Ubmitsay Orescsay",
    "mj_submit_score": "Ubmitsay ouryay orescsay",
    "mj_time": "Imetay:",
    "mj_today_heading": "Odaytay — ",
    "mj_undo": "Ndoway",
}

if __name__ == "__main__":
    for lang in ["pl", "tl", "th", "pgl"]:
        insert_mj.insert_lang(lang)
