# -*- coding: utf-8 -*-
"""nn_* batch 3: ja, zh, zh-hant, pl"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_nn

insert_nn.LANGS["ja"] = {
    "nn_bridge": "マインスイーパーがノノグラムと出会う — 行と列の手がかりを使って地雷を見つけよう。",
    "nn_btn_daily": "📅 デイリー",
    "nn_btn_new_random": "🎲 新しいランダム",
    "nn_btn_random": "🎲 ランダム",
    "nn_btn_retry": "🔄 リトライ",
    "nn_label_potd": "📅 今日のパズル",
    "nn_overlay_solved": "🎉 クリア！",
    "nn_save_score": "スコアを保存",
    "nn_lb_today": "🏆 本日のベストタイム",
    "nn_instructions": "<strong>左クリック</strong>で開く — <em>地雷をクリックするとゲームオーバー！</em> &nbsp;|&nbsp; <strong>右クリック</strong>で切り替え: フラグ 💣 &rarr; 不確か ? &rarr; 非表示。 &nbsp;|&nbsp; すべての安全なセルを開けると<strong>クリア</strong>です。",
    "nn_what_h2": "Nonosweeper とは？",
    "nn_what_p1": "Nonosweeper は、2つの人気パズル形式を融合したハイブリッドパズルです：<strong>マインスイーパー</strong>の地雷除去の緊張感と、<strong>ノノグラム</strong>（ピクロスやグリドラーとも呼ばれる）の格子推理ロジックです。標準的なマインスイーパーとは異なり、数字を開くために盲目的にクリックすることはありません — 代わりに、ノノグラムと同様に行と列のヒントの全セットが最初から表示されています。あなたの役割は、それらのヒントを使ってどのセルに地雷が隠れているかを正確に特定し、安全なセルをクリックして開けることです。",
    "nn_what_p2": "マインスイーパーの要素が緊張感を高めます：地雷を一度でも間違えてクリックすると、パズルはすぐに終了します。安全な最初のクリックはなく、ランダムな推測も許可されていません — すべての動きはヒントから推論する必要があります。",
    "nn_clues_h2": "ヒントの読み方",
    "nn_clues_p1": "各行と列には、1つ以上の数字で構成されたヒントがあります。各数字は、その行または列における<strong>連続する地雷の数</strong>を表しています。連続する地雷は順番に表示され（行は左から右、列は上から下）、少なくとも1つの安全なセルで区切られています。",
    "nn_clues_p2": 'たとえば、行のヒント <strong>3 &nbsp;1 &nbsp;2</strong> は、3つの地雷が連続、隙間、1つの地雷、隙間、そして2つの地雷が連続を意味します。<strong>—</strong> のヒントは、その行または列には地雷が全くないことを意味します。',
    "nn_diff_h2": "難易度レベル",
    "nn_diff_beginner": "初心者 (8×8)",
    "nn_diff_intermediate": "中級者 (10×10)",
    "nn_diff_expert": "上級者 (15×15)",
    "nn_diff_li1": "<strong>初心者 (8×8、地雷16個)：</strong>短いヒントのコンパクトなグリッド。メカニクスを学ぶのに最適。",
    "nn_diff_li2": "<strong>中級者 (10×10、地雷35個)：</strong>より多くのセルと密度の高い連続で、慎重なクロスリファレンスが必要。",
    "nn_diff_li3": "<strong>上級者 (15×15、地雷75個)：</strong>複数の連続を持つ複雑なヒントの大きなグリッド — 本格的なノノグラムの挑戦。",
    "nn_strat_h2": "戦略のヒント",
    "nn_strat_li1": "<strong>ゼロヒントの行/列から始めましょう。</strong>'—' ヒントはその列のすべてのセルが安全であることを意味します — 無料ですべて開けましょう。",
    "nn_strat_li2": "<strong>重複分析を使いましょう。</strong>連続が有効なすべての配置で自身と重複するほど大きい場合、重複するセルは確実に地雷です。",
    "nn_strat_li3": "<strong>行と列をクロスリファレンスしましょう。</strong>セルの行ヒントと列ヒントを組み合わせると、状態を完全に絞り込めることが多いです。",
    "nn_strat_li4": "<strong>開ける前に地雷をフラグしましょう。</strong>セルが地雷であると確信したら、隣接する安全なセルをクリックする前にフラグを立てましょう — 地雷カウンターを正確に保ち、盤面を見やすくします。",
    "nn_about_h2": "Nonosweeper について",
}

insert_nn.LANGS["zh"] = {
    "nn_bridge": "扫雷遇上数织 — 用行列线索找出所有地雷。",
    "nn_btn_daily": "📅 每日",
    "nn_btn_new_random": "🎲 新随机",
    "nn_btn_random": "🎲 随机",
    "nn_btn_retry": "🔄 重试",
    "nn_label_potd": "📅 今日谜题",
    "nn_overlay_solved": "🎉 完成！",
    "nn_save_score": "保存成绩",
    "nn_lb_today": "🏆 今日最佳时间",
    "nn_instructions": "<strong>左键点击</strong>揭开 — <em>点到地雷游戏结束！</em> &nbsp;|&nbsp; <strong>右键点击</strong>切换：标旗 💣 &rarr; 不确定 ? &rarr; 隐藏。 &nbsp;|&nbsp; 揭开所有安全格即<strong>获胜</strong>。",
    "nn_what_h2": "什么是 Nonosweeper？",
    "nn_what_p1": "Nonosweeper 是一款融合了两种经典谜题的混合游戏：<strong>扫雷</strong>的排雷紧张感与<strong>数织</strong>（也称为 Picross 或 Griddler）的格子推理逻辑。与标准扫雷不同，你无需盲目点击来揭示数字 — 行列线索从一开始就全部可见，就像数织一样。你的任务是利用这些线索推断出哪些格子藏有地雷，再点击安全格将其揭开。",
    "nn_what_p2": "扫雷元素让赌注始终保持高位：一旦误点地雷，谜题立即结束。没有安全的第一步，也不允许随机猜测 — 每一步都必须从线索中推理得出。",
    "nn_clues_h2": "如何读懂线索",
    "nn_clues_p1": "每行每列都有一条由一个或多个数字组成的线索。每个数字代表该行或列中<strong>连续地雷的数量</strong>。这些连续段按顺序排列（行从左到右，列从上到下），且相邻连续段之间至少有一个安全格。",
    "nn_clues_p2": '例如，行线索 <strong>3 &nbsp;1 &nbsp;2</strong> 表示：3个连续地雷，间隔，1个地雷，间隔，再2个连续地雷。<strong>—</strong> 线索表示该行或列没有任何地雷。',
    "nn_diff_h2": "难度等级",
    "nn_diff_beginner": "初级 (8×8)",
    "nn_diff_intermediate": "中级 (10×10)",
    "nn_diff_expert": "专家 (15×15)",
    "nn_diff_li1": "<strong>初级 (8×8，16颗地雷)：</strong>紧凑的小格盘，线索简短，适合学习规则。",
    "nn_diff_li2": "<strong>中级 (10×10，35颗地雷)：</strong>更多格子和更密集的连续段，需要仔细交叉参考。",
    "nn_diff_li3": "<strong>专家 (15×15，75颗地雷)：</strong>大格盘配复杂多段线索，是严峻的数织挑战。",
    "nn_strat_h2": "策略技巧",
    "nn_strat_li1": "<strong>从零线索行/列入手。</strong>'—' 线索意味着该行所有格子都安全 — 免费全部揭开。",
    "nn_strat_li2": "<strong>利用重叠分析。</strong>若某连续段足够长，在所有合法摆放中必然产生重叠，则重叠格子确定是地雷。",
    "nn_strat_li3": "<strong>交叉参考行与列。</strong>综合某格的行线索和列线索，往往能完全确定其状态。",
    "nn_strat_li4": "<strong>揭开前先标旗。</strong>确认某格是地雷后，先插旗再点击周边安全格 — 保持地雷计数准确，盘面清晰易读。",
    "nn_about_h2": "关于 Nonosweeper",
}

insert_nn.LANGS["zh-hant"] = {
    "nn_bridge": "掃雷遇上數織 — 用行列線索找出所有地雷。",
    "nn_btn_daily": "📅 每日",
    "nn_btn_new_random": "🎲 新隨機",
    "nn_btn_random": "🎲 隨機",
    "nn_btn_retry": "🔄 重試",
    "nn_label_potd": "📅 今日謎題",
    "nn_overlay_solved": "🎉 完成！",
    "nn_save_score": "儲存成績",
    "nn_lb_today": "🏆 今日最佳時間",
    "nn_instructions": "<strong>左鍵點擊</strong>揭開 — <em>點到地雷遊戲結束！</em> &nbsp;|&nbsp; <strong>右鍵點擊</strong>切換：標旗 💣 &rarr; 不確定 ? &rarr; 隱藏。 &nbsp;|&nbsp; 揭開所有安全格即<strong>獲勝</strong>。",
    "nn_what_h2": "什麼是 Nonosweeper？",
    "nn_what_p1": "Nonosweeper 是一款融合兩種經典謎題的混合遊戲：<strong>掃雷</strong>的排雷緊張感與<strong>數織</strong>（亦稱 Picross 或 Griddler）的格子推理邏輯。與標準掃雷不同，你無需盲目點擊來揭示數字 — 行列線索從一開始就全部可見，就像數織一樣。你的任務是利用這些線索推斷出哪些格子藏有地雷，再點擊安全格將其揭開。",
    "nn_what_p2": "掃雷元素讓賭注始終保持高位：一旦誤點地雷，謎題立即結束。沒有安全的第一步，也不允許隨機猜測 — 每一步都必須從線索中推理得出。",
    "nn_clues_h2": "如何讀懂線索",
    "nn_clues_p1": "每行每列都有一條由一個或多個數字組成的線索。每個數字代表該行或列中<strong>連續地雷的數量</strong>。這些連續段按順序排列（行從左到右，列從上到下），且相鄰連續段之間至少有一個安全格。",
    "nn_clues_p2": '例如，行線索 <strong>3 &nbsp;1 &nbsp;2</strong> 表示：3個連續地雷，間隔，1個地雷，間隔，再2個連續地雷。<strong>—</strong> 線索表示該行或列沒有任何地雷。',
    "nn_diff_h2": "難度等級",
    "nn_diff_beginner": "初級 (8×8)",
    "nn_diff_intermediate": "中級 (10×10)",
    "nn_diff_expert": "專家 (15×15)",
    "nn_diff_li1": "<strong>初級 (8×8，16顆地雷)：</strong>緊湊的小格盤，線索簡短，適合學習規則。",
    "nn_diff_li2": "<strong>中級 (10×10，35顆地雷)：</strong>更多格子和更密集的連續段，需要仔細交叉參考。",
    "nn_diff_li3": "<strong>專家 (15×15，75顆地雷)：</strong>大格盤配複雜多段線索，是嚴峻的數織挑戰。",
    "nn_strat_h2": "策略技巧",
    "nn_strat_li1": "<strong>從零線索行/列入手。</strong>'—' 線索意味著該行所有格子都安全 — 免費全部揭開。",
    "nn_strat_li2": "<strong>利用重疊分析。</strong>若某連續段足夠長，在所有合法擺放中必然產生重疊，則重疊格子確定是地雷。",
    "nn_strat_li3": "<strong>交叉參考行與列。</strong>綜合某格的行線索和列線索，往往能完全確定其狀態。",
    "nn_strat_li4": "<strong>揭開前先標旗。</strong>確認某格是地雷後，先插旗再點擊周邊安全格 — 保持地雷計數準確，盤面清晰易讀。",
    "nn_about_h2": "關於 Nonosweeper",
}

insert_nn.LANGS["pl"] = {
    "nn_bridge": "Saper spotyka Nonogram — uzyj wskazowek wierszy i kolumn, aby znalezc miny.",
    "nn_btn_daily": "📅 Codzienny",
    "nn_btn_new_random": "🎲 Nowy losowy",
    "nn_btn_random": "🎲 Losowy",
    "nn_btn_retry": "🔄 Sprobuj ponownie",
    "nn_label_potd": "📅 Zagadka dnia",
    "nn_overlay_solved": "🎉 Rozwiazano!",
    "nn_save_score": "Zapisz wynik",
    "nn_lb_today": "🏆 Dzisiejsze najlepsze czasy",
    "nn_instructions": "<strong>Lewy przycisk myszy</strong> aby odkryc — <em>klikniecie w mine konczy gre!</em> &nbsp;|&nbsp; <strong>Prawy przycisk myszy</strong> aby przelaczac: flaga 💣 &rarr; niepewny ? &rarr; ukryty. &nbsp;|&nbsp; <strong>Wygraj</strong> odkrywajac kazda bezpieczna komorke.",
    "nn_what_h2": "Co to jest Nonosweeper?",
    "nn_what_p1": "Nonosweeper to hybrydowa zagadka laczaca dwa lubiane formaty: napiecie rozminowania <strong>Sapera</strong> z logika dedukcji siatki <strong>Nonogramu</strong> (zwanego rowniez Picross lub Griddler). W przeciwienstwie do standardowego Sapera, nigdy nie klikasz slepo, aby odkryc liczby — zamiast tego pelny zestaw wskazowek wierszy i kolumn jest widoczny od samego poczatku, tak jak w nonogramie. Twoim zadaniem jest uzycie tych wskazowek do okreslenia dokladnie, ktore komorki kryja miny, a nastepnie klikniecie bezpiecznych komorek, aby je odkryc.",
    "nn_what_p2": "Element Sapera utrzymuje wysoka stawke: jeden bledny klik w mine i zagadka konczy sie natychmiast. Nie ma bezpiecznego pierwszego klikniecia i nie wolno losowo zgadywac — kazdy ruch musi byc wywnioskowany ze wskazowek.",
    "nn_clues_h2": "Jak czytac wskazowki",
    "nn_clues_p1": "Kazdy wiersz i kolumna ma wskazowke skladajaca sie z jednej lub wiecej liczb. Kazda liczba reprezentuje <strong>kolejny ciag min</strong> w tym wierszu lub kolumnie. Ciagi pojawiaja sie w kolejnosci (od lewej do prawej dla wierszy, od gory do dolu dla kolumn) i sa oddzielone co najmniej jedna bezpieczna komorka.",
    "nn_clues_p2": 'Na przyklad wskazowka wiersza <strong>3 &nbsp;1 &nbsp;2</strong> oznacza: trzy miny z rzedu, przerwa, jedna mina, przerwa, potem dwie miny z rzedu. Wskazowka <strong>—</strong> oznacza brak min w tym wierszu lub kolumnie.',
    "nn_diff_h2": "Poziomy trudnosci",
    "nn_diff_beginner": "Poczatkujacy (8x8)",
    "nn_diff_intermediate": "Sredniozaawansowany (10x10)",
    "nn_diff_expert": "Ekspert (15x15)",
    "nn_diff_li1": "<strong>Poczatkujacy (8x8, 16 min):</strong> Kompaktowa siatka z krotkimi wskazowkami. Dobry do nauki mechaniki.",
    "nn_diff_li2": "<strong>Sredniozaawansowany (10x10, 35 min):</strong> Wiecej komorek i gestsze ciagi wymagaja ostroznego krzyzowego odwolywania sie.",
    "nn_diff_li3": "<strong>Ekspert (15x15, 75 min):</strong> Duza siatka ze zlozononymi wskazowkami wielociagowymi — powazne wyzwanie nonogramowe.",
    "nn_strat_h2": "Porady strategiczne",
    "nn_strat_li1": "<strong>Zacznij od wierszy/kolumn z wskazowka zero.</strong> Wskazowka '—' oznacza, ze kazda komorka w tej linii jest bezpieczna — odkryj je wszystkie za darmo.",
    "nn_strat_li2": "<strong>Uzyj analizy nakladania sie.</strong> Jesli ciag jest wystarczajaco duzy, ze musi nakladac sie sam na siebie w kazdym prawidlowym rozmieszczeniu, te nakladajace sie komorki sa na pewno minami.",
    "nn_strat_li3": "<strong>Krzyzowo odwoluj sie do wierszy i kolumn.</strong> Wskazowka wiersza i kolumny komorki razem czesto zawezaja jej stan calkowicie.",
    "nn_strat_li4": "<strong>Oznaczaj miny przed odkrywaniem.</strong> Gdy jestes pewien, ze komorka jest mina, oflaguj ja przed klikaniem sasiadujacych bezpiecznych komorek — utrzymuje to licznik min dokladny i plansze czytelna.",
    "nn_about_h2": "O Nonosweeper",
}

if __name__ == "__main__":
    for lang in ["ja", "zh", "zh-hant", "pl"]:
        insert_nn.insert_lang(lang)
