# -*- coding: utf-8 -*-
"""quests batch 3: ko, ja, zh, zh-hant"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_quests

insert_quests.LANGS["ko"] = {
    "quests_title": "퀘스트",
    "quests_subtitle": "퀘스트를 완료하여 보상을 획득하세요. 진행 상황은 브라우저에 저장됩니다.",
    "quests_daily_title": "일일 퀘스트",
    "quests_daily_note": "하루에 하나의 퀘스트, 24시간마다 교체됩니다.",
    "quests_seasonal_title": "시즌 퀘스트",
    "quests_seasonal_note": "세 가지 모두 한 달 내내 활성화됩니다. 진행 상황은 매일 이어집니다.",
    "quests_rewards_title": "보상",
    "quests_rewards_note": "이 기기에서 광고를 비활성화하려면 보상 중 하나를 획득하세요.",
    "quests_reward_active": "보상 활성화:",
    "quests_reward_active_desc": "광고가 비활성화되었습니다 — 계속 유지하세요!",
    "quests_streak_reward_title": "20일 연속 일일 퀘스트",
    "quests_streak_reward_desc": "20일 연속으로 일일 퀘스트를 완료하세요.",
    "quests_season_reward_title": "이번 시즌 일일 퀘스트 10개",
    "quests_season_reward_desc": "이번 달 중 아무 10일에 일일 퀘스트를 완료하세요.",
    "quests_og_title": "지뢰찾기 퀘스트",
    "quests_og_desc": "지뢰찾기의 일일 및 월간 퀘스트를 완료하세요. 20일 연속 또는 한 시즌에 10개를 완료하여 광고를 비활성화하세요.",
    "quest_complete": "완료!",
    "quest_unlocked": "해금!",
    "quest_not_complete": "아직 완료되지 않음",
    "quest_play": "플레이",
    "quest_days": "일",
    "quest_daily_easy_win": "쉬운 지뢰찾기 승리",
    "quest_daily_rush_5": "Rush 모드에서 지뢰 5개 제거",
    "quest_daily_tentaizu": "오늘의 Tentaizu 퍼즐 완료",
    "quest_season_intermediate_win": "중간 지뢰찾기 승리",
    "quest_season_rush_100": "Rush 모드에서 지뢰 100개 제거",
    "quest_season_tentaizu_10": "일일 Tentaizu 퍼즐 10개 완료",
    "quest_reward_reason_streak": "20일 연속 일일 퀘스트",
    "quest_reward_reason_season": "이번 시즌 일일 퀘스트 10개",
    "quest_toast_daily_easy": "일일 퀘스트 완료! 쉬운 지뢰찾기 승리.",
    "quest_toast_daily_rush": "일일 퀘스트 완료! Rush 지뢰 5개 제거됨.",
    "quest_toast_daily_tentaizu": "일일 퀘스트 완료! Tentaizu 퍼즐 완료됨.",
    "quest_toast_reward_unlocked": "보상 해금! 광고 비활성화됨 — {reason}.",
    "quest_toast_season_intermediate": "시즌 퀘스트 완료! 중간 지뢰찾기 승리!",
    "quest_toast_season_rush": "시즌 퀘스트 완료! Rush 지뢰 100개 제거됨!",
    "quest_toast_season_tentaizu": "시즌 퀘스트 완료! Tentaizu 퍼즐 10개 완료됨!",
}

insert_quests.LANGS["ja"] = {
    "quests_title": "クエスト",
    "quests_subtitle": "クエストをクリアして報酬を獲得しましょう。進捗はブラウザに保存されます。",
    "quests_daily_title": "デイリークエスト",
    "quests_daily_note": "1日1クエスト、24時間ごとに更新されます。",
    "quests_seasonal_title": "シーズンクエスト",
    "quests_seasonal_note": "3つすべてが1か月間有効です。進捗は毎日引き継がれます。",
    "quests_rewards_title": "報酬",
    "quests_rewards_note": "いずれかの報酬を獲得すると、このデバイスで広告が非表示になります。",
    "quests_reward_active": "報酬アクティブ:",
    "quests_reward_active_desc": "広告は非表示になっています — 続けましょう！",
    "quests_streak_reward_title": "20日連続デイリークエスト",
    "quests_streak_reward_desc": "20日連続でデイリークエストをクリアしましょう。",
    "quests_season_reward_title": "今シーズン10回のデイリークエスト",
    "quests_season_reward_desc": "今月中に任意の10日間デイリークエストをクリアしましょう。",
    "quests_og_title": "マインスイーパークエスト",
    "quests_og_desc": "マインスイーパーのデイリーおよび月間クエストをクリアしましょう。20日連続または1シーズンに10クエストをクリアして広告を非表示にしましょう。",
    "quest_complete": "クリア！",
    "quest_unlocked": "解除！",
    "quest_not_complete": "未クリア",
    "quest_play": "プレイ",
    "quest_days": "日",
    "quest_daily_easy_win": "初級マインスイーパーをクリア",
    "quest_daily_rush_5": "Rushモードで地雷を5個除去",
    "quest_daily_tentaizu": "デイリーTentaizuパズルをクリア",
    "quest_season_intermediate_win": "中級マインスイーパーをクリア",
    "quest_season_rush_100": "Rushモードで地雷を100個除去",
    "quest_season_tentaizu_10": "デイリーTentaizuパズルを10個クリア",
    "quest_reward_reason_streak": "20日連続デイリークエスト",
    "quest_reward_reason_season": "今シーズン10回のデイリークエスト",
    "quest_toast_daily_easy": "デイリークエストクリア！初級マインスイーパー攻略。",
    "quest_toast_daily_rush": "デイリークエストクリア！Rush地雷5個除去完了。",
    "quest_toast_daily_tentaizu": "デイリークエストクリア！Tentaizuパズル攻略。",
    "quest_toast_reward_unlocked": "報酬解除！広告非表示 — {reason}。",
    "quest_toast_season_intermediate": "シーズンクエストクリア！中級マインスイーパー攻略！",
    "quest_toast_season_rush": "シーズンクエストクリア！Rush地雷100個除去完了！",
    "quest_toast_season_tentaizu": "シーズンクエストクリア！Tentaizuパズル10個攻略！",
}

insert_quests.LANGS["zh"] = {
    "quests_title": "任务",
    "quests_subtitle": "完成任务以获得奖励。进度保存在您的浏览器中。",
    "quests_daily_title": "每日任务",
    "quests_daily_note": "每天一个任务，每24小时轮换一次。",
    "quests_seasonal_title": "赛季任务",
    "quests_seasonal_note": "三个任务全月有效。进度每天累积。",
    "quests_rewards_title": "奖励",
    "quests_rewards_note": "获得任意奖励即可在此设备上关闭广告。",
    "quests_reward_active": "奖励已激活：",
    "quests_reward_active_desc": "广告已关闭 — 继续保持！",
    "quests_streak_reward_title": "每日任务20天连击",
    "quests_streak_reward_desc": "连续20天完成每日任务。",
    "quests_season_reward_title": "本赛季完成10次每日任务",
    "quests_season_reward_desc": "本月任意10天完成每日任务。",
    "quests_og_title": "扫雷任务",
    "quests_og_desc": "完成扫雷的每日和月度任务。达成20天连击或一个赛季完成10个任务即可关闭广告。",
    "quest_complete": "已完成！",
    "quest_unlocked": "已解锁！",
    "quest_not_complete": "尚未完成",
    "quest_play": "游玩",
    "quest_days": "天",
    "quest_daily_easy_win": "赢得简单扫雷",
    "quest_daily_rush_5": "在Rush模式中消除5个地雷",
    "quest_daily_tentaizu": "完成每日Tentaizu谜题",
    "quest_season_intermediate_win": "赢得中级扫雷",
    "quest_season_rush_100": "在Rush模式中消除100个地雷",
    "quest_season_tentaizu_10": "完成10个每日Tentaizu谜题",
    "quest_reward_reason_streak": "每日任务20天连击",
    "quest_reward_reason_season": "本赛季完成10次每日任务",
    "quest_toast_daily_easy": "每日任务完成！简单扫雷已获胜。",
    "quest_toast_daily_rush": "每日任务完成！已消除5个Rush地雷。",
    "quest_toast_daily_tentaizu": "每日任务完成！Tentaizu谜题已完成。",
    "quest_toast_reward_unlocked": "奖励已解锁！广告已关闭 — {reason}。",
    "quest_toast_season_intermediate": "赛季任务完成！中级扫雷已获胜！",
    "quest_toast_season_rush": "赛季任务完成！已消除100个Rush地雷！",
    "quest_toast_season_tentaizu": "赛季任务完成！已完成10个Tentaizu谜题！",
}

insert_quests.LANGS["zh-hant"] = {
    "quests_title": "任務",
    "quests_subtitle": "完成任務以獲得獎勵。進度儲存在您的瀏覽器中。",
    "quests_daily_title": "每日任務",
    "quests_daily_note": "每天一個任務，每24小時輪換一次。",
    "quests_seasonal_title": "賽季任務",
    "quests_seasonal_note": "三個任務全月有效。進度每天累積。",
    "quests_rewards_title": "獎勵",
    "quests_rewards_note": "獲得任意獎勵即可在此裝置上關閉廣告。",
    "quests_reward_active": "獎勵已啟用：",
    "quests_reward_active_desc": "廣告已關閉 — 繼續保持！",
    "quests_streak_reward_title": "每日任務20天連擊",
    "quests_streak_reward_desc": "連續20天完成每日任務。",
    "quests_season_reward_title": "本賽季完成10次每日任務",
    "quests_season_reward_desc": "本月任意10天完成每日任務。",
    "quests_og_title": "踩地雷任務",
    "quests_og_desc": "完成踩地雷的每日和月度任務。達成20天連擊或一個賽季完成10個任務即可關閉廣告。",
    "quest_complete": "已完成！",
    "quest_unlocked": "已解鎖！",
    "quest_not_complete": "尚未完成",
    "quest_play": "遊玩",
    "quest_days": "天",
    "quest_daily_easy_win": "贏得簡單踩地雷",
    "quest_daily_rush_5": "在Rush模式中消除5個地雷",
    "quest_daily_tentaizu": "完成每日Tentaizu謎題",
    "quest_season_intermediate_win": "贏得中級踩地雷",
    "quest_season_rush_100": "在Rush模式中消除100個地雷",
    "quest_season_tentaizu_10": "完成10個每日Tentaizu謎題",
    "quest_reward_reason_streak": "每日任務20天連擊",
    "quest_reward_reason_season": "本賽季完成10次每日任務",
    "quest_toast_daily_easy": "每日任務完成！簡單踩地雷已獲勝。",
    "quest_toast_daily_rush": "每日任務完成！已消除5個Rush地雷。",
    "quest_toast_daily_tentaizu": "每日任務完成！Tentaizu謎題已完成。",
    "quest_toast_reward_unlocked": "獎勵已解鎖！廣告已關閉 — {reason}。",
    "quest_toast_season_intermediate": "賽季任務完成！中級踩地雷已獲勝！",
    "quest_toast_season_rush": "賽季任務完成！已消除100個Rush地雷！",
    "quest_toast_season_tentaizu": "賽季任務完成！已完成10個Tentaizu謎題！",
}

if __name__ == "__main__":
    for lang in ["ko", "ja", "zh", "zh-hant"]:
        insert_quests.insert_lang(lang)
