"""mj_* batch 3: ko, ja, zh, zh-hant"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_mj

insert_mj.LANGS["ko"] = {
    "mj_hint_free": "빈 타일 표시",
    "mj_hint_match": "일치 항목 표시",
    "mj_htp_back": "오늘의 퍼즐 플레이",
    "mj_htp_controls_h2": "조작법",
    "mj_htp_controls_li1": "<strong>빈 타일을 클릭</strong>하여 선택합니다 (금색으로 강조됨).",
    "mj_htp_controls_li2": "<strong>같은 종류의 두 번째 빈 타일을 클릭</strong>하여 쌍을 제거합니다.",
    "mj_htp_controls_li3": "<strong>선택한 타일을 다시 클릭</strong>하여 선택을 취소합니다.",
    "mj_htp_controls_li4": "<strong>실행 취소</strong>는 한 번에 일치된 쌍 하나씩 되돌립니다.",
    "mj_htp_daily_h2": "오늘의 퍼즐",
    "mj_htp_daily_p": "매일 오늘 날짜로 새 보드가 생성됩니다 — 전 세계 모든 플레이어에게 동일한 보드입니다. 첫 번째 타일을 클릭하면 타이머가 시작됩니다. 보드를 완료하면 리더보드에 시간을 제출할 수 있습니다.",
    "mj_htp_desc": "마작 솔리테어 규칙 학습 — 빈 타일 쌍을 맞추고, 힌트를 사용하고, 거북이 보드를 지우세요.",
    "mj_htp_free_h2": "빈 타일이란?",
    "mj_htp_free_p": "타일이 <strong>비어있는</strong> 상태는 두 가지 조건이 충족될 때입니다: (1) 위에 쌓인 타일이 없고, (2) 왼쪽 <em>또는</em> 오른쪽이 열려 있을 때 — 즉, 적어도 한쪽에 같은 층의 인접 타일이 없는 경우입니다.",
    "mj_htp_goal_h2": "목표",
    "mj_htp_goal_p": "일치하는 쌍을 선택하여 보드에서 144개의 타일을 모두 제거하세요. 쌍의 두 타일 모두 <strong>비어있어야</strong> 합니다. 보드가 비어있으면 게임에서 승리합니다.",
    "mj_htp_hints_h2": "힌트 버튼",
    "mj_htp_hints_p": "<strong>빈 타일 표시</strong>는 현재 접근 가능한 모든 타일을 파란색으로 강조합니다. <strong>일치 항목 표시</strong>는 적어도 하나의 일치하는 빈 파트너가 있는 빈 타일을 녹색으로 강조합니다.",
    "mj_htp_intro": "마작 솔리테어는 1인용 타일 매칭 게임입니다. 144개의 타일이 클래식 거북이 형태로 쌓여 있습니다. 동일한 빈 쌍을 맞춰 모든 타일을 제거하는 것이 목표입니다.",
    "mj_htp_refs_h2": "참고자료",
    "mj_htp_refs_p": '이 구현은 ffalt의 오픈소스 프로젝트 <a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a>를 기반으로 합니다. <a href="https://ko.wikipedia.org/wiki/%EB%A7%88%EC%9E%91_%EC%86%94%EB%A6%AC%ED%85%8C%EC%96%B4" target="_blank" rel="noopener noreferrer">위키백과</a>에서 게임에 대해 더 알아보세요.',
    "mj_htp_tiles_h2": "타일 종류 &amp; 매칭",
    "mj_htp_tiles_p": "전체 세트는 144개의 타일을 사용합니다: 원형 9개 (1–9), 대나무 9개 (1–9), 한자 9개 (1–9), 바람 4개 (동, 남, 서, 북), 용 3개 (적, 녹, 백), 계절 4개, 꽃 4개. 대부분의 타일은 동일한 쌍과만 매칭됩니다. <strong>예외:</strong> 임의의 두 계절 타일은 서로 매칭되고, 임의의 두 꽃 타일도 서로 매칭됩니다.",
    "mj_htp_title": "마작 솔리테어 플레이 방법 | minesweeper.org",
    "mj_lb_all_heading": "전체 기간",
    "mj_lb_season_heading": "이번 달",
    "mj_lb_tab_all": "전체 기간",
    "mj_lb_tab_daily": "오늘",
    "mj_lb_tab_season": "이번 달",
    "mj_name_label": "이름",
    "mj_new_game": "새 게임",
    "mj_play_today": "오늘 플레이",
    "mj_removed_pairs": "제거된 쌍",
    "mj_same_for_all": "모두 동일한 보드 · UTC 자정에 초기화",
    "mj_solved": "🎉 해결됨!",
    "mj_submit_btn": "점수 제출",
    "mj_submit_score": "점수를 제출하세요",
    "mj_time": "시간:",
    "mj_today_heading": "오늘 — ",
    "mj_undo": "실행 취소",
}

insert_mj.LANGS["ja"] = {
    "mj_hint_free": "フリータイルを表示",
    "mj_hint_match": "マッチを表示",
    "mj_htp_back": "今日のパズルをプレイ",
    "mj_htp_controls_h2": "操作方法",
    "mj_htp_controls_li1": "<strong>フリータイルをクリック</strong>して選択します（金色でハイライト）。",
    "mj_htp_controls_li2": "<strong>同じ種類の2枚目のフリータイルをクリック</strong>してペアを取り除きます。",
    "mj_htp_controls_li3": "<strong>選択したタイルをもう一度クリック</strong>して選択を解除します。",
    "mj_htp_controls_li4": "<strong>元に戻す</strong>はマッチしたペアを1つずつ元に戻します。",
    "mj_htp_daily_h2": "デイリーパズル",
    "mj_htp_daily_p": "毎日今日の日付から新しいボードが生成されます — 世界中のすべてのプレイヤーに同じボードです。タイマーは最初のタイルをクリックしたときに開始されます。ボードを完成させてリーダーボードにタイムを送信しましょう。",
    "mj_htp_desc": "麻雀ソリティアのルールを学ぶ — フリータイルのペアをマッチさせ、ヒントを使って、タートルボードをクリアしましょう。",
    "mj_htp_free_h2": "フリータイルとは？",
    "mj_htp_free_p": "タイルが<strong>フリー</strong>になるのは、2つの条件が満たされた場合です：(1) 上にタイルが積まれていない、かつ (2) 左<em>または</em>右が開いている — つまり、少なくとも一方の側に同じ層の隣接タイルがない。",
    "mj_htp_goal_h2": "ゴール",
    "mj_htp_goal_p": "一致するペアを選択してボードから144枚のタイルをすべて取り除きます。ペアの両方のタイルが<strong>フリー</strong>でなければなりません。ボードが空になるとゲームに勝利します。",
    "mj_htp_hints_h2": "ヒントボタン",
    "mj_htp_hints_p": "<strong>フリータイルを表示</strong>は現在アクセス可能なすべてのタイルを青でハイライトします。<strong>マッチを表示</strong>は少なくとも1つの一致するフリーパートナーを持つフリータイルを緑でハイライトします。",
    "mj_htp_intro": "麻雀ソリティアは1人用のタイルマッチングゲームです。144枚のタイルがクラシックなタートルの形に積み重ねられています。同一のフリーペアをマッチさせてすべてのタイルを取り除くのが目標です。",
    "mj_htp_refs_h2": "参考文献",
    "mj_htp_refs_p": 'この実装はffaltのオープンソースプロジェクト<a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a>に基づいています。ゲームの詳細は<a href="https://ja.wikipedia.org/wiki/%E9%BA%BB%E5%B0%86%E3%82%BD%E3%83%AA%E3%83%86%E3%82%A3%E3%82%A2" target="_blank" rel="noopener noreferrer">Wikipedia</a>をご覧ください。',
    "mj_htp_tiles_h2": "タイルの種類 &amp; マッチング",
    "mj_htp_tiles_p": "フルセットは144枚のタイルを使用します：筒子9枚(1–9)、索子9枚(1–9)、万子9枚(1–9)、風牌4枚(東南西北)、三元牌3枚(中発白)、季節4枚、花4枚。ほとんどのタイルは同一のペアとのみマッチします。<strong>例外：</strong>任意の2枚の季節タイルはお互いにマッチし、任意の2枚の花タイルもお互いにマッチします。",
    "mj_htp_title": "麻雀ソリティアの遊び方 | minesweeper.org",
    "mj_lb_all_heading": "歴代",
    "mj_lb_season_heading": "今月",
    "mj_lb_tab_all": "歴代",
    "mj_lb_tab_daily": "今日",
    "mj_lb_tab_season": "今月",
    "mj_name_label": "名前",
    "mj_new_game": "新しいゲーム",
    "mj_play_today": "今日プレイ",
    "mj_removed_pairs": "取り除いたペア",
    "mj_same_for_all": "全員同じボード · UTC深夜にリセット",
    "mj_solved": "🎉 クリア！",
    "mj_submit_btn": "スコアを送信",
    "mj_submit_score": "スコアを送信する",
    "mj_time": "タイム:",
    "mj_today_heading": "今日 — ",
    "mj_undo": "元に戻す",
}

insert_mj.LANGS["zh"] = {
    "mj_hint_free": "显示可用牌",
    "mj_hint_match": "显示可配对",
    "mj_htp_back": "玩今日谜题",
    "mj_htp_controls_h2": "操作说明",
    "mj_htp_controls_li1": "<strong>点击一张可用牌</strong>以选中它（以金色高亮显示）。",
    "mj_htp_controls_li2": "<strong>点击相同类型的第二张可用牌</strong>以移除这对牌。",
    "mj_htp_controls_li3": "<strong>再次点击已选中的牌</strong>以取消选择。",
    "mj_htp_controls_li4": "<strong>撤销</strong>每次撤回一对已配对的牌。",
    "mj_htp_daily_h2": "每日谜题",
    "mj_htp_daily_p": "每天根据今日日期生成一个新棋盘——全球所有玩家的棋盘相同。点击第一张牌时计时器启动。完成棋盘即可将您的时间提交至排行榜。",
    "mj_htp_desc": "学习麻将单人纸牌游戏的规则——配对可用牌、使用提示，清空龟形棋盘。",
    "mj_htp_free_h2": "什么是可用牌？",
    "mj_htp_free_p": "当满足以下两个条件时，一张牌为<strong>可用牌</strong>：(1) 上方没有其他牌叠放，且 (2) 左侧<em>或</em>右侧是开放的——即同一层至少一侧没有相邻的牌。",
    "mj_htp_goal_h2": "目标",
    "mj_htp_goal_p": "通过选择匹配的对子，将棋盘上的全部144张牌移除。每对中的两张牌都必须是<strong>可用牌</strong>。当棋盘为空时，游戏获胜。",
    "mj_htp_hints_h2": "提示按钮",
    "mj_htp_hints_p": "<strong>显示可用牌</strong>以蓝色高亮显示当前所有可访问的牌。<strong>显示可配对</strong>以绿色高亮显示至少有一个匹配可用搭档的可用牌。",
    "mj_htp_intro": "麻将单人纸牌游戏是一款单人牌型匹配游戏。144张牌以经典龟形叠放。您的目标是通过匹配相同的可用对子移除所有牌。",
    "mj_htp_refs_h2": "参考资料",
    "mj_htp_refs_p": '本实现基于ffalt的开源项目<a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a>。在<a href="https://zh.wikipedia.org/wiki/%E9%BA%BB%E5%B0%86%E7%89%8C%E6%B8%B8%E6%88%8F" target="_blank" rel="noopener noreferrer">维基百科</a>上了解更多关于该游戏的信息。',
    "mj_htp_tiles_h2": "牌型 &amp; 配对规则",
    "mj_htp_tiles_p": "完整套装包含144张牌：9张饼牌（1–9）、9张条牌（1–9）、9张万字牌（1–9）、4张风牌（东南西北）、3张三元牌（中发白）、4张季节牌和4张花牌。大多数牌只与相同的牌配对。<strong>例外：</strong>任意两张季节牌可相互配对，任意两张花牌也可相互配对。",
    "mj_htp_title": "如何游玩麻将单人纸牌 | minesweeper.org",
    "mj_lb_all_heading": "历史最佳",
    "mj_lb_season_heading": "本月",
    "mj_lb_tab_all": "历史最佳",
    "mj_lb_tab_daily": "今日",
    "mj_lb_tab_season": "本月",
    "mj_name_label": "名称",
    "mj_new_game": "新游戏",
    "mj_play_today": "今日游玩",
    "mj_removed_pairs": "已移除对子",
    "mj_same_for_all": "所有人棋盘相同 · UTC午夜重置",
    "mj_solved": "🎉 完成！",
    "mj_submit_btn": "提交成绩",
    "mj_submit_score": "提交您的成绩",
    "mj_time": "时间：",
    "mj_today_heading": "今日 — ",
    "mj_undo": "撤销",
}

insert_mj.LANGS["zh-hant"] = {
    "mj_hint_free": "顯示可用牌",
    "mj_hint_match": "顯示可配對",
    "mj_htp_back": "玩今日謎題",
    "mj_htp_controls_h2": "操作說明",
    "mj_htp_controls_li1": "<strong>點擊一張可用牌</strong>以選中它（以金色高亮顯示）。",
    "mj_htp_controls_li2": "<strong>點擊相同類型的第二張可用牌</strong>以移除這對牌。",
    "mj_htp_controls_li3": "<strong>再次點擊已選中的牌</strong>以取消選擇。",
    "mj_htp_controls_li4": "<strong>撤銷</strong>每次撤回一對已配對的牌。",
    "mj_htp_daily_h2": "每日謎題",
    "mj_htp_daily_p": "每天根據今日日期生成一個新棋盤——全球所有玩家的棋盤相同。點擊第一張牌時計時器啟動。完成棋盤即可將您的時間提交至排行榜。",
    "mj_htp_desc": "學習麻將單人紙牌遊戲的規則——配對可用牌、使用提示，清空龜形棋盤。",
    "mj_htp_free_h2": "什麼是可用牌？",
    "mj_htp_free_p": "當滿足以下兩個條件時，一張牌為<strong>可用牌</strong>：(1) 上方沒有其他牌疊放，且 (2) 左側<em>或</em>右側是開放的——即同一層至少一側沒有相鄰的牌。",
    "mj_htp_goal_h2": "目標",
    "mj_htp_goal_p": "透過選擇匹配的對子，將棋盤上的全部144張牌移除。每對中的兩張牌都必須是<strong>可用牌</strong>。當棋盤為空時，遊戲獲勝。",
    "mj_htp_hints_h2": "提示按鈕",
    "mj_htp_hints_p": "<strong>顯示可用牌</strong>以藍色高亮顯示當前所有可訪問的牌。<strong>顯示可配對</strong>以綠色高亮顯示至少有一個匹配可用搭檔的可用牌。",
    "mj_htp_intro": "麻將單人紙牌遊戲是一款單人牌型匹配遊戲。144張牌以經典龜形疊放。您的目標是透過匹配相同的可用對子移除所有牌。",
    "mj_htp_refs_h2": "參考資料",
    "mj_htp_refs_p": '本實現基於ffalt的開源項目<a href="https://github.com/ffalt/mah" target="_blank" rel="noopener noreferrer">mah</a>。在<a href="https://zh.wikipedia.org/wiki/%E9%BA%BB%E5%B0%86%E7%89%8C%E6%B8%B8%E6%88%8F" target="_blank" rel="noopener noreferrer">維基百科</a>上了解更多關於該遊戲的資訊。',
    "mj_htp_tiles_h2": "牌型 &amp; 配對規則",
    "mj_htp_tiles_p": "完整套裝包含144張牌：9張餅牌（1–9）、9張條牌（1–9）、9張萬字牌（1–9）、4張風牌（東南西北）、3張三元牌（中發白）、4張季節牌和4張花牌。大多數牌只與相同的牌配對。<strong>例外：</strong>任意兩張季節牌可相互配對，任意兩張花牌也可相互配對。",
    "mj_htp_title": "如何遊玩麻將單人紙牌 | minesweeper.org",
    "mj_lb_all_heading": "歷史最佳",
    "mj_lb_season_heading": "本月",
    "mj_lb_tab_all": "歷史最佳",
    "mj_lb_tab_daily": "今日",
    "mj_lb_tab_season": "本月",
    "mj_name_label": "名稱",
    "mj_new_game": "新遊戲",
    "mj_play_today": "今日遊玩",
    "mj_removed_pairs": "已移除對子",
    "mj_same_for_all": "所有人棋盤相同 · UTC午夜重置",
    "mj_solved": "🎉 完成！",
    "mj_submit_btn": "提交成績",
    "mj_submit_score": "提交您的成績",
    "mj_time": "時間：",
    "mj_today_heading": "今日 — ",
    "mj_undo": "撤銷",
}

if __name__ == "__main__":
    for lang in ["ko", "ja", "zh", "zh-hant"]:
        insert_mj.insert_lang(lang)
