# -*- coding: utf-8 -*-
"""nn_* batch 2: ru, pt, it, ko"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_nn

insert_nn.LANGS["ru"] = {
    "nn_bridge": "Сапёр встречает Нонограмму — используйте подсказки строк и столбцов для поиска мин.",
    "nn_btn_daily": "📅 Ежедневно",
    "nn_btn_new_random": "🎲 Новая случайная",
    "nn_btn_random": "🎲 Случайная",
    "nn_btn_retry": "🔄 Повторить",
    "nn_label_potd": "📅 Задача дня",
    "nn_overlay_solved": "🎉 Решено!",
    "nn_save_score": "Сохранить результат",
    "nn_lb_today": "🏆 Лучшее время сегодня",
    "nn_instructions": "<strong>Левая кнопка</strong> для открытия — <em>клик на мину завершает игру!</em> &nbsp;|&nbsp; <strong>Правая кнопка</strong> для переключения: флаг 💣 &rarr; под вопросом ? &rarr; скрыто. &nbsp;|&nbsp; <strong>Победите</strong>, открыв каждую безопасную клетку.",
    "nn_what_h2": "Что такое Nonosweeper?",
    "nn_what_p1": "Nonosweeper — это гибридная головоломка, объединяющая два любимых формата: напряжение разминирования <strong>Сапёра</strong> и логику дедукции сетки <strong>Нонограммы</strong> (также известной как Picross или Griddler). В отличие от стандартного Сапёра, вы никогда не кликаете вслепую для открытия чисел — вместо этого полный набор подсказок строк и столбцов виден с самого начала, как и в нонограмме. Ваша задача — использовать эти подсказки, чтобы выяснить, какие клетки скрывают мины, а затем нажимать на безопасные клетки.",
    "nn_what_p2": "Элемент Сапёра поддерживает ставки высокими: один неверный клик на мину — и головоломка немедленно завершается. Нет безопасного первого клика и никакого случайного угадывания — каждый ход должен быть выведен из подсказок.",
    "nn_clues_h2": "Как читать подсказки",
    "nn_clues_p1": "Каждая строка и столбец имеют подсказку из одного или нескольких чисел. Каждое число представляет <strong>последовательный ряд мин</strong> в этой строке или столбце. Ряды появляются по порядку (слева направо для строк, сверху вниз для столбцов) и разделены хотя бы одной безопасной клеткой.",
    "nn_clues_p2": 'Например, подсказка строки <strong>3 &nbsp;1 &nbsp;2</strong> означает: три мины подряд, промежуток, одна мина, промежуток, затем две мины подряд. Подсказка <strong>—</strong> означает, что в этой строке или столбце нет мин.',
    "nn_diff_h2": "Уровни сложности",
    "nn_diff_beginner": "Начинающий (8×8)",
    "nn_diff_intermediate": "Средний (10×10)",
    "nn_diff_expert": "Эксперт (15×15)",
    "nn_diff_li1": "<strong>Начинающий (8×8, 16 мин):</strong> Компактная сетка с короткими подсказками. Хорошо для изучения механики.",
    "nn_diff_li2": "<strong>Средний (10×10, 35 мин):</strong> Больше клеток и более плотные ряды требуют тщательных перекрёстных ссылок.",
    "nn_diff_li3": "<strong>Эксперт (15×15, 75 мин):</strong> Большая сетка со сложными подсказками из нескольких рядов — серьёзный вызов нонограммы.",
    "nn_strat_h2": "Стратегические советы",
    "nn_strat_li1": "<strong>Начинайте с строк/столбцов с нулевой подсказкой.</strong> Подсказка '—' означает, что каждая клетка в этой линии безопасна — откройте их все бесплатно.",
    "nn_strat_li2": "<strong>Используйте анализ перекрытий.</strong> Если ряд достаточно большой, чтобы перекрываться при каждом допустимом размещении, эти перекрывающиеся клетки точно являются минами.",
    "nn_strat_li3": "<strong>Перекрёстные ссылки строк и столбцов.</strong> Подсказки строки и столбца клетки вместе часто полностью ограничивают её состояние.",
    "nn_strat_li4": "<strong>Помечайте мины перед открытием.</strong> Как только вы убеждены, что клетка является миной, отметьте её перед нажатием на соседние безопасные клетки — это поддерживает точный счётчик мин и читабельную доску.",
    "nn_about_h2": "О Nonosweeper",
}

insert_nn.LANGS["pt"] = {
    "nn_bridge": "Minesweeper encontra o Nonograma — use as pistas de linhas e colunas para encontrar as minas.",
    "nn_btn_daily": "📅 Diário",
    "nn_btn_new_random": "🎲 Novo aleatório",
    "nn_btn_random": "🎲 Aleatório",
    "nn_btn_retry": "🔄 Tentar novamente",
    "nn_label_potd": "📅 Puzzle do dia",
    "nn_overlay_solved": "🎉 Resolvido!",
    "nn_save_score": "Guardar pontuação",
    "nn_lb_today": "🏆 Melhores tempos de hoje",
    "nn_instructions": "<strong>Clique esquerdo</strong> para revelar — <em>clicar numa mina termina o jogo!</em> &nbsp;|&nbsp; <strong>Clique direito</strong> para ciclar: bandeira 💣 &rarr; incerto ? &rarr; oculto. &nbsp;|&nbsp; <strong>Ganhe</strong> revelando cada célula segura.",
    "nn_what_h2": "O que é o Nonosweeper?",
    "nn_what_p1": "O Nonosweeper é um puzzle híbrido que funde dois formatos de puzzle adorados: a tensão de limpar minas do <strong>Campo Minado</strong> e a lógica de dedução de grelha de um <strong>Nonograma</strong> (também conhecido como Picross ou Griddler). Ao contrário do Campo Minado padrão, nunca clica às cegas para revelar números — em vez disso, o conjunto completo de pistas de linhas e colunas é visível desde o início, tal como num nonograma. O seu trabalho é usar essas pistas para descobrir exatamente quais células escondem minas e depois clicar nas células seguras para as revelar.",
    "nn_what_p2": "O elemento Campo Minado mantém as apostas altas: um clique errado numa mina e o puzzle termina imediatamente. Não há primeiro clique seguro e não é permitido adivinhar aleatoriamente — cada movimento deve ser deduzido das pistas.",
    "nn_clues_h2": "Como ler as pistas",
    "nn_clues_p1": "Cada linha e coluna tem uma pista composta por um ou mais números. Cada número representa uma <strong>sequência consecutiva de minas</strong> nessa linha ou coluna. As sequências aparecem por ordem (da esquerda para a direita nas linhas, de cima para baixo nas colunas) e são separadas por pelo menos uma célula segura.",
    "nn_clues_p2": 'Por exemplo, uma pista de linha de <strong>3 &nbsp;1 &nbsp;2</strong> significa: três minas seguidas, um espaço, uma mina, um espaço, depois duas minas seguidas. Uma pista de <strong>—</strong> significa que não há minas nessa linha ou coluna.',
    "nn_diff_h2": "Níveis de dificuldade",
    "nn_diff_beginner": "Iniciante (8×8)",
    "nn_diff_intermediate": "Intermédio (10×10)",
    "nn_diff_expert": "Especialista (15×15)",
    "nn_diff_li1": "<strong>Iniciante (8×8, 16 minas):</strong> Uma grelha compacta com pistas curtas. Bom para aprender o mecânico.",
    "nn_diff_li2": "<strong>Intermédio (10×10, 35 minas):</strong> Mais células e sequências mais densas requerem uma referência cruzada cuidadosa.",
    "nn_diff_li3": "<strong>Especialista (15×15, 75 minas):</strong> Uma grande grelha com pistas complexas de múltiplas sequências — um sério desafio de nonograma.",
    "nn_strat_h2": "Dicas de estratégia",
    "nn_strat_li1": "<strong>Comece com linhas/colunas de pista zero.</strong> Uma pista '—' significa que cada célula nessa linha é segura — revele-as todas de graça.",
    "nn_strat_li2": "<strong>Use a análise de sobreposição.</strong> Se uma sequência for grande o suficiente para se sobrepor em cada posicionamento válido, essas células sobrepostas são definitivamente minas.",
    "nn_strat_li3": "<strong>Faça referência cruzada entre linhas e colunas.</strong> A pista de linha e a pista de coluna de uma célula juntas muitas vezes restringem completamente o seu estado.",
    "nn_strat_li4": "<strong>Marque as minas antes de revelar.</strong> Quando tiver a certeza de que uma célula é uma mina, marque-a antes de clicar nas células seguras adjacentes — mantém o contador de minas preciso e o tabuleiro legível.",
    "nn_about_h2": "Sobre o Nonosweeper",
}

insert_nn.LANGS["it"] = {
    "nn_bridge": "Puntaspilli incontra il Nonogramma — usa gli indizi di righe e colonne per trovare le mine.",
    "nn_btn_daily": "📅 Quotidiano",
    "nn_btn_new_random": "🎲 Nuovo casuale",
    "nn_btn_random": "🎲 Casuale",
    "nn_btn_retry": "🔄 Riprova",
    "nn_label_potd": "📅 Puzzle del giorno",
    "nn_overlay_solved": "🎉 Risolto!",
    "nn_save_score": "Salva punteggio",
    "nn_lb_today": "🏆 Migliori tempi di oggi",
    "nn_instructions": "<strong>Click sinistro</strong> per rivelare — <em>cliccare su una mina termina il gioco!</em> &nbsp;|&nbsp; <strong>Click destro</strong> per ciclare: bandiera 💣 &rarr; incerto ? &rarr; nascosto. &nbsp;|&nbsp; <strong>Vinci</strong> rivelando ogni cella sicura.",
    "nn_what_h2": "Cos'è Nonosweeper?",
    "nn_what_p1": "Nonosweeper è un puzzle ibrido che fonde due amati formati di puzzle: la tensione dello sminamento di <strong>Campo Minato</strong> e la logica di deduzione della griglia di un <strong>Nonogramma</strong> (noto anche come Picross o Griddler). A differenza del Campo Minato standard, non fai mai clic alla cieca per rivelare i numeri — invece, l'intero set di indizi di righe e colonne è visibile dall'inizio, proprio come in un nonogramma. Il tuo compito è usare questi indizi per capire esattamente quali celle nascondono mine, poi fare clic sulle celle sicure per rivelarle.",
    "nn_what_p2": "L'elemento Campo Minato mantiene alta la posta: un clic sbagliato su una mina e il puzzle finisce immediatamente. Non c'è primo clic sicuro e non è consentito fare ipotesi casuali — ogni mossa deve essere dedotta dagli indizi.",
    "nn_clues_h2": "Come leggere gli indizi",
    "nn_clues_p1": "Ogni riga e colonna ha un indizio composto da uno o più numeri. Ogni numero rappresenta una <strong>sequenza consecutiva di mine</strong> in quella riga o colonna. Le sequenze appaiono in ordine (da sinistra a destra per le righe, dall'alto al basso per le colonne) e sono separate da almeno una cella sicura.",
    "nn_clues_p2": 'Ad esempio, un indizio di riga di <strong>3 &nbsp;1 &nbsp;2</strong> significa: tre mine di fila, uno spazio, una mina, uno spazio, poi due mine di fila. Un indizio di <strong>—</strong> significa che non ci sono mine in quella riga o colonna.',
    "nn_diff_h2": "Livelli di difficoltà",
    "nn_diff_beginner": "Principiante (8×8)",
    "nn_diff_intermediate": "Intermedio (10×10)",
    "nn_diff_expert": "Esperto (15×15)",
    "nn_diff_li1": "<strong>Principiante (8×8, 16 mine):</strong> Una griglia compatta con indizi brevi. Buono per imparare il meccanismo.",
    "nn_diff_li2": "<strong>Intermedio (10×10, 35 mine):</strong> Più celle e sequenze più dense richiedono un attento riferimento incrociato.",
    "nn_diff_li3": "<strong>Esperto (15×15, 75 mine):</strong> Una grande griglia con indizi complessi a più sequenze — una seria sfida di nonogramma.",
    "nn_strat_h2": "Consigli strategici",
    "nn_strat_li1": "<strong>Inizia con righe/colonne a indizio zero.</strong> Un indizio '—' significa che ogni cella in quella riga è sicura — rivelale tutte gratuitamente.",
    "nn_strat_li2": "<strong>Usa l'analisi di sovrapposizione.</strong> Se una sequenza è abbastanza grande da sovrapporsi in ogni posizionamento valido, quelle celle sovrapposte sono definitivamente mine.",
    "nn_strat_li3": "<strong>Fai riferimenti incrociati tra righe e colonne.</strong> L'indizio di riga e l'indizio di colonna di una cella insieme spesso restringono completamente il suo stato.",
    "nn_strat_li4": "<strong>Segna le mine prima di rivelare.</strong> Una volta certo che una cella è una mina, segnala prima di fare clic sulle celle sicure adiacenti — mantiene il contatore mine preciso e il tabellone leggibile.",
    "nn_about_h2": "Informazioni su Nonosweeper",
}

insert_nn.LANGS["ko"] = {
    "nn_bridge": "지뢰찾기가 노노그램을 만나다 — 행과 열 단서를 사용해 지뢰를 찾으세요.",
    "nn_btn_daily": "📅 오늘의",
    "nn_btn_new_random": "🎲 새 랜덤",
    "nn_btn_random": "🎲 랜덤",
    "nn_btn_retry": "🔄 다시 시도",
    "nn_label_potd": "📅 오늘의 퍼즐",
    "nn_overlay_solved": "🎉 해결됨!",
    "nn_save_score": "점수 저장",
    "nn_lb_today": "🏆 오늘의 최고 기록",
    "nn_instructions": "<strong>왼쪽 클릭</strong>으로 공개 — <em>지뢰를 클릭하면 게임이 끝납니다!</em> &nbsp;|&nbsp; <strong>오른쪽 클릭</strong>으로 전환: 깃발 💣 &rarr; 불확실 ? &rarr; 숨김. &nbsp;|&nbsp; 모든 안전한 셀을 공개하면 <strong>승리</strong>합니다.",
    "nn_what_h2": "Nonosweeper란 무엇인가요?",
    "nn_what_p1": "Nonosweeper는 두 가지 사랑받는 퍼즐 형식을 결합한 하이브리드 퍼즐입니다: <strong>지뢰찾기</strong>의 지뢰 제거 긴장감과 <strong>노노그램</strong>(Picross 또는 Griddler라고도 함)의 격자 추론 논리입니다. 표준 지뢰찾기와 달리 숫자를 공개하기 위해 무작위로 클릭하지 않습니다 — 대신 노노그램처럼 처음부터 행과 열 단서 전체 세트가 보입니다. 여러분의 역할은 단서를 사용해 어떤 셀에 지뢰가 있는지 정확히 파악한 다음 안전한 셀을 클릭해 공개하는 것입니다.",
    "nn_what_p2": "지뢰찾기 요소가 긴장감을 높여줍니다: 지뢰를 한 번만 잘못 클릭해도 퍼즐이 즉시 끝납니다. 안전한 첫 번째 클릭도 없고 무작위 추측도 허용되지 않습니다 — 모든 이동은 단서에서 추론해야 합니다.",
    "nn_clues_h2": "단서 읽는 방법",
    "nn_clues_p1": "각 행과 열에는 하나 이상의 숫자로 구성된 단서가 있습니다. 각 숫자는 해당 행이나 열의 <strong>연속 지뢰 묶음</strong>을 나타냅니다. 묶음은 순서대로 표시되며(행은 왼쪽에서 오른쪽, 열은 위에서 아래) 최소 하나의 안전한 셀로 구분됩니다.",
    "nn_clues_p2": '예를 들어 행 단서 <strong>3 &nbsp;1 &nbsp;2</strong>는 지뢰 3개 연속, 간격, 지뢰 1개, 간격, 지뢰 2개 연속을 의미합니다. <strong>—</strong> 단서는 해당 행이나 열에 지뢰가 전혀 없음을 의미합니다.',
    "nn_diff_h2": "난이도 수준",
    "nn_diff_beginner": "초급 (8×8)",
    "nn_diff_intermediate": "중급 (10×10)",
    "nn_diff_expert": "전문가 (15×15)",
    "nn_diff_li1": "<strong>초급 (8×8, 지뢰 16개):</strong> 짧은 단서가 있는 소형 격자. 메커닉을 배우기에 좋습니다.",
    "nn_diff_li2": "<strong>중급 (10×10, 지뢰 35개):</strong> 더 많은 셀과 더 밀집한 묶음은 신중한 교차 참조가 필요합니다.",
    "nn_diff_li3": "<strong>전문가 (15×15, 지뢰 75개):</strong> 복잡한 다중 묶음 단서가 있는 대형 격자 — 진지한 노노그램 도전.",
    "nn_strat_h2": "전략 팁",
    "nn_strat_li1": "<strong>단서가 없는 행/열부터 시작하세요.</strong> '—' 단서는 그 줄의 모든 셀이 안전하다는 의미입니다 — 모두 무료로 공개하세요.",
    "nn_strat_li2": "<strong>겹침 분석을 사용하세요.</strong> 묶음이 모든 유효한 배치에서 스스로 겹칠 만큼 충분히 크면, 그 겹치는 셀들은 확실히 지뢰입니다.",
    "nn_strat_li3": "<strong>행과 열을 교차 참조하세요.</strong> 셀의 행 단서와 열 단서를 함께 보면 종종 상태를 완전히 좁힐 수 있습니다.",
    "nn_strat_li4": "<strong>공개하기 전에 지뢰를 표시하세요.</strong> 셀이 지뢰임을 확신하면 인접한 안전한 셀을 클릭하기 전에 표시하세요 — 지뢰 카운터를 정확하게 유지하고 보드를 읽기 쉽게 만듭니다.",
    "nn_about_h2": "Nonosweeper 소개",
}

if __name__ == "__main__":
    for lang in ["ru", "pt", "it", "ko"]:
        insert_nn.insert_lang(lang)
