# -*- coding: utf-8 -*-
"""15-Puzzle fp_* batch 3: ko, ja, zh, zh-hant"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import insert_fp

insert_fp.LANGS["ko"] = {
    "fp_col_moves": "수",
    "fp_gen_copy": "복사",
    "fp_gen_delete": "삭제",
    "fp_gen_file_label": "JPG 또는 PNG, 최대 2MB",
    "fp_gen_limit_post": "-퍼즐 제한. 저장된 퍼즐을 삭제하여 공간을 만드세요.",
    "fp_gen_limit_pre": "한도에 도달했습니다\xa0",
    "fp_gen_limit_reached": "퍼즐 한도 도달",
    "fp_gen_mode_h2": "2. 사진 모드 선택",
    "fp_gen_mode_hint": "<strong>타일:</strong> 사진이 타일에 걸쳐 슬라이스되어 함께 섞입니다.<br><strong>완성 시 공개:</strong> 타일에 숫자가 표시되며, 완성하면 아래 사진이 공개됩니다.",
    "fp_gen_mode_reveal": "완성 시 공개",
    "fp_gen_mode_tiles": "타일",
    "fp_gen_no_puzzles": "아직 저장된 퍼즐이 없습니다. 위에서 만들어 보세요!",
    "fp_gen_refresh": "새로고침",
    "fp_gen_refresh_hint": "아래 저장 목록에서 확인하려면 새로고침하세요.",
    "fp_gen_save_btn": "저장 &amp; 링크 얻기",
    "fp_gen_saved_title": "퍼즐이 저장되었습니다! 이 링크를 공유하세요:",
    "fp_gen_scramble": "↺ 섞기",
    "fp_gen_signin_btn": "로그인",
    "fp_gen_signin_msg": '사진을 업로드하고 퍼즐을 저장하려면 <a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">로그인</a>해야 합니다.',
    "fp_gen_title_label": "퍼즐 제목 (선택 사항)",
    "fp_gen_title_ph": "나만의 멋진 퍼즐",
    "fp_gen_untitled": "제목 없는 퍼즐",
    "fp_gen_upload_h2": "1. 사진 업로드",
    "fp_gen_your_puzzles": "저장된 퍼즐",
    "fp_htp_back": "← 오늘의 퍼즐 플레이",
    "fp_htp_controls_desktop_li1": "<strong>타일을 클릭</strong>하여 빈 공간 옆의 타일을 밀어 넣으세요.",
    "fp_htp_controls_desktop_li2": "<strong>같은 행 또는 열에서 더 멀리 있는 타일을 클릭</strong>하면 타일과 빈 공간 사이의 전체 타일 줄이 한 번에 함께 이동합니다 — 실제 물리적 퍼즐처럼요.",
    "fp_htp_controls_desktop_li3": "<strong>방향키</strong>를 사용하면 해당 방향에서 빈 공간으로 타일을 이동합니다.",
    "fp_htp_controls_footer": "<strong>새 게임</strong> 버튼을 사용하면 언제든지 보드를 초기화하고 다시 시작할 수 있습니다.",
    "fp_htp_controls_h2": "조작법",
    "fp_htp_controls_mobile_li1": "<strong>타일을 탭</strong>하여 빈 공간 옆의 타일을 밀어 넣으세요.",
    "fp_htp_controls_mobile_li2": "<strong>더 멀리 있는 타일을 탭</strong>하면 같은 행 또는 열 전체가 한 번에 이동합니다.",
    "fp_htp_daily_h2": "오늘의 퍼즐",
    "fp_htp_daily_p1": "매일 자정 UTC에 새 퍼즐이 생성됩니다 — 전 세계 모든 플레이어에게 동일한 섞인 보드가 제공됩니다. 퍼즐을 완성하고 점수를 제출하여 리더보드에서 순위를 확인하세요.",
    "fp_htp_daily_p2": '<a href="/other/15puzzle/generator">퍼즐 생성기</a>를 사용하여 나만의 사진 퍼즐을 만들 수도 있습니다 — 이미지를 업로드하고, 모드를 선택하고, 누구에게나 링크를 공유하세요.',
    "fp_htp_desc": "15-퍼즐 플레이 방법을 알아보세요 — 클래식 슬라이딩 타일 게임. 규칙, 조작법, 사진 모드, 빠른 풀이 전략을 이해하세요.",
    "fp_htp_ex_midgame": "진행 중. 위쪽 행이 자리를 잡아가고 있습니다. 위에서 아래로 한 번에 한 행씩 완성하는 데 집중하세요.",
    "fp_htp_ex_nearlydone": "거의 완성. 아래쪽 행만 섞여 있습니다. 이 단계에서는 세밀한 조정이 필요합니다 — 이미 완성된 행의 진행 상황을 되돌리지 마세요.",
    "fp_htp_ex_scrambled": "시작 위치. 타일은 무작위로 섞이지만 항상 풀 수 있습니다. 빈 공간(어두운 사각형)은 보드 어디에나 있을 수 있습니다.",
    "fp_htp_ex_solved": "완성! 모든 타일이 순서대로 배열되고 전체 이미지가 공개됩니다. 시간과 이동 횟수가 리더보드에 기록됩니다.",
    "fp_htp_example_h2": "예시: 단계별 풀이",
    "fp_htp_example_intro": "아래 스크린샷은 Lady Di's Mines를 이미지로 사용한 사진 퍼즐의 풀이 과정을 보여줍니다. 각 타일에는 숫자와 그림 조각이 있어 풀이 중에 이미지를 시각적 가이드로 활용할 수 있습니다.",
    "fp_htp_goal_h2": "목표",
    "fp_htp_goal_p1": "15개의 타일을 오름차순으로 — 왼쪽에서 오른쪽, 위에서 아래로 — 빈 공간이 오른쪽 하단 모서리에 오도록 배열하세요. 완성된 위치는 다음과 같습니다: 맨 위 행에 1, 2, 3, 4, 그 다음 5, 6, 7, 8, 그 다음 9, 10, 11, 12, 그 다음 13, 14, 15와 빈칸.",
    "fp_htp_goal_p2": "점수는 사용한 이동 횟수와 풀이 속도의 조합입니다. 이동 횟수가 적을수록, 시간이 짧을수록 리더보드 순위가 높아집니다.",
    "fp_htp_intro": "15-퍼즐은 4×4 격자에서 진행되는 클래식 슬라이딩 타일 게임입니다. 15개의 번호가 매겨진 타일이 보드를 채우고 하나의 빈 공간이 남습니다. 타일을 빈 공간으로 밀어 1에서 15까지 순서대로 배열하세요.",
    "fp_htp_photo_h2": "사진 퍼즐 모드",
    "fp_htp_photo_p1": "오늘의 퍼즐과 커스텀 사진 퍼즐은 두 가지 시각적 모드를 제공합니다:",
    "fp_htp_photo_reveal": "<strong>완성 시 공개</strong> — 풀이 중에는 타일에 숫자만 표시됩니다. 마지막 타일을 올바른 위치에 놓으면 전체 사진이 아래에서 공개됩니다. 이미지는 힌트가 아닌 완성의 보상입니다.",
    "fp_htp_photo_tiles": "<strong>타일 모드</strong> — 각 타일에 사진 조각이 표시됩니다. 이미지가 풀이를 안내하는 시각적 맥락을 제공합니다 — 숫자 위에 두 번째 정보 레이어로 그림을 활용하세요.",
    "fp_htp_strategy_h2": "전략",
    "fp_htp_strategy_p1": "<strong>위에서부터 행별로 풀어나가세요.</strong> 1행과 2행은 위의 것을 흩뜨리지 않고 각각 완성하고 고정할 수 있습니다. 마지막 두 행(타일 9–15)은 회전 기법을 사용하여 함께 풀어야 합니다.",
    "fp_htp_strategy_p2": "<strong>타일 1과 타일 2를 함께 배치하세요.</strong> 타일 1만 제자리로 밀려고 하면 타일 2가 밀리는 경우가 많습니다. 대신 타일 1과 2를 동시에 올바른 열 위치로 이동한 다음 동시에 맨 위 행으로 회전시키세요.",
    "fp_htp_strategy_p3": "<strong>다중 타일 슬라이드를 활용하세요.</strong> 빈 공간에 직접 인접하지 않은 타일을 클릭하거나 탭하면 사이에 있는 전체 행 또는 열이 이동합니다. 이것은 타일을 하나씩 이동하는 것보다 빠르며 효율적인 풀이에 필수적입니다.",
    "fp_htp_strategy_p4": "<strong>이동 횟수를 세세요.</strong> 다중 타일 슬라이드를 포함하여 모든 슬라이드가 한 번의 이동으로 계산됩니다. 잘 계획된 다중 타일 슬라이드 하나로 여러 번의 단일 타일 이동을 절약할 수 있습니다 — 횟수를 최소화하기 위해 미리 계획하세요.",
    "fp_htp_title": "15-퍼즐 플레이 방법 | minesweeper.org",
    "fp_moves": "이동:",
    "fp_name_label": "이름",
    "fp_new_game": "↺ 새 게임",
    "fp_photo_puzzle": "사진 퍼즐",
    "fp_same_for_all": "모든 사람에게 동일한 퍼즐 · 자정 UTC에 초기화",
    "fp_solved": "🎉 완성!",
    "fp_submit_score": "점수 제출",
    "fp_time": "시간:",
    "fp_today_heading": "오늘 — ",
}

insert_fp.LANGS["ja"] = {
    "fp_col_moves": "手数",
    "fp_gen_copy": "コピー",
    "fp_gen_delete": "削除",
    "fp_gen_file_label": "JPGまたはPNG、最大2MB",
    "fp_gen_limit_post": "パズルの上限。保存済みパズルを削除してスペースを確保してください。",
    "fp_gen_limit_pre": "上限に達しました\xa0",
    "fp_gen_limit_reached": "パズル上限に到達",
    "fp_gen_mode_h2": "2. 写真モードを選択",
    "fp_gen_mode_hint": "<strong>タイル:</strong> 写真がタイルに分割されて一緒にシャッフルされます。<br><strong>クリア時に公開:</strong> タイルには数字のみ表示され、完成すると下の写真が公開されます。",
    "fp_gen_mode_reveal": "クリア時に公開",
    "fp_gen_mode_tiles": "タイル",
    "fp_gen_no_puzzles": "保存済みパズルがまだありません。上で作成してみましょう！",
    "fp_gen_refresh": "更新",
    "fp_gen_refresh_hint": "下の保存リストで確認するには更新してください。",
    "fp_gen_save_btn": "保存 &amp; リンクを取得",
    "fp_gen_saved_title": "パズルが保存されました！このリンクをシェアしてください：",
    "fp_gen_scramble": "↺ シャッフル",
    "fp_gen_signin_btn": "サインイン",
    "fp_gen_signin_msg": '写真をアップロードしてパズルを保存するには<a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">サインイン</a>が必要です。',
    "fp_gen_title_label": "パズルのタイトル（任意）",
    "fp_gen_title_ph": "私の素敵なパズル",
    "fp_gen_untitled": "無題のパズル",
    "fp_gen_upload_h2": "1. 写真をアップロード",
    "fp_gen_your_puzzles": "保存済みパズル",
    "fp_htp_back": "← 今日のパズルをプレイ",
    "fp_htp_controls_desktop_li1": "空きスペースに隣接する<strong>タイルをクリック</strong>してスライドさせます。",
    "fp_htp_controls_desktop_li2": "同じ行または列でより遠くにある<strong>タイルをクリック</strong>すると、そのタイルと空きスペースの間にある全タイルが一度に一緒にスライドします — 本物の物理パズルと同じように。",
    "fp_htp_controls_desktop_li3": "<strong>矢印キー</strong>で対応する方向から空きスペースへタイルを移動します。",
    "fp_htp_controls_footer": "<strong>新しいゲーム</strong>ボタンを使うと、いつでもボードをリセットして最初からやり直せます。",
    "fp_htp_controls_h2": "操作方法",
    "fp_htp_controls_mobile_li1": "空きスペースに隣接する<strong>タイルをタップ</strong>してスライドさせます。",
    "fp_htp_controls_mobile_li2": "より遠くにある<strong>タイルをタップ</strong>すると、同じ行または列全体が一度に移動します。",
    "fp_htp_daily_h2": "デイリーパズル",
    "fp_htp_daily_p1": "毎日UTC深夜に新しいパズルが生成されます — 世界中のすべてのプレイヤーに同じシャッフルされたボードが提供されます。解いてスコアを提出し、リーダーボードでのランキングを確認しましょう。",
    "fp_htp_daily_p2": '<a href="/other/15puzzle/generator">パズルジェネレーター</a>を使って独自のフォトパズルを作成することもできます — 画像をアップロードし、モードを選択して、誰とでもリンクをシェアしてください。',
    "fp_htp_desc": "15パズルのプレイ方法を学びましょう — クラシックなスライドタイルゲーム。ルール、操作方法、写真モード、速く解くための戦略を理解しましょう。",
    "fp_htp_ex_midgame": "途中経過。上の行が揃ってきています。上から順に一行ずつ完成させることに集中しましょう。",
    "fp_htp_ex_nearlydone": "もう少しで完成。下の行だけが乱れています。この段階では細かい調整が必要です — すでに完成した行の進捗を崩さないようにしましょう。",
    "fp_htp_ex_scrambled": "開始位置。タイルはランダムにシャッフルされますが、必ず解けるようになっています。空きスペース（暗い四角）はボードのどこにでもある可能性があります。",
    "fp_htp_ex_solved": "完成！すべてのタイルが順番に並び、全体の画像が公開されます。あなたのタイムと手数がリーダーボードに記録されます。",
    "fp_htp_example_h2": "例：ステップバイステップの解き方",
    "fp_htp_example_intro": "以下のスクリーンショットは、Lady Di's Minesを画像に使ったフォトパズルの解き方を示しています。各タイルには数字と絵の断片があるので、解きながら画像を視覚的なガイドとして活用できます。",
    "fp_htp_goal_h2": "目標",
    "fp_htp_goal_p1": "15枚のタイルを昇順に — 左から右、上から下へ — 空きスペースが右下隅になるよう並べます。完成した配置は次のようになります：最上行に1、2、3、4、次に5、6、7、8、次に9、10、11、12、次に13、14、15と空白。",
    "fp_htp_goal_p2": "スコアは使った手数と解くのにかかった時間の組み合わせです。手数が少なく時間が短いほど、リーダーボードのランキングが上がります。",
    "fp_htp_intro": "15パズルは4×4グリッドでプレイするクラシックなスライドタイルゲームです。15枚の番号付きタイルがボードを埋め、1つの空きスペースが残ります。タイルを空きスペースにスライドさせて、1から15まで順番に並べ替えましょう。",
    "fp_htp_photo_h2": "フォトパズルモード",
    "fp_htp_photo_p1": "デイリーパズルとカスタムフォトパズルには2つの異なるビジュアルモードがあります：",
    "fp_htp_photo_reveal": "<strong>クリア時に公開</strong> — 解いている間タイルには数字のみ表示されます。最後のタイルを正しい位置に置くと、下から全体の写真が公開されます。画像はヒントではなく、完成の報酬です。",
    "fp_htp_photo_tiles": "<strong>タイルモード</strong> — 各タイルに写真のスライスが表示されます。画像が解き方を導く視覚的な文脈を提供します — 数字の上に第2の情報レイヤーとして絵を活用しましょう。",
    "fp_htp_strategy_h2": "戦略",
    "fp_htp_strategy_p1": "<strong>上から行ごとに解いていきましょう。</strong> 1行目と2行目は、上にあるものを乱さずにそれぞれ完成させて固定できます。最後の2行（タイル9〜15）は回転テクニックを使って一緒に解きます。",
    "fp_htp_strategy_p2": "<strong>タイル1とタイル2を一緒に配置しましょう。</strong> タイル1だけを所定の位置にスライドしようとすると、タイル2が動いてしまうことが多いです。代わりに、タイル1と2を同時に正しい列の位置に移動させてから、同時に最上行に回転させましょう。",
    "fp_htp_strategy_p3": "<strong>複数タイルスライドを活用しましょう。</strong> 空きスペースに直接隣接していないタイルをクリックまたはタップすると、間にある行または列全体が移動します。これはタイルを一枚ずつ動かすより速く、効率的な解き方に不可欠です。",
    "fp_htp_strategy_p4": "<strong>手数を数えましょう。</strong> 複数タイルスライドを含め、すべてのスライドが1手として数えられます。うまく計画された複数タイルスライド1回で、数回の単一タイル移動を節約できます — 手数を最小化するために事前に計画しましょう。",
    "fp_htp_title": "15パズルの遊び方 | minesweeper.org",
    "fp_moves": "手数：",
    "fp_name_label": "名前",
    "fp_new_game": "↺ 新しいゲーム",
    "fp_photo_puzzle": "フォトパズル",
    "fp_same_for_all": "全員同じパズル · UTC深夜にリセット",
    "fp_solved": "🎉 完成！",
    "fp_submit_score": "スコアを提出",
    "fp_time": "タイム：",
    "fp_today_heading": "今日 — ",
}

insert_fp.LANGS["zh"] = {
    "fp_col_moves": "步数",
    "fp_gen_copy": "复制",
    "fp_gen_delete": "删除",
    "fp_gen_file_label": "JPG 或 PNG，最大 2MB",
    "fp_gen_limit_post": "个拼图上限。删除已保存的拼图以腾出空间。",
    "fp_gen_limit_pre": "您已达到\xa0",
    "fp_gen_limit_reached": "已达到拼图上限",
    "fp_gen_mode_h2": "2. 选择照片模式",
    "fp_gen_mode_hint": "<strong>贴片：</strong> 照片被切割到贴片上并与之一起打乱。<br><strong>完成时揭示：</strong> 贴片显示数字；完成后揭示下方的照片。",
    "fp_gen_mode_reveal": "完成时揭示",
    "fp_gen_mode_tiles": "贴片",
    "fp_gen_no_puzzles": "暂无已保存的拼图。在上方创建一个吧！",
    "fp_gen_refresh": "刷新",
    "fp_gen_refresh_hint": "刷新以在下方已保存列表中查看。",
    "fp_gen_save_btn": "保存 &amp; 获取链接",
    "fp_gen_saved_title": "拼图已保存！分享此链接：",
    "fp_gen_scramble": "↺ 打乱",
    "fp_gen_signin_btn": "登录",
    "fp_gen_signin_msg": '您必须<a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">登录</a>才能上传照片和保存拼图。',
    "fp_gen_title_label": "拼图标题（可选）",
    "fp_gen_title_ph": "我的精彩拼图",
    "fp_gen_untitled": "无标题拼图",
    "fp_gen_upload_h2": "1. 上传照片",
    "fp_gen_your_puzzles": "我的已保存拼图",
    "fp_htp_back": "← 玩今日拼图",
    "fp_htp_controls_desktop_li1": "<strong>点击</strong>紧邻空格的贴片将其滑入。",
    "fp_htp_controls_desktop_li2": "<strong>点击同行或同列中较远的贴片</strong>，该贴片与空格之间的整行贴片会一起移动 — 就像真实的实体拼图一样。",
    "fp_htp_controls_desktop_li3": "<strong>方向键</strong>可将贴片从相应方向移入空格。",
    "fp_htp_controls_footer": "使用<strong>新游戏</strong>按钮随时重置棋盘并重新开始。",
    "fp_htp_controls_h2": "操作方式",
    "fp_htp_controls_mobile_li1": "<strong>点击</strong>紧邻空格的贴片将其滑入。",
    "fp_htp_controls_mobile_li2": "<strong>点击较远的贴片</strong>，同行或同列整体会一次性移动。",
    "fp_htp_daily_h2": "每日拼图",
    "fp_htp_daily_p1": "每天 UTC 午夜生成一个新拼图 — 全球每位玩家都面对同一个打乱的棋盘。完成拼图，提交分数，在排行榜上查看自己的排名。",
    "fp_htp_daily_p2": '您也可以使用<a href="/other/15puzzle/generator">拼图生成器</a>创建自己的照片拼图 — 上传任意图片，选择模式，与任何人分享链接。',
    "fp_htp_desc": "学习如何玩15拼图 — 经典滑块游戏。了解规则、操作方式、照片模式以及快速求解策略。",
    "fp_htp_ex_midgame": "进行到一半。顶部行正在归位。专注于从上到下逐行完成。",
    "fp_htp_ex_nearlydone": "接近完成。只有底部行还是乱的。此阶段需要细微调整 — 避免破坏已完成行的进度。",
    "fp_htp_ex_scrambled": "起始位置。贴片被随机打乱但始终有解。空格（深色方块）可能在棋盘任何位置。",
    "fp_htp_ex_solved": "完成！所有贴片按顺序排列，完整图像揭示。您的用时和步数被记录在排行榜上。",
    "fp_htp_example_h2": "示例：逐步求解过程",
    "fp_htp_example_intro": "以下截图展示了以 Lady Di's Mines 为图像的照片拼图求解过程。每个贴片都带有数字和图片片段 — 因此您可以在求解过程中将图像作为视觉引导。",
    "fp_htp_goal_h2": "目标",
    "fp_htp_goal_p1": "将全部 15 个贴片按升序排列 — 从左到右、从上到下 — 空格位于右下角。完成后的排列如下：顶行为 1、2、3、4，然后 5、6、7、8，然后 9、10、11、12，最后 13、14、15 和空格。",
    "fp_htp_goal_p2": "分数由您使用的步数和求解速度共同决定。步数越少、用时越短，排行榜排名越高。",
    "fp_htp_intro": "15拼图是在 4×4 方格上进行的经典滑块游戏。15 个编号贴片填满棋盘，留有一个空格。将贴片滑入空格，重新排列它们，直到所有贴片从 1 到 15 依次排列。",
    "fp_htp_photo_h2": "照片拼图模式",
    "fp_htp_photo_p1": "每日拼图和自定义照片拼图提供两种不同的视觉模式：",
    "fp_htp_photo_reveal": "<strong>完成时揭示</strong> — 求解过程中贴片只显示数字。当您将最后一个贴片放到正确位置时，完整照片从下方揭示。图像是完成的奖励，而非提示。",
    "fp_htp_photo_tiles": "<strong>贴片模式</strong> — 每个贴片显示照片的对应切片。图像为您的求解提供视觉背景 — 将图片作为数字之上的第二层信息加以利用。",
    "fp_htp_strategy_h2": "策略",
    "fp_htp_strategy_p1": "<strong>从顶部逐行求解。</strong> 第 1 行和第 2 行各自可以完成并固定，而不会干扰上方已完成的内容。最后两行（贴片 9–15）需使用旋转技巧一起求解。",
    "fp_htp_strategy_p2": "<strong>将贴片 1 和贴片 2 一起归位。</strong> 单独将贴片 1 滑入位置往往会移动贴片 2。应将贴片 1 和 2 同时移至正确的列位置，然后同时旋转到顶行。",
    "fp_htp_strategy_p3": "<strong>利用多贴片滑动。</strong> 点击或轻触不直接紧邻空格的贴片，会将两者之间的整行或整列一起移动。这比逐个移动贴片更快，是高效求解的关键。",
    "fp_htp_strategy_p4": "<strong>计算步数。</strong> 每次滑动（包括多贴片滑动）计为一步。一次精心策划的多贴片滑动可以节省数步单贴片移动 — 提前规划以最小化步数。",
    "fp_htp_title": "如何玩15拼图 | minesweeper.org",
    "fp_moves": "步数：",
    "fp_name_label": "名称",
    "fp_new_game": "↺ 新游戏",
    "fp_photo_puzzle": "照片拼图",
    "fp_same_for_all": "所有人相同的拼图 · UTC 午夜重置",
    "fp_solved": "🎉 完成！",
    "fp_submit_score": "提交分数",
    "fp_time": "用时：",
    "fp_today_heading": "今天 — ",
}

insert_fp.LANGS["zh-hant"] = {
    "fp_col_moves": "步數",
    "fp_gen_copy": "複製",
    "fp_gen_delete": "刪除",
    "fp_gen_file_label": "JPG 或 PNG，最大 2MB",
    "fp_gen_limit_post": "個拼圖上限。刪除已儲存的拼圖以騰出空間。",
    "fp_gen_limit_pre": "您已達到\xa0",
    "fp_gen_limit_reached": "已達到拼圖上限",
    "fp_gen_mode_h2": "2. 選擇照片模式",
    "fp_gen_mode_hint": "<strong>貼片：</strong> 照片被切割到貼片上並與之一起打亂。<br><strong>完成時揭示：</strong> 貼片顯示數字；完成後揭示下方的照片。",
    "fp_gen_mode_reveal": "完成時揭示",
    "fp_gen_mode_tiles": "貼片",
    "fp_gen_no_puzzles": "尚無已儲存的拼圖。在上方建立一個吧！",
    "fp_gen_refresh": "重新整理",
    "fp_gen_refresh_hint": "重新整理以在下方已儲存清單中查看。",
    "fp_gen_save_btn": "儲存 &amp; 取得連結",
    "fp_gen_saved_title": "拼圖已儲存！分享此連結：",
    "fp_gen_scramble": "↺ 打亂",
    "fp_gen_signin_btn": "登入",
    "fp_gen_signin_msg": '您必須<a href="/login?next=/other/15puzzle/generator" style="color:var(--accent2);font-weight:700;">登入</a>才能上傳照片和儲存拼圖。',
    "fp_gen_title_label": "拼圖標題（選填）",
    "fp_gen_title_ph": "我的精彩拼圖",
    "fp_gen_untitled": "無標題拼圖",
    "fp_gen_upload_h2": "1. 上傳照片",
    "fp_gen_your_puzzles": "我的已儲存拼圖",
    "fp_htp_back": "← 玩今日拼圖",
    "fp_htp_controls_desktop_li1": "<strong>點擊</strong>緊鄰空格的貼片將其滑入。",
    "fp_htp_controls_desktop_li2": "<strong>點擊同行或同欄中較遠的貼片</strong>，該貼片與空格之間的整行貼片會一起移動 — 就像真實的實體拼圖一樣。",
    "fp_htp_controls_desktop_li3": "<strong>方向鍵</strong>可將貼片從相應方向移入空格。",
    "fp_htp_controls_footer": "使用<strong>新遊戲</strong>按鈕隨時重置棋盤並重新開始。",
    "fp_htp_controls_h2": "操作方式",
    "fp_htp_controls_mobile_li1": "<strong>點擊</strong>緊鄰空格的貼片將其滑入。",
    "fp_htp_controls_mobile_li2": "<strong>點擊較遠的貼片</strong>，同行或同欄整體會一次性移動。",
    "fp_htp_daily_h2": "每日拼圖",
    "fp_htp_daily_p1": "每天 UTC 午夜產生一個新拼圖 — 全球每位玩家都面對同一個打亂的棋盤。完成拼圖，提交分數，在排行榜上查看自己的排名。",
    "fp_htp_daily_p2": '您也可以使用<a href="/other/15puzzle/generator">拼圖產生器</a>建立自己的照片拼圖 — 上傳任意圖片，選擇模式，與任何人分享連結。',
    "fp_htp_desc": "學習如何玩15拼圖 — 經典滑塊遊戲。了解規則、操作方式、照片模式以及快速求解策略。",
    "fp_htp_ex_midgame": "進行到一半。頂部行正在歸位。專注於從上到下逐行完成。",
    "fp_htp_ex_nearlydone": "接近完成。只有底部行還是亂的。此階段需要細微調整 — 避免破壞已完成行的進度。",
    "fp_htp_ex_scrambled": "起始位置。貼片被隨機打亂但始終有解。空格（深色方塊）可能在棋盤任何位置。",
    "fp_htp_ex_solved": "完成！所有貼片按順序排列，完整圖像揭示。您的用時和步數被記錄在排行榜上。",
    "fp_htp_example_h2": "示例：逐步求解過程",
    "fp_htp_example_intro": "以下截圖展示了以 Lady Di's Mines 為圖像的照片拼圖求解過程。每個貼片都帶有數字和圖片片段 — 因此您可以在求解過程中將圖像作為視覺引導。",
    "fp_htp_goal_h2": "目標",
    "fp_htp_goal_p1": "將全部 15 個貼片按升冪排列 — 從左到右、從上到下 — 空格位於右下角。完成後的排列如下：頂行為 1、2、3、4，然後 5、6、7、8，然後 9、10、11、12，最後 13、14、15 和空格。",
    "fp_htp_goal_p2": "分數由您使用的步數和求解速度共同決定。步數越少、用時越短，排行榜排名越高。",
    "fp_htp_intro": "15拼圖是在 4×4 方格上進行的經典滑塊遊戲。15 個編號貼片填滿棋盤，留有一個空格。將貼片滑入空格，重新排列它們，直到所有貼片從 1 到 15 依次排列。",
    "fp_htp_photo_h2": "照片拼圖模式",
    "fp_htp_photo_p1": "每日拼圖和自訂照片拼圖提供兩種不同的視覺模式：",
    "fp_htp_photo_reveal": "<strong>完成時揭示</strong> — 求解過程中貼片只顯示數字。當您將最後一個貼片放到正確位置時，完整照片從下方揭示。圖像是完成的獎勵，而非提示。",
    "fp_htp_photo_tiles": "<strong>貼片模式</strong> — 每個貼片顯示照片的對應切片。圖像為您的求解提供視覺背景 — 將圖片作為數字之上的第二層資訊加以利用。",
    "fp_htp_strategy_h2": "策略",
    "fp_htp_strategy_p1": "<strong>從頂部逐行求解。</strong> 第 1 行和第 2 行各自可以完成並固定，而不會干擾上方已完成的內容。最後兩行（貼片 9–15）需使用旋轉技巧一起求解。",
    "fp_htp_strategy_p2": "<strong>將貼片 1 和貼片 2 一起歸位。</strong> 單獨將貼片 1 滑入位置往往會移動貼片 2。應將貼片 1 和 2 同時移至正確的欄位置，然後同時旋轉到頂行。",
    "fp_htp_strategy_p3": "<strong>利用多貼片滑動。</strong> 點擊或輕觸不直接緊鄰空格的貼片，會將兩者之間的整行或整欄一起移動。這比逐個移動貼片更快，是高效求解的關鍵。",
    "fp_htp_strategy_p4": "<strong>計算步數。</strong> 每次滑動（包括多貼片滑動）計為一步。一次精心規劃的多貼片滑動可以節省數步單貼片移動 — 提前規劃以最小化步數。",
    "fp_htp_title": "如何玩15拼圖 | minesweeper.org",
    "fp_moves": "步數：",
    "fp_name_label": "名稱",
    "fp_new_game": "↺ 新遊戲",
    "fp_photo_puzzle": "照片拼圖",
    "fp_same_for_all": "所有人相同的拼圖 · UTC 午夜重置",
    "fp_solved": "🎉 完成！",
    "fp_submit_score": "提交分數",
    "fp_time": "用時：",
    "fp_today_heading": "今天 — ",
}

if __name__ == "__main__":
    for lang in ["ko", "ja", "zh", "zh-hant"]:
        insert_fp.insert_lang(lang)
