/**
 * gameEngine.test.js
 *
 * Tests for the ported game engine functions.
 * Test vectors for calcBoardHash come from mobile/ios/BoardHashSpec.md.
 * Test vectors for isSolvable come from mobile/ios/NoGuessSolverSpec.md.
 */

import {
  neighbors,
  placeMines,
  isSolvable,
  placeMinesNoGuess,
  calcBoardHash,
  calc3BV,
  BOARD_SIZES,
} from '../gameEngine';

// ── neighbors ─────────────────────────────────────────────────────────────────

describe('neighbors', () => {
  test('centre cell on 3×3 has 8 neighbours', () => {
    expect(neighbors(1, 1, 3, 3)).toHaveLength(8);
  });

  test('corner cell has 3 neighbours', () => {
    expect(neighbors(0, 0, 3, 3)).toHaveLength(3);
  });

  test('edge cell has 5 neighbours', () => {
    expect(neighbors(0, 1, 3, 3)).toHaveLength(5);
  });

  test('does not include the cell itself', () => {
    const result = neighbors(1, 1, 3, 3);
    expect(result.find(([r, c]) => r === 1 && c === 1)).toBeUndefined();
  });

  test('1×1 board has no neighbours', () => {
    expect(neighbors(0, 0, 1, 1)).toHaveLength(0);
  });
});

// ── placeMines ────────────────────────────────────────────────────────────────

describe('placeMines', () => {
  const { rows, cols, mines } = BOARD_SIZES.beginner; // 9×9, 10 mines

  test('returns correct mine count', () => {
    const { mineSet } = placeMines(rows, cols, mines, 4, 4);
    expect(mineSet.size).toBe(mines);
  });

  test('safe zone around first click contains no mines', () => {
    for (let trial = 0; trial < 20; trial++) {
      const safeR = 4, safeC = 4;
      const { mineSet } = placeMines(rows, cols, mines, safeR, safeC);
      for (let dr = -1; dr <= 1; dr++) {
        for (let dc = -1; dc <= 1; dc++) {
          const nr = safeR + dr, nc = safeC + dc;
          if (nr >= 0 && nr < rows && nc >= 0 && nc < cols) {
            expect(mineSet.has(nr * cols + nc)).toBe(false);
          }
        }
      }
    }
  });

  test('board numbers match mine adjacency', () => {
    const safeR = 0, safeC = 0;
    const { mineSet, board } = placeMines(rows, cols, mines, safeR, safeC);
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const idx = r * cols + c;
        if (mineSet.has(idx)) {
          expect(board[r][c]).toBe(-1);
        } else {
          const count = neighbors(r, c, rows, cols)
            .filter(([nr, nc]) => mineSet.has(nr * cols + nc)).length;
          expect(board[r][c]).toBe(count);
        }
      }
    }
  });

  test('all mine indices are within board bounds', () => {
    const { mineSet } = placeMines(rows, cols, mines, 0, 0);
    for (const idx of mineSet) {
      expect(idx).toBeGreaterThanOrEqual(0);
      expect(idx).toBeLessThan(rows * cols);
    }
  });
});

// ── isSolvable ────────────────────────────────────────────────────────────────

describe('isSolvable', () => {
  test('a trivial 3×3 board with 1 mine in the corner is solvable from a blank cell', () => {
    // 3×3, mine at (0,0). Start at (2,2) which is blank (0).
    // BFS from (2,2) floods all blank cells and their borders, revealing enough
    // numbered cells for the solver to deduce the mine location without guessing.
    const rows = 3, cols = 3;
    const mineSet = new Set([0]);
    const board = [
      [-1, 1, 0],
      [ 1, 1, 0],
      [ 0, 0, 0],
    ];
    expect(isSolvable(rows, cols, mineSet, board, 2, 2)).toBe(true);
  });

  test('returns false when board requires a guess', () => {
    // 1×3 board: [ mine | covered | mine ]
    // Starting from the middle reveals it as "2" but both neighbours are unknown
    // — the solver cannot determine which is which without guessing.
    const rows = 1, cols = 5;
    // Mines at indices 0 and 4. Start at index 2.
    const mineSet = new Set([0, 4]);
    const board = [[-1, 1, 0, 1, -1]];
    // The cell at (0,2) = 0, so BFS reveals (0,1) and (0,3).
    // (0,1)=1: one hidden neighbour (0,0)=mine → marks mine ✓
    // (0,3)=1: one hidden neighbour (0,4)=mine → marks mine ✓
    // Actually this IS solvable. Use a harder case:
    // 1×4: mines at 0 and 3. Start at 1.
    const rows2 = 1, cols2 = 4;
    const mineSet2 = new Set([0, 3]);
    const board2 = [[-1, 1, 1, -1]];
    // Start at (0,1): revealed[1]=1, board[0][1]=1
    // hidden neighbours of cell 1: cell 0 (mine) → remaining=0 after counting known mine?
    // Actually cell 0 is in mineSet but not yet in knownMine → it's a hidden unrevealed cell.
    // hidden=[0], remaining=1 → remaining===hidden.length → mark 0 as mine ✓
    // Then cell 2: revealed? No — BFS from cell 1 only reveals cell 1 (value=1, not 0).
    // Cell 2 is never revealed → isSolvable returns false.
    expect(isSolvable(rows2, cols2, mineSet2, board2, 0, 1)).toBe(false);
  });

  test('solvable boards are generated by placeMinesNoGuess', () => {
    const { rows, cols, mines } = BOARD_SIZES.beginner;
    // Run a handful of trials — each should be solvable
    let solvableCount = 0;
    for (let i = 0; i < 10; i++) {
      const { mineSet, board } = placeMinesNoGuess(rows, cols, mines, 4, 4);
      if (isSolvable(rows, cols, mineSet, board, 4, 4)) solvableCount++;
    }
    // Expect all 10 (or at worst the fallback case) to pass — 9/10 is a safe threshold
    expect(solvableCount).toBeGreaterThanOrEqual(9);
  });
});

// ── calcBoardHash — test vectors from BoardHashSpec.md ────────────────────────

describe('calcBoardHash', () => {
  test('mine only at cell 0 on 9×9 board', () => {
    expect(calcBoardHash(9, 9, new Set([0]))).toBe('AQAAAAAAAAAAAAA=');
  });

  test('mine only at cell 9 on 9×9 board', () => {
    expect(calcBoardHash(9, 9, new Set([9]))).toBe('AAIAAAAAAAAAAAA=');
  });

  test('mines at cells 0 and 80 (corners) on 9×9 board', () => {
    expect(calcBoardHash(9, 9, new Set([0, 80]))).toBe('AQAAAAAAAAAAAAE=');
  });

  test('empty mine set produces all-zero base64', () => {
    const hash = calcBoardHash(9, 9, new Set());
    // ceil(9*9/8) = 11 zero bytes → base64 = 'AAAAAAAAAAAAAAA=' (15 A's + 1 padding)
    expect(hash).toBe('AAAAAAAAAAAAAAA=');
  });

  test('same mineSet always produces same hash', () => {
    const mineSet = new Set([1, 5, 20, 55, 79]);
    expect(calcBoardHash(9, 9, mineSet)).toBe(calcBoardHash(9, 9, mineSet));
  });

  test('hash length is consistent with board size', () => {
    // ceil(9*9/8)=11 bytes → base64 length = ceil(11/3)*4 = 16
    expect(calcBoardHash(9, 9, new Set([0])).length).toBe(16);
    // ceil(16*16/8)=32 bytes → base64 length = ceil(32/3)*4 = 44
    expect(calcBoardHash(16, 16, new Set([0])).length).toBe(44);
    // ceil(16*30/8)=60 bytes → base64 length = ceil(60/3)*4 = 80
    expect(calcBoardHash(16, 30, new Set([0])).length).toBe(80);
  });
});

// ── calc3BV ───────────────────────────────────────────────────────────────────

describe('calc3BV', () => {
  test('all-blank board (no mines) has 3BV of 1', () => {
    // A board with no mines: every cell is blank (0), one big opening = 1
    const rows = 3, cols = 3;
    const mineSet = new Set();
    const board = Array.from({ length: rows }, () => Array(cols).fill(0));
    expect(calc3BV(board, rows, cols, mineSet)).toBe(1);
  });

  test('fully isolated numbers each count as 1', () => {
    // 1×3 board: mine at centre, numbered cells on each side, no openings
    // board = [1, -1, 1], mineSet = {1}
    const rows = 1, cols = 3;
    const mineSet = new Set([1]);
    const board = [[1, -1, 1]];
    // No blank cells → no openings. Two isolated numbered cells → 3BV = 2
    expect(calc3BV(board, rows, cols, mineSet)).toBe(2);
  });

  test('opening region + isolated number counts correctly', () => {
    // 3×3, mine at (0,0). Cells (0,1),(1,0),(1,1) are numbered; rest blank opening.
    const rows = 3, cols = 3;
    const mineSet = new Set([0]); // idx 0 = (0,0)
    const board = [
      [-1, 1, 0],
      [ 1, 1, 0],
      [ 0, 0, 0],
    ];
    // One opening region covers all non-mine cells → 3BV = 1
    expect(calc3BV(board, rows, cols, mineSet)).toBe(1);
  });

  test('3BV is always at least 1 for a valid board', () => {
    const { rows, cols, mines } = BOARD_SIZES.beginner;
    for (let i = 0; i < 5; i++) {
      const { mineSet, board } = placeMines(rows, cols, mines, 4, 4);
      expect(calc3BV(board, rows, cols, mineSet)).toBeGreaterThanOrEqual(1);
    }
  });

  test('3BV never exceeds non-mine cell count', () => {
    const { rows, cols, mines } = BOARD_SIZES.beginner;
    for (let i = 0; i < 5; i++) {
      const { mineSet, board } = placeMines(rows, cols, mines, 4, 4);
      expect(calc3BV(board, rows, cols, mineSet)).toBeLessThanOrEqual(rows * cols - mines);
    }
  });
});

// ── BOARD_SIZES ───────────────────────────────────────────────────────────────

describe('BOARD_SIZES', () => {
  test('beginner is 9×9 with 10 mines', () => {
    expect(BOARD_SIZES.beginner).toEqual({ rows: 9, cols: 9, mines: 10 });
  });

  test('intermediate is 16×16 with 40 mines', () => {
    expect(BOARD_SIZES.intermediate).toEqual({ rows: 16, cols: 16, mines: 40 });
  });

  test('expert is 30×16 with 99 mines', () => {
    expect(BOARD_SIZES.expert).toEqual({ rows: 30, cols: 16, mines: 99 });
  });
});
